### ISSUE TITLE
elasticSearch cannot search anything

### ISSUE THREAD

**Issue by crazy2323** [linkedin/WhereHows#1008]
elasticSearch cannot search anything，Is there any wrong by conf?

**Comment by alyiwang** [comment]
@camelliazhang  could you comment on this? Thanks

**Comment by Ash-Mishra** [comment]
The documentation in the starting is wrong.
![image](https://user-images.githubusercontent.com/36027768/48548069-106b5780-e8f2-11e8-96bb-d4473e7a5438.png)
don't do this. If you have done this please delete from elasticserch.
Try this the documentation in wherehows-data-model/ELASTICSEARCH
This will sole the issue for sure. The initial documentation is not proper for elasticsearch.
![image](https://user-images.githubusercontent.com/36027768/48548271-8f609000-e8f2-11e8-915d-e35d3775b2b5.png)

**Comment by keremsahin1** [comment]
Dear issue owner,

Thanks for your interest in WhereHows. We have recently announced DataHub which is the rebranding of WhereHows. LinkedIn improved the architecture of WhereHows and rebranded WhereHows into DataHub and replaced its metadata infrastructure in this direction. DataHub is a more advanced and improved metadata management product compared to WhereHows. 

Unfortunately, we have to stop supporting WhereHows to better focus on DataHub and offer more help to DataHub users. Therefore, we will drop all issues related to WhereHows and will not accept any contribution for it. Active development for DataHub has already started on `datahub` branch and will continue to live in there until it's finally merged to master and project is renamed to DataHub. 

Please check the `datahub` branch to get familar with DataHub.

Best,
DataHub team
