### ISSUE TITLE
Performance about multiple calls to replace

### ISSUE THREAD

**Issue by o0lwj0o** [linkedin/WhereHows#1019]
Hi,
&nbsp;&nbsp;&nbsp;&nbsp;I have found multiple calls to `String.replace(.. , ..)` about the same pattern in the project.
For example, in the file WhereHows/wherehows-frontend/app/utils/Search.java:
```Java
   ...
   if (tableNotInList != null && tableNotInList.size() > 0) {
    ...
          shouldValueList.add(Json.parse(mustNotQueryUnit.replace("$FIELD", "name").
              replace("$VALUE", table.toLowerCase().trim())));
    ...
    }
    if (fieldAnyList != null && fieldAnyList.size() > 0) {
    ...
          shouldValueList.add(Json.parse(hasChildValue.replace("$TYPE", "field").
              replace("$FIELD", "field_name").
              replace("$VALUE", field.toLowerCase().trim())));
    ...
    }
    if (fieldAllList != null && fieldAllList.size() > 0) {
     ...
          mustValueList.add(Json.parse(hasChildValue.replace("$TYPE", "field").
              replace("$FIELD", "field_name").
              replace("$VALUE", field.toLowerCase().trim())));
    ...
    }
   ...
```
&nbsp;&nbsp;&nbsp;&nbsp;There are multiple calls to `replace` about "$FIELD", "$VALUE" and "$TYPE". If it was achieved like the following code, it will promote its performance and be able to reuse the pattern.
```Java
Pattern pattern = Pattern.compile(regex);
pattern.matcher(str).replaceAll(repl);
```

**Comment by alyiwang** [comment]
That's a good suggestion. Thanks!  @camelliazhang  could you comment on this?

**Comment by keremsahin1** [comment]
Dear issue owner,

Thanks for your interest in WhereHows. We have recently announced DataHub which is the rebranding of WhereHows. LinkedIn improved the architecture of WhereHows and rebranded WhereHows into DataHub and replaced its metadata infrastructure in this direction. DataHub is a more advanced and improved metadata management product compared to WhereHows. 

Unfortunately, we have to stop supporting WhereHows to better focus on DataHub and offer more help to DataHub users. Therefore, we will drop all issues related to WhereHows and will not accept any contribution for it. Active development for DataHub has already started on `datahub` branch and will continue to live in there until it's finally merged to master and project is renamed to DataHub. 

Please check the `datahub` branch to get familar with DataHub.

Best,
DataHub team
