### ISSUE TITLE
simple doubt regarding db_type_id in POST http://localhost:9009/cfg/db

### ISSUE THREAD

**Issue by ashitabh** [linkedin/WhereHows#102]
where is db_type_id coming from ?

.MySQLIntegrityConstraintViolationException: Column 'db_type_id' cannot be null"

  {
      "db_id": 10001,
      "db_code": "TD",
      "description": "TERADATA VM",
      "cluster_size": 22,
      "associated_data_centers": 1,
      "replication_role": "MASTER",
      "uri": "Teradata://sample-td",
      "short_connection_string": "SAMPLE-TD"
    }

**Comment by SunZhaonan** [comment]
The db_type_id came from our internal legacy code. As it won't be used in any part, assign a default value will resolve this. e.g. `"db_type_id":0` . 
I'll also make a quick change of this table's DDL .

**Comment by ashitabh** [comment]
thanks , it's working now
