### ISSUE TITLE
WhereHows UI: The tree view of dataset on the left panel cannot be displayed

### ISSUE THREAD

**Issue by leopoda** [linkedin/WhereHows#103]
Hi, guys

I have setup the WhereHows on my local VM, and created the HDFS metadata ETL job successfully, but still have some problems. The tree view of dataset or flow on UI's left side panel doesn't display, it's always in the "Loading" status.

I have configured the wherehows.ui.tree.dataset.file & wherehows.ui.tree.flow.file in table wh_property, but the issue still repro.

And my question is: how are the files dataset.json and flow.json generated?

mysql> select * from wh_property;
+--------------------------------+------------------------------------------+--------------+------------+
| property_name                  | property_value                           | is_encrypted | group_name |
+--------------------------------+------------------------------------------+--------------+------------+
| wherehows.app_folder           | /tmp/wherehows                           | N            | NULL       |
| wherehows.db.driver            | com.mysql.jdbc.Driver                    | N            | NULL       |
| wherehows.db.jdbc.url          | jdbc:mysql://localhost/wherehows         | N            | NULL       |
| wherehows.db.password          | wherehows                                | N            | NULL       |
| wherehows.db.username          | wherehows                                | N            | NULL       |
| wherehows.ui.tree.dataset.file | /var/tmp/wherehows/resource/dataset.json | N            | NULL       |
| wherehows.ui.tree.flow.file    | /var/tmp/wherehows/resource/flow.json    | N            | NULL       |
+--------------------------------+------------------------------------------+--------------+------------+

Any help is highly appreciated.

thanks,
Jack

**Comment by SunZhaonan** [comment]
dataset.json and flow.json is generated after dataset metadata ETL jobs and execution metadata ETL jobs. If you have run any of these jobs, the json should be generated in the directory you specified.

So just configure the schedule table and run one of the HDFS metadata ETL job and see if dataset.json get generated.

**Comment by leopoda** [comment]
@SunZhaonan I am still confused on the dataset.json & flow.json. I am sure the HDFS metadata ETL executed successfully, and I can see the metadata on werehows UI, but the tree view cannot get displayed, because the dataset.josn is not generated.

I checked the log /var/tmp/wherehows/wherehows.log, I found some clue:

2016-04-05 23:09:04 INFO  HdfsMetadataEtl:141 - extract finished
2016-04-05 23:09:04 INFO  HdfsMetadataEtl:158 - hdfs metadata transform
2016-04-05 23:09:05 INFO  jython script : HdfsTransform:? -    1 (     5):    9 fields,    9 total fields(including nested) found in [data]@hdfs:///user/wherehows/data with source Hdfs
2016-04-05 23:09:05 INFO  HdfsMetadataEtl:168 - hdfs metadata load
2016-04-05 23:09:06 INFO  HdfsMetadataEtl:173 - hdfs metadata load finished
2016-04-05 23:09:06 INFO  Job Launcher:87 - whEtlId: 1145 now stop
2016-04-05 23:09:06 INFO  application:371 - ETL job jobtype:HADOOP_DATASET_METADATA_ETL	refId:1	refIdType:DB	whEtlJobId:1	whEtlExecId1145 finished
**2016-04-05 23:09:06 INFO  application:371 - Start build dataset tree**

Only "Start build dataset tree" is written into the log, no "Finish build dataset tree" message in the log. I searched the string "Start build dataset tree" in the all the source code files, but didn't find any code to log this INFO message.

Can you explain more detail on the process that how is the dataset.json generated? Or could you provided some script to initialize the wherehows DB after a new fresh install? Maybe I miss some steps when I setup the werehows on my local VM.

Looks forward to your feedback :)

**Comment by SunZhaonan** [comment]
Once a dataset metadata ETL job finished, the scheduler will trigger a build tree job. Code is here : 
https://github.com/linkedin/WhereHows/blob/master/backend-service/app/actors/TreeBuilderActor.java#L51.

You can't search that message because that message is dynamic generated.

And the logic of generating the tree is in jython code : https://github.com/linkedin/WhereHows/blob/master/metadata-etl/src/main/resources/jython/DatasetTreeBuilder.py

In your log, what things is after 'Start build dataset tree'. It just stopped?

**Comment by leopoda** [comment]
@SunZhaonan Thanks for your suggestion. Seems there is a bug in file DatasetTreeBuilder.py:

      query = "select distinct id, concat(SUBSTRING_INDEX(urn, ':///', 1), '/', SUBSTRING_INDEX(urn, ':///', -1)) p from dict_dataset order by urn"
      cur.execute(query)
      datasets = cur.fetchall()
      self.dataset_dict = dict()

The sql query is invalid, and throw below error message when executing:

[SQL] select distinct id, concat(SUBSTRING_INDEX(urn, ':///', 1), '/', SUBSTRING_INDEX(urn, ':///', -1)) p from dict_dataset order by urn

[Err] 3065 - Expression #1 of ORDER BY clause is not in SELECT list, references column 'wherehows.dict_dataset.urn' which is not in SELECT list; this is incompatible with DISTINCT

**Comment by SunZhaonan** [comment]
The query works for me on mysql version 5.6.16. Which version is your mysql?

From the log I think it need add another `urn` in the select result. Change the sql to :
select distinct id, concat(SUBSTRING_INDEX(urn, ':///', 1), '/', SUBSTRING_INDEX(urn, ':///', -1)) p **, urn** from dict_dataset order by urn

**Comment by leopoda** [comment]
The version of MySQL server is 5.7.11.

It's weird that the query complains such syntax error, maybe some settings of MySQL caused this error. Anyway, I removed the "order by urn" clause and re-compiled and deployed the package, and finally the tree view of dataset got displayed.

Thanks for the help!

**Comment by leopoda** [comment]
- [ ]
