### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by honghan123** [linkedin/WhereHows#1033]
Here is the error I got. Can someone help?

> Task :wherehows-dao:findbugsTest
Scanning archives (44 / 44)
2 analysis passes to perform
Pass 1: Analyzing classes (74 / 74) - 100% complete
Pass 2: Analyzing classes (8 / 8) - 100% complete
Done with analysisindbugsTest
FindBugs rule violations were found. See the report at: file:///home/ec2-user/wherehow/WhereHows/wherehows-dao/build/reports/findbugs/test.html

Missing header in: wherehows-dao/src/main/java/wherehows/models/table/AccessControlEntry.java

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':wherehows-dao:licenseMain'.
> License violations were found: /home/ec2-user/wherehow/WhereHows/wherehows-dao/src/main/java/wherehows/models/table/AccessControlEntry.java}

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED in 2m 4s
31 actionable tasks: 28 executed, 3 up-to-date

**Comment by alyiwang** [comment]
Thanks for reporting. We have fixed this in #1023
