### ISSUE TITLE
Where can I find lineage for flow

### ISSUE THREAD

**Issue by kiranclarivate** [linkedin/WhereHows#1039]
Hi ,
I am unable to see any lineage button in the flow screen.COuld you please help me to find it?

Thanks,
Kiran

![image](https://user-images.githubusercontent.com/29731425/37448397-359e1496-284c-11e8-8142-d1ce3dc7f984.png)

**Comment by kiranclarivate** [comment]
@mars-lan Kindly check this issue.Have you removed the lineage button from this screen.In older version of wherehows..lineage button was available on this screen as well.

Thanks,
Kiran

**Comment by keremsahin1** [comment]
Dear issue owner,

Thanks for your interest in WhereHows. We have recently announced DataHub which is the rebranding of WhereHows. LinkedIn improved the architecture of WhereHows and rebranded WhereHows into DataHub and replaced its metadata infrastructure in this direction. DataHub is a more advanced and improved metadata management product compared to WhereHows. 

Unfortunately, we have to stop supporting WhereHows to better focus on DataHub and offer more help to DataHub users. Therefore, we will drop all issues related to WhereHows and will not accept any contribution for it. Active development for DataHub has already started on `datahub` branch and will continue to live in there until it's finally merged to master and project is renamed to DataHub. 

Please check the `datahub` branch to get familar with DataHub.

Best,
DataHub team
