### ISSUE TITLE
why I cannot use ETL Job Api?

### ISSUE THREAD

**Issue by chenhuizi** [linkedin/WhereHows#1051]
All the following APIs:
ETL Job GET API
ETL Job New Job POST API
ETL Job Control PUT API
ETL Job Schedule Update PUT API
ETL Job Property Update PUT API

the response is Action not found

**Comment by alyiwang** [comment]
@chenhuizi  thanks for reporting! Actually the backend APIs have been deprecated and not recommended to use. We haven't test those for a while. For config, might be better just insert/edit at DB

**Comment by keremsahin1** [comment]
Dear issue owner,

Thanks for your interest in WhereHows. We have recently announced DataHub which is the rebranding of WhereHows. LinkedIn improved the architecture of WhereHows and rebranded WhereHows into DataHub and replaced its metadata infrastructure in this direction. DataHub is a more advanced and improved metadata management product compared to WhereHows. 

Unfortunately, we have to stop supporting WhereHows to better focus on DataHub and offer more help to DataHub users. Therefore, we will drop all issues related to WhereHows and will not accept any contribution for it. Active development for DataHub has already started on `datahub` branch and will continue to live in there until it's finally merged to master and project is renamed to DataHub. 

Please check the `datahub` branch to get familar with DataHub.

Best,
DataHub team
