### ISSUE TITLE
Error running build.sh in dockerr

### ISSUE THREAD

**Issue by cpalomaressbd** [linkedin/WhereHows#1053]
I got this error:

> Task :wherehows-etl:compileJava
/WhereHows/wherehows-etl/src/main/java/metadata/etl/sqlParser/InsertStmt.java:16: error: package gudusoft.gsqlparser does not exist
import gudusoft.gsqlparser.TBaseType;

I couldnt execute all the build.sh

**Comment by alisaraa** [comment]
Oh, you need the gsp in your extralibs. Do you have it? https://github.com/linkedin/WhereHows/tree/master/wherehows-etl/extralibs

**Comment by joaolcorreia** [comment]
Hi, I'm trying to build the docker but it is producing this error (see below). Any ideas on how to fix this? Thanks!

/Users/joao/WhereHows-master/wherehows-etl/src/main/java/metadata/etl/sqlParser/UpdateStmt.java:36: error: cannot find symbol
    public UpdateStmt(TUpdateSqlStatement stmt) throws NoSqlTypeException {
                      ^
  symbol:   class TUpdateSqlStatement
  location: class UpdateStmt
/Users/joao/WhereHows-master/wherehows-etl/src/main/java/metadata/etl/sqlParser/UpdateStmt.java:82: error: cannot find symbol
    private String checkAlias(TTableList tablelist, String name) {
                              ^
  symbol:   class TTableList
  location: class UpdateStmt
50 errors


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':wherehows-etl:compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED in 3s
13 actionable tasks: 2 executed, 11 up-to-date

**Comment by joaolcorreia** [comment]
For future reference I installed the gsp.jar in the wherehow-etl/extralibs and it build fine!

**Comment by JoaoVasques** [comment]
Shouldn't the build script take care of that? Doing a patch for it

**Comment by jywadhwani** [comment]
This is similar to https://github.com/linkedin/WhereHows/issues/596. Closing the issue.
