### ISSUE TITLE
Can not run ElasticSearchIndex.py

### ISSUE THREAD

**Issue by honghan123** [linkedin/WhereHows#1056]
tried to run jython ElasticSearchIndex.py, got following errors

WhereHows/wherehows-etl/build/resources/main/jython/ElasticSearchIndex.py", line 18, in <module>

import sys, json
File "json/__init__.py", line 108, in <module>
File "json/decoder.py", line 24, in <module>
File "json/decoder.py", line 18, in _floatconstants
LookupError: no codec search functions registered: can't find ecoding 'hex'

I have tried both jython 2.7.0 and 2.7.1

any help?

**Comment by Ash-Mishra** [comment]
Why don't you just run the job for elasticsearch. There is a job template available in jobs/template for elasticsearch

**Comment by keremsahin1** [comment]
Dear issue owner,

Thanks for your interest in WhereHows. We have recently announced DataHub which is the rebranding of WhereHows. LinkedIn improved the architecture of WhereHows and rebranded WhereHows into DataHub and replaced its metadata infrastructure in this direction. DataHub is a more advanced and improved metadata management product compared to WhereHows. 

Unfortunately, we have to stop supporting WhereHows to better focus on DataHub and offer more help to DataHub users. Therefore, we will drop all issues related to WhereHows and will not accept any contribution for it. Active development for DataHub has already started on `datahub` branch and will continue to live in there until it's finally merged to master and project is renamed to DataHub. 

Please check the `datahub` branch to get familar with DataHub.

Best,
DataHub team
