### ISSUE TITLE
Force an ETL Job to Run

### ISSUE THREAD

**Issue by carnalim** [linkedin/WhereHows#106]
Do you guys have any API or way to force a job to run? The only thing I can see is to update the cron_expr but that may cause the job to kick off to many times for testing. I just want to force it to run independently of the cron job.

**Comment by SunZhaonan** [comment]
Each job can run independently. If you want to run one job to test, follow the instruction here: https://github.com/linkedin/WhereHows/wiki/Coding-Guidelines#testing

If you want to trigger though the backend service, you can manually set the `next_run` in `wh_etl_job` table to a small value, disable all other jobs and only enable this one, then restart the service, it will only run this job.
