### ISSUE TITLE
Parquet Support

### ISSUE THREAD

**Issue by carnalim** [linkedin/WhereHows#107]
I've noticed in the HDFS crawler you have standard text, avro, orc, but I did not see anything with Parquet. Is there any plans to include the ability to scan parquet? Also are you deriving the schema from the raw_metadata file? If this is true why in avro/parquet not derive the schema from the embedded schema in the file.

**Comment by SunZhaonan** [comment]
Agree, parquet is definitely a wide used format, but as linkedin doesn't have requirement for that yet, we haven't put it in our plan. But it won't be a very big task and welcome pull request :)

The schema is actually derived from embedded schema. The raw_metadata file is just an intermediate file for the ease of ETL.

**Comment by ericsun2** [comment]
@carnalim can you upload a sample Parquet with complex nested structure in it. I want to use that as unit test to make sure we cover your use case better.

**Comment by mars-lan** [comment]
Added in https://github.com/linkedin/WhereHows/pull/483
