### ISSUE TITLE
Build failed ...

### ISSUE THREAD

**Issue by joaolcorreia** [linkedin/WhereHows#1076]
After a failed attempt to run WhereHows with docker Im trying a real machine running Ubuntu LTS.
While compiling Im getting the build failed with the following tests:

Failed tests
     * JobsUtilTest. testGetEnabledJobs
     * JobsUtilTest. testGetEnabledJobsByType
     * JobsUtilTest. testGetScheduledJobs

Any ideas?
Joao

**Comment by mtHuberty** [comment]
Having the exact same issue. Haven't tried the docker yet, went straight to an Ubuntu EC2 instance, but I'm having those same failing unit tests pop up. Did anyone ever get back to you on this?

**Comment by keremsahin1** [comment]
Dear issue owner,

Thanks for your interest in WhereHows. We have recently announced DataHub which is the rebranding of WhereHows. LinkedIn improved the architecture of WhereHows and rebranded WhereHows into DataHub and replaced its metadata infrastructure in this direction. DataHub is a more advanced and improved metadata management product compared to WhereHows. 

Unfortunately, we have to stop supporting WhereHows to better focus on DataHub and offer more help to DataHub users. Therefore, we will drop all issues related to WhereHows and will not accept any contribution for it. Active development for DataHub has already started on `datahub` branch and will continue to live in there until it's finally merged to master and project is renamed to DataHub. 

Please check the `datahub` branch to get familar with DataHub.

Best,
DataHub team
