### ISSUE TITLE
ORACLE_METADATA_ETL JOB执行成功后dataset.json无更新

### ISSUE THREAD

**Issue by lichaoie** [linkedin/WhereHows#1088]
如题，ORACLE_METADATA_ETL JOB已成功执行，但是dataset.json无更新。是配置原因么 ？DATASET_TREE_BUILDER.job放在etl.jobs.dir配置的目录下，但好像不会执行？1.0版本

**Comment by xkcoding** [comment]
@lichaoie 请问您现在已经成功了吗？

**Comment by keremsahin1** [comment]
Dear issue owner,

Thanks for your interest in WhereHows. We have recently announced DataHub which is the rebranding of WhereHows. LinkedIn improved the architecture of WhereHows and rebranded WhereHows into DataHub and replaced its metadata infrastructure in this direction. DataHub is a more advanced and improved metadata management product compared to WhereHows. 

Unfortunately, we have to stop supporting WhereHows to better focus on DataHub and offer more help to DataHub users. Therefore, we will drop all issues related to WhereHows and will not accept any contribution for it. Active development for DataHub has already started on `datahub` branch and will continue to live in there until it's finally merged to master and project is renamed to DataHub. 

Please check the `datahub` branch to get familar with DataHub.

Best,
DataHub team
