### ISSUE TITLE
How to start backend? (failing)

### ISSUE THREAD

**Issue by ziveo** [linkedin/WhereHows#1098]
I cloned repo https://github.com/linkedin/WhereHows.git but can not start backend.

This is a script (runBackend):

    #!/bin/bash
    set -a
    source application.env
    set +a
    
    export JAVA_OPTS="-Xms512m -Xmx2048m -Dhttp.port=9001"
    
    build/stage/wherehows-backend/bin/playBinary

Trying to run:

    cd WhereHows/wherehows-backend
    ./runBackend

error:

    ./runBackend: line 8: build/stage/wherehows-backend/bin/playBinary: No such file or directory

This is a file (application.env) whre apperently line 8 error is comming from (WHZ_DB_DRIVER="com.mysql.jdbc.Driver"):

    # Directory containing kerberos config files
    WHZ_KRB5_DIR="/dir/to/krb5conf"
    
    # Secret Key
    WHZ_SECRET="change_me"
    
    # Database Connection
    WHZ_DB_DRIVER="com.mysql.jdbc.Driver"
    WHZ_DB_USERNAME="wherehows"
    WHZ_DB_PASSWORD="wherehows"
    # Fully qualified jdbc url
    WHZ_DB_URL="jdbc:mysql://localhost/wherehows"
    
    #mysql setup
    WHZ_DB_DSCLASSNAME="com.mysql.jdbc.jdbc2.optional.MysqlDataSource"
    WHZ_DB_DIALECT="org.hibernate.dialect.MySQLInnoDBDialect"
    
    # Directory containing ETL job files
    WHZ_ETL_JOBS_DIR="/var/tmp/jobs"
    
    # Temp directory for ETL job
    WHZ_ETL_TEMP_DIR="/var/tmp/wherehows"

How to fix this?

thanks.

**Comment by syknar** [comment]
sounds like you may have skipped building the distribution, it's kind of glossed over in the docs. just cd to your backend directory and run ../gradlew dist

cd WhereHows/wherehows-backend
../gradlew dist
