### ISSUE TITLE
Discrepancy in local_test_properties.template

### ISSUE THREAD

**Issue by carnalim** [linkedin/WhereHows#110]
In the following properties [https://github.com/linkedin/WhereHows/blob/master/metadata-etl/src/main/resources/local_test.properties.template](url) There are few fields that are not in the HDFS Dataset [https://github.com/LinkedIn/Wherehows/wiki/Hdfs-Dataset](url) or in the VM Table like:

hdfs.remote.working.dir=
hdfs.schema_location=

Are those deprecated?

**Comment by SunZhaonan** [comment]
Yes, these two are deprecated. `hdfs.remote.working.dir` is not using here. `hdfs.schema_location` is a path on hdfs that we planned to store a copy of result, but haven't implemented yet. Leave them empty is fine.
