### ISSUE TITLE
Problem when trying from root: gradle build   (wherehows-web:emberBuild)

### ISSUE THREAD

**Issue by ziveo** [linkedin/WhereHows#1100]
These are commands that I ran and have problems with:

```
➜  WhereHows git:(master) ✗ gradle build

> Task :wherehows-data-model:generateAvroJava 
[WARNING] Avro: Invalid default for field state: null not a ["string"]
[WARNING] Avro: Invalid default for field state: null not a [{"type":"string","avro.java.string":"String"}]

> Task :wherehows-web:bowerInstall 
bower bootstrap       extra-resolution Unnecessary resolution: bootstrap#3.3.7
bower jquery-ui       extra-resolution Unnecessary resolution: jquery-ui#^1.12.1

> Task :wherehows-web:emberBuild 
DEPRECATION: An addon is trying to access project.nodeModulesPath. This is not a reliable way to discover npm modules. Instead, consider doing: require("resolve").sync(something, { basedir: project.root }). Accessed from:   new NPMDependencyVersionChecker (/WhereHows/wherehows-web/node_modules/ember-cli-medium-editor/node_modules/ember-cli-version-checker/src/npm-dependency-version-checker.js:11:33)
<=======------> 60% EXECUTING [3m 1s]
> :wherehows-web:emberBuild

```

**Comment by keremsahin1** [comment]
Dear issue owner,

Thanks for your interest in WhereHows. We have recently announced DataHub which is the rebranding of WhereHows. LinkedIn improved the architecture of WhereHows and rebranded WhereHows into DataHub and replaced its metadata infrastructure in this direction. DataHub is a more advanced and improved metadata management product compared to WhereHows. 

Unfortunately, we have to stop supporting WhereHows to better focus on DataHub and offer more help to DataHub users. Therefore, we will drop all issues related to WhereHows and will not accept any contribution for it. Active development for DataHub has already started on `datahub` branch and will continue to live in there until it's finally merged to master and project is renamed to DataHub. 

Please check the `datahub` branch to get familar with DataHub.

Best,
DataHub team
