### ISSUE TITLE
Flows not showing in UI

### ISSUE THREAD

**Issue by draganavb** [linkedin/WhereHows#1106]
Hi,
UI is launching (via tunnel, on docker), however none of the flows are not showing. Data is populated in db, table: flow. There are no errors when jobs are executing.
There is an error at the bottom of the Browser: "An error occurred getting entities
SyntaxError: Unexpected token < in JSON at position 2". Scrip finder and Schema history just show 0 records.
Thanks a bunch!

**Comment by xkcoding** [comment]
@draganavb you can use the tag v1.0.0 can solve this error... 

i just found this yesterday. maybe the programmer is still code in master branch, so ....

**Comment by vikassharma-v** [comment]
@ankurgadgilwar For the front-end UI/API to pick up any data, the data should to be present in Elasticsearch.
First, set up the Elasticsearch ETL job, it will fetch data from DB and populate it to ElasticSearch.
I would suggest checking whether the data is getting populated in wherehows DB tables thought your Hive ETL.
If DB is getting populated then check whether Elasticsearch is getting populated.
If above steps work then you should be able to see data on front-end UI/API.

**Comment by ankurgadgilwar** [comment]
@vikassharma-v I tried the above method, however, the backend is only scheduling the previously run HIVE_METADATA_ETL job even though I have moved it from the location where the backend picks up the jobs from. And now, I am not able to run the frontend. I am getting the below issue `'/WhereHows/wherehows-web/build/nodejs/node-v7.8.0-linux-x64/bin/node'' finished with non-zero exit value 1`. I don't see the ElasticSearch job scheduled in the database.

**Comment by keremsahin1** [comment]
Dear issue owner,

Thanks for your interest in WhereHows. We have recently announced DataHub which is the rebranding of WhereHows. LinkedIn improved the architecture of WhereHows and rebranded WhereHows into DataHub and replaced its metadata infrastructure in this direction. DataHub is a more advanced and improved metadata management product compared to WhereHows. 

Unfortunately, we have to stop supporting WhereHows to better focus on DataHub and offer more help to DataHub users. Therefore, we will drop all issues related to WhereHows and will not accept any contribution for it. Active development for DataHub has already started on `datahub` branch and will continue to live in there until it's finally merged to master and project is renamed to DataHub. 

Please check the `datahub` branch to get familar with DataHub.

Best,
DataHub team
