### ISSUE TITLE
LDAP configuration help

### ISSUE THREAD

**Issue by spobo1** [linkedin/WhereHows#1112]
Hi

I am struggling to get the wherehows frontend authentication to work against my LDAP server. I wonder if anyone would be so kind as to review my config?

First proof that LDAP is able to authenticate the user using command line utilities on the same machine that the wherehows docker image is running:

>> ldapwhoami -vvv -h localhost -p 389 -D uid=george,ou=People,dc=example,dc=com -x -w <password ommitted>
ldap_initialize( ldap://localhost:389 )
dn:uid=george,ou=People,dc=example,dc=com
Result: Success (0)
>> 

Next my .env LDAP related settings:

# LDAP
WHZ_LDAP_URL=ldap://localhost:389
WHZ_LDAP_PRINCIPAL_DOMAIN=@example.com
WHZ_LDAP_SEARCH_BASE=ou=People,dc=example,dc=com

And the stack trace when I login to the front end with the ID and password that I have verified against LDAP:

wherehows-frontend_1       | 2018-04-22 02:59:16 INFO  application:85 - Creating DAO factory: wherehows.dao.DaoFactory
wherehows-frontend_1       | 2018-04-22 02:59:16 ERROR application:183 - Piwik site ID must be an integer
wherehows-frontend_1       | 2018-04-22 02:59:40 ERROR application:96 - Ldap server connection error!
wherehows-frontend_1       | javax.naming.CommunicationException: localhost:389
wherehows-frontend_1       | 	at com.sun.jndi.ldap.Connection.<init>(Connection.java:226) ~[na:1.8.0_162]
wherehows-frontend_1       | 	at com.sun.jndi.ldap.LdapClient.<init>(LdapClient.java:137) ~[na:1.8.0_162]
wherehows-frontend_1       | 	at com.sun.jndi.ldap.LdapClient.getInstance(LdapClient.java:1615) ~[na:1.8.0_162]
wherehows-frontend_1       | 	at com.sun.jndi.ldap.LdapCtx.connect(LdapCtx.java:2749) ~[na:1.8.0_162]
wherehows-frontend_1       | 	at com.sun.jndi.ldap.LdapCtx.<init>(LdapCtx.java:319) ~[na:1.8.0_162]
wherehows-frontend_1       | 	at com.sun.jndi.ldap.LdapCtxFactory.getUsingURL(LdapCtxFactory.java:192) ~[na:1.8.0_162]
wherehows-frontend_1       | 	at com.sun.jndi.ldap.LdapCtxFactory.getUsingURLs(LdapCtxFactory.java:210) ~[na:1.8.0_162]
wherehows-frontend_1       | 	at com.sun.jndi.ldap.LdapCtxFactory.getLdapCtxInstance(LdapCtxFactory.java:153) ~[na:1.8.0_162]
wherehows-frontend_1       | 	at com.sun.jndi.ldap.LdapCtxFactory.getInitialContext(LdapCtxFactory.java:83) ~[na:1.8.0_162]
wherehows-frontend_1       | 	at javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:684) ~[na:1.8.0_162]
wherehows-frontend_1       | 	at javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:313) ~[na:1.8.0_162]
wherehows-frontend_1       | 	at javax.naming.InitialContext.init(InitialContext.java:244) ~[na:1.8.0_162]

**Comment by Qsimple** [comment]
Have you got an error with this config file??

**Comment by keremsahin1** [comment]
Dear issue owner,

Thanks for your interest in WhereHows. We have recently announced DataHub which is the rebranding of WhereHows. LinkedIn improved the architecture of WhereHows and rebranded WhereHows into DataHub and replaced its metadata infrastructure in this direction. DataHub is a more advanced and improved metadata management product compared to WhereHows. 

Unfortunately, we have to stop supporting WhereHows to better focus on DataHub and offer more help to DataHub users. Therefore, we will drop all issues related to WhereHows and will not accept any contribution for it. Active development for DataHub has already started on `datahub` branch and will continue to live in there until it's finally merged to master and project is renamed to DataHub. 

Please check the `datahub` branch to get familar with DataHub.

Best,
DataHub team
