### ISSUE TITLE
What is the difference between stg_dict_dataset and dict_dataset

### ISSUE THREAD

**Issue by chenhuizi** [linkedin/WhereHows#1125]
What is the difference between stg_dict_dataset and dict_dataset？

**Comment by mtHuberty** [comment]
From what my team has guessed, stg_ tables are used to hold (or stage) your data BEFORE you run any transform scripts on it, and the regular tables hold the results of any tranformations. All I know for sure is that I can truncate/delete the stg tables and it has no effect (that I can tell) on the frontend displaying my data. I even have some scripts that insert some missing data (comments) into a few tables, and I've found I can safely ignore the stg_ tables and still get my data to save and show up in the frontend web client.

**Comment by ankurgadgilwar** [comment]
Can you just put a snapshot of how the data looks on the UI. I am just able to see he schema in my case

**Comment by keremsahin1** [comment]
Dear issue owner,

Thanks for your interest in WhereHows. We have recently announced DataHub which is the rebranding of WhereHows. LinkedIn improved the architecture of WhereHows and rebranded WhereHows into DataHub and replaced its metadata infrastructure in this direction. DataHub is a more advanced and improved metadata management product compared to WhereHows. 

Unfortunately, we have to stop supporting WhereHows to better focus on DataHub and offer more help to DataHub users. Therefore, we will drop all issues related to WhereHows and will not accept any contribution for it. Active development for DataHub has already started on `datahub` branch and will continue to live in there until it's finally merged to master and project is renamed to DataHub. 

Please check the `datahub` branch to get familar with DataHub.

Best,
DataHub team
