### ISSUE TITLE
sample data doesn't work at all

### ISSUE THREAD

**Issue by richardxin** [linkedin/WhereHows#1134]
None of the sample data works, I took a look at https://github.com/linkedin/WhereHows/blob/master/wherehows-frontend/app/dao/DatasetsDAO.java#L850

but the schedule is hard-coded in
https://github.com/linkedin/WhereHows/blob/master/wherehows-frontend/app/utils/SampleData.java

Did I miss anything? sampledata could have any schema, I dont understand the logic here? 
What are these field  names? https://github.com/linkedin/WhereHows/blob/master/wherehows-frontend/app/utils/SampleData.java#L26-L39, one of Linkedin internal tables?

**Comment by keremsahin1** [comment]
Dear issue owner,

Thanks for your interest in WhereHows. We have recently announced DataHub which is the rebranding of WhereHows. LinkedIn improved the architecture of WhereHows and rebranded WhereHows into DataHub and replaced its metadata infrastructure in this direction. DataHub is a more advanced and improved metadata management product compared to WhereHows. 

Unfortunately, we have to stop supporting WhereHows to better focus on DataHub and offer more help to DataHub users. Therefore, we will drop all issues related to WhereHows and will not accept any contribution for it. Active development for DataHub has already started on `datahub` branch and will continue to live in there until it's finally merged to master and project is renamed to DataHub. 

Please check the `datahub` branch to get familar with DataHub.

Best,
DataHub team
