### ISSUE TITLE
Add admin pages for WhereHows

### ISSUE THREAD

**Issue by SunZhaonan** [linkedin/WhereHows#114]
Currently, WhereHows can only config through API. So if I want to change one job's configuration or want to add a new job, I have run the service and use 'curl' call from command line follow the [steps](https://github.com/linkedin/WhereHows/wiki/Set-Up-New-Metadata-ETL-Jobs#step-by-step-instructions). This is a pain for a admin who need to manage and operate the WhereHows backend jobs. What I usually do is use a database tools(Aqua data studio) which have UI so I can open a table and directly change the value there. But absolutely this is not a standard way.

We should have several 'admin' pages in frontend that could configure WhereHows backend job. User with 'admin' permission login can enter the admin pages. 
These admin pages are all one to one map to database configuration tables
They contains at least these pages : 
1. Scheduled jobs --> wh_etl_job 
2. job configurations --> wh_etl_job_property
3. all applications configurations --> cfg_application
4. all databases configurations--> cfg_database
5. wherehows property --> wh_property
6. job execution history (read only) --> wh_etl_job_execution

In lineage ETL, there are several configuration table also better need to have a frontend:
1. filename_pattern
2. dataset_partition_layout_pattern
3. log_lineage_pattern
4. log_reference_job_id_pattern

**Comment by joezxh** [comment]
什么时候完成哦，正在使用wherehows.

**Comment by planckiii** [comment]
There are some news in thath issue ?
