### ISSUE TITLE
Teradata table comments are not being extracted (Version 1.0.0)

### ISSUE THREAD

**Issue by mtHuberty** [linkedin/WhereHows#1141]
Hey there!

I am currently using the docker build from the version tagged 1.0.0.
I am using the TERADATA_METADATA_ETL.job file to collect metadata from our Teradata system. I  have it configured properly to connect to and pull from our Teradata instance, and am successfully getting metadata from TD stored in my WhereHows mysql database, and I can view it in the WhereHows frontend. However, the job is NOT successfully collecting the comments from each table that it parses. 

Is this a bug with the Teradata crawler? I would greatly appreciate it if someone could point me toward the file that contains the code that parses the Teradata information so that I can try to tweak it to collect the comments as well. I noticed in version 1.1.0, the jython jobs are listed in the .job file, but in the 1.0.0 version, the location of those scripts is probably hard coded elsewhere and I'm having trouble locating it.

**Comment by keremsahin1** [comment]
Dear issue owner,

Thanks for your interest in WhereHows. We have recently announced DataHub which is the rebranding of WhereHows. LinkedIn improved the architecture of WhereHows and rebranded WhereHows into DataHub and replaced its metadata infrastructure in this direction. DataHub is a more advanced and improved metadata management product compared to WhereHows. 

Unfortunately, we have to stop supporting WhereHows to better focus on DataHub and offer more help to DataHub users. Therefore, we will drop all issues related to WhereHows and will not accept any contribution for it. Active development for DataHub has already started on `datahub` branch and will continue to live in there until it's finally merged to master and project is renamed to DataHub. 

Please check the `datahub` branch to get familar with DataHub.

Best,
DataHub team
