### ISSUE TITLE
An error occurred getting entities in web UI Datasets tab

### ISSUE THREAD

**Issue by rvucera** [linkedin/WhereHows#1161]
After installing Linkedin's `WhereHows` following the github docs (https://github.com/linkedin/WhereHows/blob/master/wherehows-docs/getting-started.md#getting-started), logging into the web UI, and navigating to the Datasets tab, it complains

    An error occurred getting entities
    
    SyntaxError: JSON.parse: unexpected character at line 3 column 1 of the JSON data

[![enter image description here][1]][1]

Looking at the developer console in the web browser, can see the error outputs

    SyntaxError: JSON.parse: unexpected character at line 3 column 1 of the JSON data[Learn More]  vendor-01c52695e9f268de5628f7bec75d6bb1.js:65255:14
    	tryCatcher http://localhost:9001/assets/assets/vendor-01c52695e9f268de5628f7bec75d6bb1.js:65255:14
    	invokeCallback http://localhost:9001/assets/assets/vendor-01c52695e9f268de5628f7bec75d6bb1.js:65437:15
    	publish http://localhost:9001/assets/assets/vendor-01c52695e9f268de5628f7bec75d6bb1.js:65422:9
    	Queue</Queue.prototype.invoke http://localhost:9001/assets/assets/vendor-01c52695e9f268de5628f7bec75d6bb1.js:27963:17
    	Queue</Queue.prototype.flush http://localhost:9001/assets/assets/vendor-01c52695e9f268de5628f7bec75d6bb1.js:27848:25
    	DeferredActionQueues</DeferredActionQueues.prototype.flush http://localhost:9001/assets/assets/vendor-01c52695e9f268de5628f7bec75d6bb1.js:28035:25
    	Backburner</Backburner.prototype.end http://localhost:9001/assets/assets/vendor-01c52695e9f268de5628f7bec75d6bb1.js:28169:26
    	Backburner/this._boundAutorunEnd http://localhost:9001/assets/assets/vendor-01c52695e9f268de5628f7bec75d6bb1.js:28131:17
    Unhandled promise rejection SyntaxError: JSON.parse: unexpected character at line 3 column 1 of the JSON data
    Stack trace:
    tryCatcher@http://localhost:9001/assets/assets/vendor-01c52695e9f268de5628f7bec75d6bb1.js:65255:14
    invokeCallback@http://localhost:9001/assets/assets/vendor-01c52695e9f268de5628f7bec75d6bb1.js:65437:15
    publish@http://localhost:9001/assets/assets/vendor-01c52695e9f268de5628f7bec75d6bb1.js:65422:9
    Queue</Queue.prototype.invoke@http://localhost:9001/assets/assets/vendor-01c52695e9f268de5628f7bec75d6bb1.js:27963:17
    Queue</Queue.prototype.flush@http://localhost:9001/assets/assets/vendor-01c52695e9f268de5628f7bec75d6bb1.js:27848:25
    DeferredActionQueues</DeferredActionQueues.prototype.flush@http://localhost:9001/assets/assets/vendor-01c52695e9f268de5628f7bec75d6bb1.js:28035:25
    Backburner</Backburner.prototype.end@http://localhost:9001/assets/assets/vendor-01c52695e9f268de5628f7bec75d6bb1.js:28169:26
    Backburner/this._boundAutorunEnd@http://localhost:9001/assets/assets/vendor-01c52695e9f268de5628f7bec75d6bb1.js:28131:17

Does anyone know what this error means and where to look to investigate further (first time working with `wherehows` and the given output on its own it not very helpful to my uninitiated self)?

** Note my configuration variables for the Play frontend (https://github.com/linkedin/WhereHows/blob/master/wherehows-docs/getting-started.md#frontend-setup) look like

    export WHZ_DB_USERNAME="wherehows"
    export WHZ_DB_PASSWORD="wherehows"
    export WHZ_DB_URL="jdbc:mysql://localhost/wherehows"
    
    export WHZ_ES_DATASET_URL="localhost:9200/wherehows"
    export WHZ_ES_METRIC_URL="localhost:9200/_nodes/stats" (honestly don't know if this is correct (don't use elasticsearch much))
    export WHZ_ES_FLOW_URL="localhost:9200/wherehows/flows_jobs"
    
    export YOUR_HDFS_BROWSER_LINK="http://node004.myco.local:8888/filebrowser/#"
    
    export WHZ_LDAP_URL="ldap://co.myco.local:389"
    export WHZ_LDAP_PRINCIPAL_DOMAIN="@co.local"
    export WHZ_LDAP_SEARCH_BASE="ou=mapr access,dc=co,dc=local"

  [1]: https://i.stack.imgur.com/gSzhC.png

**Comment by rvucera** [comment]
Looking at this github issue seems to dedscribe something similar recent problem (around May 1, 2018) (https://github.com/linkedin/WhereHows/issues/1131#issuecomment-385882867). The response is in chinese, but using google translate it reads:

> The latest code has a dao method did not write SQL, throw an exception directly, may be the author has not finished, you can try to use the 1.0.0 this tag, I tried this is no problem

So checking out the commit with tag v1.0.0

    git checkout tags/v1.0.0
Adding redoing the parts of the installation that needed redoing (eg. adding the extralibs, setting the frontend configuration variables, starting the front- and backends), I see that error message no longer appears.

**Comment by lg985** [comment]
![image](https://user-images.githubusercontent.com/39213065/44894781-1eaecc00-ad24-11e8-914b-6b57c0304fab.png)
I use the tag v1.0.0 , but it alerts error as above when build it.
