### ISSUE TITLE
Issue with Docker on Windows

### ISSUE THREAD

**Issue by Churchill59** [linkedin/WhereHows#1209]
Hello,

I do not understand how to make the Docker run on WIndows. The .sh does not run (I do not think I should install cygwin)

Should I build a Linux VM?
Should I use the Linux one in Hyper V?

Thank you

**Comment by mtHuberty** [comment]
Did you install [docker for windows?](https://docs.docker.com/docker-for-windows/) I believe docker only runs on Linux, so I assume that download would come with a VM of sorts. Even docker on mac uses "docker-machine" which is basically a linux VM.

**Comment by Churchill59** [comment]
Hello, Thank you for your feedback. Yes I did install Docker for Windows:
![image](https://user-images.githubusercontent.com/22095760/41590858-5ee51374-73b8-11e8-9163-ff787a1f0571.png)

I can switch on Windows or Linux containers. But I do not know where I can run the command line to build the Docker itself.

**Comment by keremsahin1** [comment]
Dear issue owner,

Thanks for your interest in WhereHows. We have recently announced DataHub which is the rebranding of WhereHows. LinkedIn improved the architecture of WhereHows and rebranded WhereHows into DataHub and replaced its metadata infrastructure in this direction. DataHub is a more advanced and improved metadata management product compared to WhereHows. 

Unfortunately, we have to stop supporting WhereHows to better focus on DataHub and offer more help to DataHub users. Therefore, we will drop all issues related to WhereHows and will not accept any contribution for it. Active development for DataHub has already started on `datahub` branch and will continue to live in there until it's finally merged to master and project is renamed to DataHub. 

Please check the `datahub` branch to get familar with DataHub.

Best,
DataHub team
