### ISSUE TITLE
cfg_object_name_map table schema is missing in data-model/DDL scripts

### ISSUE THREAD

**Issue by aig** [linkedin/WhereHows#122]
cfg_object_name_map table schema is missing in data-model/DDL scripts, but used in web/app/dao/LineageDAO.java

**Comment by ericsun2** [comment]
Will be appended soon.

**Comment by ericsun2** [comment]
cfg_object_name_map is used to 
- map View to its Original Table
- map Replica to its Original Dataset
- map Alias to its Original Dataset

DDL has been fixed.
