### ISSUE TITLE
Not Able to insert DataSet using Backend API

### ISSUE THREAD

**Issue by vikassharma-v** [linkedin/WhereHows#1237]
Hi,
I am trying to insert Dataset using Backend API (POST: {wherehows-backend-url}/dataset/).
The API returns a success but in logs, it throws an error saying "Column count doesn't match value count at row 1".
I am trying to integrate with Wherehows using backend APIs.
Please help.
Thanks

**Comment by mtHuberty** [comment]
I don't think the backend API is being supported anymore. =(
[#1051](https://github.com/linkedin/WhereHows/issues/1051)

**Comment by keremsahin1** [comment]
Dear issue owner,

Thanks for your interest in WhereHows. We have recently announced DataHub which is the rebranding of WhereHows. LinkedIn improved the architecture of WhereHows and rebranded WhereHows into DataHub and replaced its metadata infrastructure in this direction. DataHub is a more advanced and improved metadata management product compared to WhereHows. 

Unfortunately, we have to stop supporting WhereHows to better focus on DataHub and offer more help to DataHub users. Therefore, we will drop all issues related to WhereHows and will not accept any contribution for it. Active development for DataHub has already started on `datahub` branch and will continue to live in there until it's finally merged to master and project is renamed to DataHub. 

Please check the `datahub` branch to get familar with DataHub.

Best,
DataHub team
