### ISSUE TITLE
oracle lib link has changed 

### ISSUE THREAD

**Issue by richthofen** [linkedin/WhereHows#1242]
https://github.com/linkedin/WhereHows/tree/master/wherehows-etl/extralibs

i found the jar here:
http://www.oracle.com/technetwork/database/features/jdbc/jdbc-drivers-12c-download-1958347.html

**Comment by mtHuberty** [comment]
I also had an issue with my Oracle jobs failing. 

When using Wherehows with Docker, I also had to alter my Dockerfile at `Wherehows/wherehows-docker/wherehows-backend/Dockerfile` to include some extra apt-gets, ENV declarations and some folder COPYing. I'll just post the whole Dockerfile, though I don't completely understand why the additions help:
```
FROM openjdk:8

#(I added the libaio imports, and the jython but that was for something separate)
RUN apt-get update && \
    apt-get install -y wget && \
	apt-get install -y libaio1 && \
	apt-get install -y libaio-dev \
	apt-get install -y jython

# Install dockerize
ENV DOCKERIZE_VERSION v0.5.0
RUN wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz

# (I added these steps, found from a StackOverflow post when debugging my Oracle job failing)
COPY lib/ /app/lib/
RUN unzip -qq /app/lib/instantclient-basic-linux.x64-12.2.0.1.0.zip \
    -d /usr/local/lib
RUN unzip -qq /app/lib/instantclient-sdk-linux.x64-12.2.0.1.0.zip \
    -d /usr/local/lib
RUN ln -s /usr/local/lib/instantclient_12_2/libclntsh.so.12.2 \
    /usr/local/lib/instantclient_12_2/libclntsh.so


# Setup app environment
ADD tmp/wherehows-backend /application
WORKDIR /application
RUN mkdir -p logs/etl
ENV WHZ_ETL_JOBS_DIR=/application/jobs
ENV WHZ_ETL_TEMP_DIR=/application/logs/etl

# (I added the following ENV's)
ENV ORACLE_HOME /usr/local/lib/instantclient_12_2
ENV LD_LIBRARY_PATH /usr/local/lib/instantclient_12_2
ENV CLASSPATH /application/lib/ojdbc8.jar
```
I put some "I added...." comments in there so you could see what I personally inserted.

I also made a small edit to a file inside the ojdbc8.jar archive that had something to do with a timezone error, but I forget off the top of my head what that was exactly. Would have to dig through my notes.

**Comment by keremsahin1** [comment]
Dear issue owner,

Thanks for your interest in WhereHows. We have recently announced DataHub which is the rebranding of WhereHows. LinkedIn improved the architecture of WhereHows and rebranded WhereHows into DataHub and replaced its metadata infrastructure in this direction. DataHub is a more advanced and improved metadata management product compared to WhereHows. 

Unfortunately, we have to stop supporting WhereHows to better focus on DataHub and offer more help to DataHub users. Therefore, we will drop all issues related to WhereHows and will not accept any contribution for it. Active development for DataHub has already started on `datahub` branch and will continue to live in there until it's finally merged to master and project is renamed to DataHub. 

Please check the `datahub` branch to get familar with DataHub.

Best,
DataHub team
