### ISSUE TITLE
import project failed

### ISSUE THREAD

**Issue by cgf120** [linkedin/WhereHows#1243]
after i download code , exec './gradlew idea'  found error info ，please help me，thank you ！

Build failed.
Build Error (EyeglassCompiler)

File to read not found or unreadable: E:/ZTESOFT/WhereHows-master/wherehows-web/tmp/eyeglass_compiler-input_base_path-oTsbSpzt.tmp/E:/ZTESOFT/WhereHows-master/wherehows-web/tmp/eyeglass_compiler-input_base_path-oTsbSpzt.tmp/app/styles/app.scss
    at undefined:undefined:undefined

Stack Trace and Error Report: C:\Users\ADMINI~1\AppData\Local\Temp/error.dump.ecd64c86729faa519cd11c339fb820f7.log

> Task :wherehows-web:emberBuild FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':wherehows-web:emberBuild'.
> Process 'command 'E:\ZTESOFT\WhereHows-master\wherehows-web\build\nodejs\node-v8.11.2-win-x64\node.exe'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**Comment by cgf120** [comment]
error.dump.ecd64c86729faa519cd11c339fb820f7.log file content

=================================================================================

ENV Summary:

  TIME: Fri Jun 29 2018 15:38:24 GMT+0800 (中国标准时间)
  TITLE: ember
  ARGV:
  - E:\ZTESOFT\WhereHows-master\wherehows-web\build\nodejs\node-v8.11.2-win-x64\node.exe
  - E:\ZTESOFT\WhereHows-master\wherehows-web\node_modules\ember-cli\bin\ember
  - build
  - --environment
  - production
  EXEC_PATH: E:\ZTESOFT\WhereHows-master\wherehows-web\build\nodejs\node-v8.11.2-win-x64\node.exe
  TMPDIR: C:\Users\ADMINI~1\AppData\Local\Temp
  SHELL: null
  PATH:
  - E
  - \ZTESOFT\WhereHows-master\wherehows-web\build\nodejs\node-v8.11.2-win-x64;C
  - \Python27\;C
  - \Python27\Scripts;C
  - \Program Files (x86)\Intel\Intel(R) Management Engine Components\iCLS\;C
  - \Program Files\Intel\Intel(R) Management Engine Components\iCLS\;C
  - \Program Files\VanDyke Software\Clients\;C
  - \Program Files (x86)\Common Files\Oracle\Java\javapath;C
  - \Windows\system32;C
  - \Windows;C
  - \Windows\System32\Wbem;C
  - \Windows\System32\WindowsPowerShell\v1.0\;C
  - \Program Files\Intel\WiFi\bin\;C
  - \Program Files\Common Files\Intel\WirelessCommon\;C
  - \Program Files\TortoiseSVN\bin;C
  - \Program Files (x86)\NVIDIA Corporation\PhysX\Common;C
  - \Program Files\PuTTY\;C
  - \WINDOWS\system32;C
  - \WINDOWS;C
  - \WINDOWS\System32\Wbem;C
  - \WINDOWS\System32\WindowsPowerShell\v1.0\;C
  - \WINDOWS\System32\OpenSSH\;C
  - \Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C
  - \Program Files\Intel\Intel(R) Management Engine Components\DAL;C
  - \Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C
  - \Program Files\Intel\Intel(R) Management Engine Components\IPT;C
  - \Program Files\Git\cmd;C
  - \Program Files\nodejs\;C
  - \Program Files\OpenSSH\bin;C
  - \Users\Administrator\AppData\Local\Microsoft\WindowsApps;C
  - \Program Files\Intel\WiFi\bin\;C
  - \Program Files\Common Files\Intel\WirelessCommon\;C
  - \Program Files\Java\jdk1.8.0_171\bin;C
  - \Users\Administrator\AppData\Local\GitHubDesktop\bin;C
  - \Users\Administrator\AppData\Roaming\npm;E
  - \ZTESOFT\tools\apache-maven-3.3.3\bin;
  PLATFORM: win32 x64
  FREEMEM: 2826608640
  TOTALMEM: 8436953088
  UPTIME: 111500.1784357
  LOADAVG: 0,0,0
  CPUS:
  - Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz - 2208
  - Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz - 2208
  - Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz - 2208
  - Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz - 2208
  - Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz - 2208
  - Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz - 2208
  - Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz - 2208
  - Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz - 2208
  - Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz - 2208
  - Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz - 2208
  - Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz - 2208
  - Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz - 2208
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.10.1-DEV
  - cldr: 32.0
  - http_parser: 2.8.0
  - icu: 60.1
  - modules: 57
  - napi: 3
  - nghttp2: 1.29.0
  - node: 8.11.2
  - openssl: 1.0.2o
  - tz: 2017c
  - unicode: 10.0
  - uv: 1.19.1
  - v8: 6.2.414.54
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: Error: File to read not found or unreadable: E:/ZTESOFT/WhereHows-master/wherehows-web/tmp/eyeglass_compiler-input_base_path-oTsbSpzt.tmp/E:/ZTESOFT/WhereHows-master/wherehows-web/tmp/eyeglass_compiler-input_base_path-oTsbSpzt.tmp/app/styles/app.scss
    at undefined:undefined:undefined
    at options.error (E:\ZTESOFT\WhereHows-master\wherehows-web\node_modules\node-sass\lib\index.js:291:26)

  - codeFrame: File to read not found or unreadable: E:/ZTESOFT/WhereHows-master/wherehows-web/tmp/eyeglass_compiler-input_base_path-oTsbSpzt.tmp/E:/ZTESOFT/WhereHows-master/wherehows-web/tmp/eyeglass_compiler-input_base_path-oTsbSpzt.tmp/app/styles/app.scss
    at undefined:undefined:undefined
  - errorMessage: Build Canceled: Broccoli Builder ran into an error with `EyeglassCompiler` plugin. 💥
File to read not found or unreadable: E:/ZTESOFT/WhereHows-master/wherehows-web/tmp/eyeglass_compiler-input_base_path-oTsbSpzt.tmp/E:/ZTESOFT/WhereHows-master/wherehows-web/tmp/eyeglass_compiler-input_base_path-oTsbSpzt.tmp/app/styles/app.scss
    at undefined:undefined:undefined
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
    - treeDir: [undefined]
  - message: Build Canceled: Broccoli Builder ran into an error with `EyeglassCompiler` plugin. 💥
File to read not found or unreadable: E:/ZTESOFT/WhereHows-master/wherehows-web/tmp/eyeglass_compiler-input_base_path-oTsbSpzt.tmp/E:/ZTESOFT/WhereHows-master/wherehows-web/tmp/eyeglass_compiler-input_base_path-oTsbSpzt.tmp/app/styles/app.scss
    at undefined:undefined:undefined
  - name: Error
  - nodeAnnotation: EyeglassCompiler
  - nodeName: EyeglassCompiler
  - originalErrorMessage: File to read not found or unreadable: E:/ZTESOFT/WhereHows-master/wherehows-web/tmp/eyeglass_compiler-input_base_path-oTsbSpzt.tmp/E:/ZTESOFT/WhereHows-master/wherehows-web/tmp/eyeglass_compiler-input_base_path-oTsbSpzt.tmp/app/styles/app.scss
    at undefined:undefined:undefined
  - stack: Error: File to read not found or unreadable: E:/ZTESOFT/WhereHows-master/wherehows-web/tmp/eyeglass_compiler-input_base_path-oTsbSpzt.tmp/E:/ZTESOFT/WhereHows-master/wherehows-web/tmp/eyeglass_compiler-input_base_path-oTsbSpzt.tmp/app/styles/app.scss
    at undefined:undefined:undefined
    at options.error (E:\ZTESOFT\WhereHows-master\wherehows-web\node_modules\node-sass\lib\index.js:291:26)


=================================================================================

**Comment by Qsimple** [comment]
I got a same error 
`wherehows-web\build\nodejs\node-v8.11.2-win-x64\node.exe'' finished with non-zero exit value -1073741819`

**Comment by keremsahin1** [comment]
Dear issue owner,

Thanks for your interest in WhereHows. We have recently announced DataHub which is the rebranding of WhereHows. LinkedIn improved the architecture of WhereHows and rebranded WhereHows into DataHub and replaced its metadata infrastructure in this direction. DataHub is a more advanced and improved metadata management product compared to WhereHows. 

Unfortunately, we have to stop supporting WhereHows to better focus on DataHub and offer more help to DataHub users. Therefore, we will drop all issues related to WhereHows and will not accept any contribution for it. Active development for DataHub has already started on `datahub` branch and will continue to live in there until it's finally merged to master and project is renamed to DataHub. 

Please check the `datahub` branch to get familar with DataHub.

Best,
DataHub team
