### ISSUE TITLE
Build failed for Wherehows 0.2.1

### ISSUE THREAD

**Issue by EmnaDr** [linkedin/WhereHows#1246]
Hello,
I have downloaded wherehows 0.2.1 i was able to run the web application
But i the build was failed for the whole projectd(root) and for backend service as well
Any advice please?

> Task :backend-service:playClean FAILED
Task ':backend-service:playClean' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
Starting process 'command 'C:\Program Files (x86)\activator-1.3.11-minimal/bin/activator''. Working directory: G:\DevSrc\WhereHows-0.2.1\backend-service Command: C:\Program Files (x86)\activator-1.3.11-minimal/bin/activator clean
:backend-service:playClean (Thread[Task worker for ':' Thread 2,5,main]) completed. Took 0.007 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':backend-service:playClean'.
> A problem occurred starting process 'command 'C:\Program Files (x86)\activator-1.3.11-minimal/bin/activator''

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.8/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1s
1 actionable task: 1 executed

**Comment by mtHuberty** [comment]
Out of pure curiosity, why are you using 0.2.1 instead of 1.x.x?

**Comment by keremsahin1** [comment]
Dear issue owner,

Thanks for your interest in WhereHows. We have recently announced DataHub which is the rebranding of WhereHows. LinkedIn improved the architecture of WhereHows and rebranded WhereHows into DataHub and replaced its metadata infrastructure in this direction. DataHub is a more advanced and improved metadata management product compared to WhereHows. 

Unfortunately, we have to stop supporting WhereHows to better focus on DataHub and offer more help to DataHub users. Therefore, we will drop all issues related to WhereHows and will not accept any contribution for it. Active development for DataHub has already started on `datahub` branch and will continue to live in there until it's finally merged to master and project is renamed to DataHub. 

Please check the `datahub` branch to get familar with DataHub.

Best,
DataHub team
