### ISSUE TITLE
frontend UI error on a fresh install

### ISSUE THREAD

**Issue by fciannel** [linkedin/WhereHows#1292]
On a fresh installation with docker, once I connect to the frontend UI, I get the following error:

```
We encountered an error
SyntaxError: Unexpected token < in JSON at position 2
```
Where can I look for it? I used the commit from last week, before the jaas was added.

The error is appearing directly on the UI, it's not from the frontend logs.

This is from the frontend log:

```
wherehows-frontend_1       | 2018-08-04 02:38:25 INFO  application:114 - Creating DAO factory: wherehows.dao.DaoFactory
wherehows-frontend_1       | 2018-08-04 02:38:27 ERROR application:257 - Piwik site ID must be an integer
wherehows-frontend_1       | 2018-08-04 02:38:31 ERROR application:257 - Piwik site ID must be an integer
wherehows-frontend_1       | 2018-08-04 02:38:31 ERROR application:257 - Piwik site ID must be an integer
wherehows-frontend_1       | 2018-08-04 02:38:35 ERROR application:216 - 
wherehows-frontend_1       | 
wherehows-frontend_1       | ! @78ngoe5f2 - Internal server error, for (GET) [/api/v2/platforms] ->
wherehows-frontend_1       |  
wherehows-frontend_1       | play.api.UnexpectedException: Unexpected exception[UnsupportedOperationException: Operation not implemented]
wherehows-frontend_1       |    at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:261) ~[com.typesafe.play-play_2.10-2.4.11.jar:2.4.11]
wherehows-frontend_1       |    at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:191) ~[com.typesafe.play-play_2.10-2.4.11.jar:2.4.11]
wherehows-frontend_1       |    at play.api.GlobalSettings$class.onError(GlobalSettings.scala:179) [com.typesafe.play-play_2.10-2.4.11.jar:2.4.11]
wherehows-frontend_1       |    at play.api.DefaultGlobal$.onError(GlobalSettings.scala:212) [com.typesafe.play-play_2.10-2.4.11.jar:2.4.11]
wherehows-frontend_1       |    at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:94) [com.typesafe.play-play_2.10-2.4.11.jar:2.4.11]
```

**Comment by djKooks** [comment]
@fciannel I'm also facing the same error. It shows:
![screen shot 2018-08-06 at 18 55 48](https://user-images.githubusercontent.com/1720209/43710385-73344562-99aa-11e8-87a0-9a94c99e4efe.png)
after login.

Somebody knows about this?

**Comment by mtHuberty** [comment]
It would be helpful to know which version (tag) of WhereHows you cloned, and what steps you took to get to this point, including downloading any of the required external library files you're likely to need: (gsp.jar, ojdbc7.jar etc, depending on which data sources you want to crawl)

**Comment by fciannel** [comment]
I checked out this commit:

commit b1a347abaa91d2842c7d8f8ee0aa5b643af6f61b
Author: Seyi Adebajo <sadebajo@linkedin.com>
Date:   Tue Jul 24 12:32:27 2018 -0700

    rebase on deprecated browse feature

from v1.1.0

I had to use a couple of commit before the jaas.conf because the jaas is not working for me. Do you recommend using a specific tag?

**Comment by djKooks** [comment]
Mine is:
```
commit: c4354ecd
Author: Seyi Adebajo sadebajo@linkedin.com
Date: July 31, 2018 5:30:03 JST
```

**Comment by tonglin0325** [comment]
I got the same problem. how to resolve this problem? @djKooks @fciannel 
![default](https://user-images.githubusercontent.com/17646435/45687294-fbd44280-bb80-11e8-97cc-2c0bbf9e8f99.png)

**Comment by justinsuen** [comment]
Any news on this? Same problem.

**Comment by renzehello** [comment]
Any news on this? Same problem.

**Comment by SumanBharathBHNetwork** [comment]
Any update on this issue?. I am running into same problem. Built and deployed to Docker.

**Comment by arthur78** [comment]
Same problem

**Comment by arthur78** [comment]
I switched to v1.0.0 tag and could log in.

Here's the list of things I also did:

- created `~/.bowerrc` file and added into it:
`{"allow_root": true, "registry": "https://registry.bower.io"}`
otherwise the `./build.sh 1` was failing

- created a test user within a mysql container:
`INSERT INTO wherehows.users
(name, email, username, password_digest, password_digest_type, authentication_type)
VALUES
('test', 'test@email.com', 'test', SHA1('test'), 'SHA1', 'default')`

- modified `wherehows-docker/wherehows-frontend/Dockerfile`, added:
`ENV JAVA_OPTS -Djava.security.auth.login.config=/application/conf/jaas.conf`

**Comment by keremsahin1** [comment]
Dear issue owner,

Thanks for your interest in WhereHows. We have recently announced DataHub which is the rebranding of WhereHows. LinkedIn improved the architecture of WhereHows and rebranded WhereHows into DataHub and replaced its metadata infrastructure in this direction. DataHub is a more advanced and improved metadata management product compared to WhereHows. 

Unfortunately, we have to stop supporting WhereHows to better focus on DataHub and offer more help to DataHub users. Therefore, we will drop all issues related to WhereHows and will not accept any contribution for it. Active development for DataHub has already started on `datahub` branch and will continue to live in there until it's finally merged to master and project is renamed to DataHub. 

Please check the `datahub` branch to get familar with DataHub.

Best,
DataHub team
