### ISSUE TITLE
Hive blacklist not working

### ISSUE THREAD

**Issue by fciannel** [linkedin/WhereHows#1306]
I have configured the hive job to have whitelist enabled and blacklist disabled, I still see that all the databases are selected,, even if the whitelist only contains one entry.

This is what the database logs are capturing:

SELECT `NAME` FROM DBS WHERE `NAME` IN ('gcs_eloqua') OR NOT (`NAME` IN ('''') OR `NAME` LIKE 'u\_%')

It does not look like the blacklist disabled is being taken into consideration?

My aim is to have only the gcs_eloqua database to be pulled.

**Comment by keremsahin1** [comment]
Dear issue owner,

Thanks for your interest in WhereHows. We have recently announced DataHub which is the rebranding of WhereHows. LinkedIn improved the architecture of WhereHows and rebranded WhereHows into DataHub and replaced its metadata infrastructure in this direction. DataHub is a more advanced and improved metadata management product compared to WhereHows. 

Unfortunately, we have to stop supporting WhereHows to better focus on DataHub and offer more help to DataHub users. Therefore, we will drop all issues related to WhereHows and will not accept any contribution for it. Active development for DataHub has already started on `datahub` branch and will continue to live in there until it's finally merged to master and project is renamed to DataHub. 

Please check the `datahub` branch to get familar with DataHub.

Best,
DataHub team
