### ISSUE TITLE
Feature Request: Business or Conceptual Object definitions

### ISSUE THREAD

**Issue by dmoore247** [linkedin/WhereHows#131]
Make it possible to import, edit, add business or conceptual object definitions and then link them to environments, systems, databases, subject areas, entities, and fields. Support bi-directional navigation within the UI.

**Comment by ericsun2** [comment]
Hi @dmoore247,

We are going to add the following entities to WhereHows as typed tags:
- Business Term
  - Line of Business: BU:Sales, BU:Marketing/International/APEC
  - Product Group / Product: Product:Eletronic/Mobile, Product:OnlineSelfServiceReporting
  - Project Group / Project: Project:SecrectProject123, Project:Nexus/ChurnPredicitonV3
  - Acronym: ORM, BPM, LTS, AWS

Are these inline with your expectation? Please elaborate with more details in your mind.

Thank you.

**Comment by dmoore247** [comment]
Business Term sounds very useful.. 
I guess what I'm thinking about can take on properties and have relationships.
Example: Sensitivity, ownership, rights and other relationships such as expert, user, contributor, designer, is-a, has,...

**Comment by ericsun2** [comment]
Building a data model for graph. That is a typical feature for knowledge and relationship management.

Scaling the flexible graph data model in MySql is going to be a performance challenge. If we have to give up some features from the full-blown graph model, which relationships are must-have?

**Comment by dmoore247** [comment]
Let's brainstorm for a moment then later cut scope?
[dataset] <---> Permissions  <--->  Group  <---> User
[dataset] <--->  Permissions <--->  User    -- Derived permissions
Owner, Steward
[dataset] <--->  [dataset]

Will the Business term support other tags like:
  Environment Env:Prod, Env:Test,Env:Dev
  Data Classification:  Sensitivity:Restricted, Sensitivity:Confidential, Sensitivity:Internal, Sensitivity:Public

And the tag sets, are they configurable by end user?
And one can navigate from object to tag to objects with that tag?
Can datasets, fields, and ETL flows be tagged?

If so, that does sound really powerful, covering most of the needs I can think of.

**Comment by planckiii** [comment]
+1 for tagging

**Comment by ismailsimsek** [comment]
+1

**Comment by keremsahin1** [comment]
Dear issue owner,

Thanks for your interest in WhereHows. We have recently announced DataHub which is the rebranding of WhereHows. LinkedIn improved the architecture of WhereHows and rebranded WhereHows into DataHub and replaced its metadata infrastructure in this direction. DataHub is a more advanced and improved metadata management product compared to WhereHows. 

Unfortunately, we have to stop supporting WhereHows to better focus on DataHub and offer more help to DataHub users. Therefore, we will drop all issues related to WhereHows and will not accept any contribution for it. Active development for DataHub has already started on `datahub` branch and will continue to live in there until it's finally merged to master and project is renamed to DataHub. 

Please check the `datahub` branch to get familar with DataHub.

Best,
DataHub team
