### ISSUE TITLE
Lineage without Azkaban

### ISSUE THREAD

**Issue by Calprice** [linkedin/WhereHows#1311]
I am interested in using the data lineage tracking features of WhereHows, but do not use Azkaban, Appworx, or any of the schedulers currently supported by WhereHows. Current documentation points here for setting up the lineage features: https://github.com/linkedin/WhereHows/tree/master/wherehows-etl. However, this page seems to imply that those features are only available for supported schedulers. Is there another way to access this feature and track data lineage?

**Comment by mtHuberty** [comment]
We have been interested in lineage for datasets and have been unable to figure out a way to get that functionality working. There was a way to configure your own via the backend api, but previous replies from the team indicate that it's no longer working as originally intended, and not recommended for use.

**Comment by keremsahin1** [comment]
Dear issue owner,

Thanks for your interest in WhereHows. We have recently announced DataHub which is the rebranding of WhereHows. LinkedIn improved the architecture of WhereHows and rebranded WhereHows into DataHub and replaced its metadata infrastructure in this direction. DataHub is a more advanced and improved metadata management product compared to WhereHows. 

Unfortunately, we have to stop supporting WhereHows to better focus on DataHub and offer more help to DataHub users. Therefore, we will drop all issues related to WhereHows and will not accept any contribution for it. Active development for DataHub has already started on `datahub` branch and will continue to live in there until it's finally merged to master and project is renamed to DataHub. 

Please check the `datahub` branch to get familar with DataHub.

Best,
DataHub team
