### ISSUE TITLE
Question: Mailing list or slack channel?

### ISSUE THREAD

**Issue by dmoore247** [linkedin/WhereHows#132]
Are there any group communication channels? I could not find this in looking through the Wiki, blog post,....

**Comment by SunZhaonan** [comment]
https://groups.google.com/forum/#!forum/wherehows
is the group

**Comment by dmoore247** [comment]
Thank you! Perhaps this would be useful info in the README.md or on the wikie.

**Comment by dmoore247** [comment]
Try gitter: https://gitter.im/wherehows/Lobby
