### ISSUE TITLE
WhereHows源码编译后，启动UI，初始化的用户名和密码是多少

### ISSUE THREAD

**Issue by hanwangabc** [linkedin/WhereHows#1342]
我按照github上的用户指南，对WhereHows进行了编译，并且通过httt://localhost:9001 访问ui,但是没有用户名和密码，按照文档上说的右上角有创建连接，我也没找到

**Comment by EastGuaPy** [comment]
需要连数据库，找到用户表，插入用户

**Comment by hanwangabc** [comment]
里面有张users表，是这张吗？另外其他的字段录入什么？

**Comment by PolarisRaven** [comment]
大佬，是怎么编译的，新手求指导！！！

**Comment by tonglin0325** [comment]
编译成功了,但是也是找不到登录方法

**Comment by cgf120** [comment]
user表里面自己添加用户就好了，注意加密方式用默认的

**Comment by tonglin0325** [comment]
@cgf120 我参考issue 616 使用下面的语句添加用户后使用账号test和密码test仍然无法登录,然后front-end日志中报错 WARN  application:359 - Authentication error!
javax.naming.AuthenticationException: javax.security.auth.login.LoginException: 没有为WHZ-Authentication配置 LoginModules

使用的插入用户语句
INSERT INTO wherehows.users
(name, email, username, password_digest, password_digest_type, authentication_type)
VALUES
('test', 'test@openx.com', 'test', SHA1('test'), 'SHA1', 'default')

**Comment by yinsong** [comment]
@tonglin0325 大佬你这个报错后面是怎么解决的,我也遇到相同的问题了

**Comment by jimmy-src** [comment]
#1457 

加微信群讨论

**Comment by tonglin0325** [comment]
@yinsong 使用v1.0.0的源代码，v1.1.0的代码会有问题

**Comment by hanwangabc** [comment]
> @yinsong 使用v1.0.0的源代码，v1.1.0的代码会有问题

1.1.0引入了LDAP做认证

**Comment by keremsahin1** [comment]
Dear issue owner,

Thanks for your interest in WhereHows. We have recently announced DataHub which is the rebranding of WhereHows. LinkedIn improved the architecture of WhereHows and rebranded WhereHows into DataHub and replaced its metadata infrastructure in this direction. DataHub is a more advanced and improved metadata management product compared to WhereHows. 

Unfortunately, we have to stop supporting WhereHows to better focus on DataHub and offer more help to DataHub users. Therefore, we will drop all issues related to WhereHows and will not accept any contribution for it. Active development for DataHub has already started on `datahub` branch and will continue to live in there until it's finally merged to master and project is renamed to DataHub. 

Please check the `datahub` branch to get familar with DataHub.

Best,
DataHub team
