### ISSUE TITLE
Issue about logs of WhereHows

### ISSUE THREAD

**Issue by lg985** [linkedin/WhereHows#1348]
Where is the log address about WhereHows? I want to check the running logs. Could you please give some guide for me. thanks in advance.

**Comment by igbopie** [comment]
Hi, what do you mean log address? I guess depending on what log you are trying to find, you will find it in different places. Could you elaborate your question please? thank you.

**Comment by mtHuberty** [comment]
Are you running it in docker containers or just using the pure gradle build?

**Comment by keremsahin1** [comment]
Dear issue owner,

Thanks for your interest in WhereHows. We have recently announced DataHub which is the rebranding of WhereHows. LinkedIn improved the architecture of WhereHows and rebranded WhereHows into DataHub and replaced its metadata infrastructure in this direction. DataHub is a more advanced and improved metadata management product compared to WhereHows. 

Unfortunately, we have to stop supporting WhereHows to better focus on DataHub and offer more help to DataHub users. Therefore, we will drop all issues related to WhereHows and will not accept any contribution for it. Active development for DataHub has already started on `datahub` branch and will continue to live in there until it's finally merged to master and project is renamed to DataHub. 

Please check the `datahub` branch to get familar with DataHub.

Best,
DataHub team
