### ISSUE TITLE
The error alerts when I login from UI side

### ISSUE THREAD

**Issue by lg985** [linkedin/WhereHows#1349]
![image](https://user-images.githubusercontent.com/39213065/44845055-18b2df80-ac7f-11e8-8041-db4a2df5806e.png)
![image](https://user-images.githubusercontent.com/39213065/44845114-3e3fe900-ac7f-11e8-86ba-c3336732589b.png)
Just as snapshot shows, the error alerts when I login from UI side.

**Comment by igbopie** [comment]
Looks like this feature is not complete, that is why you see that error. I agree that it shouldn't be there, but it does not block execution.

**Comment by keremsahin1** [comment]
Dear issue owner,

Thanks for your interest in WhereHows. We have recently announced DataHub which is the rebranding of WhereHows. LinkedIn improved the architecture of WhereHows and rebranded WhereHows into DataHub and replaced its metadata infrastructure in this direction. DataHub is a more advanced and improved metadata management product compared to WhereHows. 

Unfortunately, we have to stop supporting WhereHows to better focus on DataHub and offer more help to DataHub users. Therefore, we will drop all issues related to WhereHows and will not accept any contribution for it. Active development for DataHub has already started on `datahub` branch and will continue to live in there until it's finally merged to master and project is renamed to DataHub. 

Please check the `datahub` branch to get familar with DataHub.

Best,
DataHub team
