### ISSUE TITLE
./gradlew build error Version 1.1.0 

### ISSUE THREAD

**Issue by changhaike** [linkedin/WhereHows#1386]
when I run ./gradlew build,It comes the following error msg.The wherehows version is 1.1.0.

> Task :wherehows-web:bowerInstall
bower ESUDO         Cannot be run with sudo

Additional error details:
Since bower is a user command, there is no need to execute it with superuser permissions.
If you're having permission errors when using bower without sudo, please spend a few minutes learning more about how your system should work and make any necessary repairs.

http://www.joyent.com/blog/installing-node-and-npm
https://gist.github.com/isaacs/579814

You can however run a command with sudo using --allow-root option

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':wherehows-web:bowerInstall'.
> Process 'command '/opt/WhereHows-1.1.0/wherehows-web/build/nodejs/node-v8.9.1-linux-x64/bin/node'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED in 2s

**Comment by useracn** [comment]
also encoutered this but using wherehows v1.0.

**Comment by yinsong** [comment]
@changhaike  
vim /WhereHows-1.1.0/wherehows-web/.bowerrc
add "allow_root": true

**Comment by useracn** [comment]
Thanks. I applied this with **"registry": "https://registry.bower.io** as I encountered another error for bower during build.  Build is now successful but has issues on launching the UI.

**Comment by keremsahin1** [comment]
Dear issue owner,

Thanks for your interest in WhereHows. We have recently announced DataHub which is the rebranding of WhereHows. LinkedIn improved the architecture of WhereHows and rebranded WhereHows into DataHub and replaced its metadata infrastructure in this direction. DataHub is a more advanced and improved metadata management product compared to WhereHows. 

Unfortunately, we have to stop supporting WhereHows to better focus on DataHub and offer more help to DataHub users. Therefore, we will drop all issues related to WhereHows and will not accept any contribution for it. Active development for DataHub has already started on `datahub` branch and will continue to live in there until it's finally merged to master and project is renamed to DataHub. 

Please check the `datahub` branch to get familar with DataHub.

Best,
DataHub team
