### ISSUE TITLE
报错如下

### ISSUE THREAD

**Issue by wuchenlv1988** [linkedin/WhereHows#1398]
2018-09-20 14:11:43 ERROR c.j.b.ConnectionHandle:388 - Database access problem. Killing off this connection and all remaining connections in the connection pool. SQL State = HY000
2018-09-20 14:11:44 ERROR application:742 - PreparedStatementCallback; uncategorized SQLException for SQL [SELECT SQL_CALC_FOUND_ROWS id, `name`, `schema`, `source`, `urn`, FROM_UNIXTIME(source_modified_time) as modified, rank_01 + rank_02 + rank_03 + rank_04 + rank_05 + rank_06 + rank_07 + rank_08 + rank_09 as rank FROM (SELECT id, `name`, `schema`, `source`, `urn`, source_modified_time, CASE WHEN `name` = 'aum' THEN 3000 ELSE 0 END rank_01, CASE WHEN `name` like 'aum%' THEN 2000 ELSE 0 END rank_02, CASE WHEN `name` like '%aum%' THEN 1000 ELSE 0 END rank_03, CASE WHEN `urn` = 'aum' THEN 300 ELSE 0 END rank_04, CASE WHEN `urn` like 'aum%' THEN 200 ELSE 0 END rank_05, CASE WHEN `urn` like '%aum%' THEN 100 ELSE 0 END rank_06, CASE WHEN `schema` = 'aum' THEN 30 ELSE 0 END rank_07, CASE WHEN `schema` like 'aum%' THEN 20 ELSE 0 END rank_08, CASE WHEN `schema` like '%aum%' THEN 10 ELSE 0 END rank_09 FROM dict_dataset WHERE MATCH(`name`, `schema`,  `properties`, `urn`) AGAINST ('*aum* *v_aum*' IN BOOLEAN MODE) ) t ORDER BY rank DESC, `name`, `urn` LIMIT ?, ?;]; SQL state [HY000]; error code [1271]; Illegal mix of collations for operation 'match'; nested exception is java.sql.SQLException: Illegal mix of collations for operation 'match'
2018-09-20 14:11:44 ERROR o.s.t.s.TransactionTemplate:167 - Application exception overridden by rollback exception
org.springframework.jdbc.UncategorizedSQLException: StatementCallback; uncategorized SQLException for SQL [SELECT FOUND_ROWS()]; SQL state [null]; error code [0]; Connection is closed!; nested exception is java.sql.SQLException: Connection is closed!

为啥这个ddl语句是 DEFAULT CHARSET = latin1;有的是utf8
- dataset table
CREATE TABLE `dict_dataset` (
  `id`                          INT(11) UNSIGNED NOT NULL                                                                   AUTO_INCREMENT,
  `db_id`                       SMALLINT(6) UNSIGNED NOT NULL                                                               DEFAULT 0,
  `name`                        VARCHAR(200)                                                                                NOT NULL,
  `schema`                      MEDIUMTEXT CHARACTER SET utf8,
  `schema_type`                 VARCHAR(50)                                                                                 DEFAULT 'JSON'
  COMMENT 'JSON, Hive, DDL, XML, CSV',
  `properties`                  TEXT CHARACTER SET utf8,
  `fields`                      MEDIUMTEXT CHARACTER SET utf8,
  `urn`                         VARCHAR(500)                                                                                NOT NULL,
  `source`                      VARCHAR(50)                                                                                 NULL
  COMMENT 'The original data source type (for dataset in data warehouse). Oracle, Kafka ...',
  `location_prefix`             VARCHAR(200)                                                                                NULL,
  `parent_name`                 VARCHAR(500)                                                                                NULL
  COMMENT 'Schema Name for RDBMS, Group Name for Jobs/Projects/Tracking Datasets on HDFS ',
  `storage_type`                ENUM('Table', 'View', 'Avro', 'ORC', 'RC', 'Sequence', 'Flat File', 'JSON', 'BINARY_JSON', 'XML', 'Thrift', 'Parquet', 'Protobuff') NULL,
  `ref_dataset_id`              INT(11) UNSIGNED                                                                            NULL
  COMMENT 'Refer to Master/Main dataset for Views/ExternalTables',
  `is_active`                   BOOLEAN NULL COMMENT 'is the dataset active / exist ?',
  `is_deprecated`               BOOLEAN NULL COMMENT 'is the dataset deprecated by user ?',
  `dataset_type`                VARCHAR(30)                                                                                 NULL
  COMMENT 'hdfs, hive, kafka, teradata, mysql, sqlserver, file, nfs, pinot, salesforce, oracle, db2, netezza, cassandra, hbase, qfs, zfs',
  `hive_serdes_class`           VARCHAR(300)                                                                                NULL,
  `is_partitioned`              CHAR(1)                                                                                     NULL,
  `partition_layout_pattern_id` SMALLINT(6)                                                                                 NULL,
  `sample_partition_full_path`  VARCHAR(256)
  COMMENT 'sample partition full path of the dataset',
  `source_created_time`         INT UNSIGNED                                                                                NULL
  COMMENT 'source created time of the flow',
  `source_modified_time`        INT UNSIGNED                                                                                NULL
  COMMENT 'latest source modified time of the flow',
  `created_time`                INT UNSIGNED COMMENT 'wherehows created time',
  `modified_time`               INT UNSIGNED COMMENT 'latest wherehows modified',
  `wh_etl_exec_id`              BIGINT COMMENT 'wherehows etl execution id that modified this record',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_dataset_db_id_urn` (`db_id`,`urn`)
)
  ENGINE = InnoDB
  DEFAULT CHARSET = latin1;

**Comment by jimmy-src** [comment]
#1457 

加微信群讨论

**Comment by keremsahin1** [comment]
Dear issue owner,

Thanks for your interest in WhereHows. We have recently announced DataHub which is the rebranding of WhereHows. LinkedIn improved the architecture of WhereHows and rebranded WhereHows into DataHub and replaced its metadata infrastructure in this direction. DataHub is a more advanced and improved metadata management product compared to WhereHows. 

Unfortunately, we have to stop supporting WhereHows to better focus on DataHub and offer more help to DataHub users. Therefore, we will drop all issues related to WhereHows and will not accept any contribution for it. Active development for DataHub has already started on `datahub` branch and will continue to live in there until it's finally merged to master and project is renamed to DataHub. 

Please check the `datahub` branch to get familar with DataHub.

Best,
DataHub team
