### ISSUE TITLE
Task :wherehows-web:yarn FAILED

### ISSUE THREAD

**Issue by Refa90** [linkedin/WhereHows#1418]
When running installation stage "From the wherehows-docker, run build.sh 1", I'm getting the following error:
15:11:27.883 [LIFECYCLE] [class org.gradle.internal.buildevents.TaskExecutionLogger] > Task :wherehows-web:yarn FAILED
15:11:28.545 [ERROR] [system.err] error An unexpected error occurred: "https://codeload.github.com/ember-decorators/runloop/tar.gz/73a0827c11d0f8de01eda6a7e03a0106b00963dc: self signed certificate in certificate chain"
15:11:28.556 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Process 'command '/Users/refaela/WhereHows/wherehows-web/build/yarn/yarn-latest/bin/yarn'' finished with exit value 1 (state: FAILED)
15:11:28.560 [ERROR] [org.gradle.internal.buildevents.BuildResultLogger] BUILD FAILED in 1m 0s

Please help - no info regarding this problem found on the web

**Comment by theseyi** [comment]
@Refa90 Sorry you're having this issue, could you provide the detailed steps you took to arrive at this exception so we can reproduce and resolve? thanks

**Comment by Refa90** [comment]
I cloned the repo to my local mac.
Then I followed this guide: https://github.com/linkedin/WhereHows/blob/master/wherehows-docker/README.md
docker is already installed on my pc, so I run the script on stage 2 as mentioned above.
Then I got the following exception.
Thanks for your reply

**Comment by CristianoMarquesPoa** [comment]
Hi, me too have this problem. My docker are instaled on windows 10. I did all the suggested tests but it did not work.

**Comment by j4m4l** [comment]
I am having absolutely the same problem on fresh build.

**Comment by keremsahin1** [comment]
Dear issue owner,

Thanks for your interest in WhereHows. We have recently announced DataHub which is the rebranding of WhereHows. LinkedIn improved the architecture of WhereHows and rebranded WhereHows into DataHub and replaced its metadata infrastructure in this direction. DataHub is a more advanced and improved metadata management product compared to WhereHows. 

Unfortunately, we have to stop supporting WhereHows to better focus on DataHub and offer more help to DataHub users. Therefore, we will drop all issues related to WhereHows and will not accept any contribution for it. Active development for DataHub has already started on `datahub` branch and will continue to live in there until it's finally merged to master and project is renamed to DataHub. 

Please check the `datahub` branch to get familar with DataHub.

Best,
DataHub team
