### ISSUE TITLE
Web Application Config - connection question

### ISSUE THREAD

**Issue by RDDOUB** [linkedin/WhereHows#142]
I'm new here, but I have mysql set up and am not sure where I add the connection information on the application.conf file? If anyone has a mocked up example I would really appreciate it.

Start the web application server

Make sure your web/conf/application.conf file have the correct connection info for your mysql database. You can either edit it in your code or run with a specific configuration file location with '-Dconfig.file=$YOUR_CONFIG_FILE' option.

**Comment by jerrybai2009** [comment]
In the web/conf/application.conf,
you can see below code:

database.opensource.username = "wherehows"
database.opensource.password = "wherehows"
database.opensource.url = "jdbc:mysql://localhost/wherehows?charset=utf8&zeroDateTimeBehavior=convertToNull"

Replace the username, password and url with your mysql settings.
This file is default application configuration file.

If you have different configuration file, you can user -Dconfig.file=$YOUR_FILE command option when start your web server

**Comment by RDDOUB** [comment]
Thanks, I was in the right place and had an issue with my url.
