### ISSUE TITLE
Build web frontend error

### ISSUE THREAD

**Issue by cnwarden** [linkedin/WhereHows#1426]
anyone know how to fix this issue? I have tried v1.1.0 and v1.0.0, the same issue.

![image](https://user-images.githubusercontent.com/1269145/46245399-8b9aac00-c41f-11e8-8efe-f44839b869ab.png)

**Comment by jimmy-src** [comment]
you can try:
```
cd wherehows-web
npm install
bower install
```
and then
```
cd ..
./gradlew build
./gradlew build dist
```

**Comment by jimmy-src** [comment]
#1457

加微信群讨论

**Comment by Ash-Mishra** [comment]
Try running as a super user. That fixed it for me.
If it still doesn't work ,as an additional step try adding
{
"allow_root": true,
"registry": "https://registry.bower.io"
}
to .bowerrc file

**Comment by keremsahin1** [comment]
Dear issue owner,

Thanks for your interest in WhereHows. We have recently announced DataHub which is the rebranding of WhereHows. LinkedIn improved the architecture of WhereHows and rebranded WhereHows into DataHub and replaced its metadata infrastructure in this direction. DataHub is a more advanced and improved metadata management product compared to WhereHows. 

Unfortunately, we have to stop supporting WhereHows to better focus on DataHub and offer more help to DataHub users. Therefore, we will drop all issues related to WhereHows and will not accept any contribution for it. Active development for DataHub has already started on `datahub` branch and will continue to live in there until it's finally merged to master and project is renamed to DataHub. 

Please check the `datahub` branch to get familar with DataHub.

Best,
DataHub team
