### ISSUE TITLE
Why Metrics/Schema History no data? And how to import?

### ISSUE THREAD

**Issue by YunKillerE** [linkedin/WhereHows#1447]
WhereHows version v1.0.0

![image](https://user-images.githubusercontent.com/12254857/47202070-a91fbd80-d3ae-11e8-9480-a4dd7d4d2daf.png)

I have already import hive metadata and azkaban metadata

but Metrics/Schema History no data?
How to import?

Thanks!

**Comment by jimmy-src** [comment]
insert into dict_dataset_schema_history(dataset_id,urn,modified_date,`schema`) select id as dataset_id, urn,  FROM_UNIXTIME(modified_time) as modified_date, `schema` from dict_dataset where id > 0

And UI Schema History works

#1457

加群讨论

**Comment by Ash-Mishra** [comment]
I have got a solution for this. After every Etl job we want the schema history to be updated based on the data in dict_dataset.
I have added an extra function in the corresponding Load.py file for which you want the schema history.

Just use this funtion in your load.py file

```
def update_schema_history(self):
    update_schema_history_cmd = '''
    insert into
      dict_dataset_schema_history(dataset_id, urn, modified_date, `schema`)
    select
      id as dataset_id,
      urn,
      FROM_UNIXTIME(modified_time) as modified_date,
      `schema`
    from
      dict_dataset as s
    where
      s.id > 0
      and date(FROM_UNIXTIME(s.modified_time)) not in (
        select
          modified_date
        from
          dict_dataset_schema_history
        where
          urn = s.urn
      );
    
    
    update
      dict_dataset_schema_history
      inner join dict_dataset on (
        dict_dataset_schema_history.dataset_id = dict_dataset.id
        and dict_dataset_schema_history.modified_date = date(FROM_UNIXTIME(dict_dataset.modified_time))
      )
    set
      dict_dataset_schema_history.schema = dict_dataset.schema;
    '''
    self.logger.info(update_schema_history_cmd)
    self.executeCommands(update_schema_history_cmd)
    self.logger.info("finish updating schema history")

**Comment by keremsahin1** [comment]
Dear issue owner,

Thanks for your interest in WhereHows. We have recently announced DataHub which is the rebranding of WhereHows. LinkedIn improved the architecture of WhereHows and rebranded WhereHows into DataHub and replaced its metadata infrastructure in this direction. DataHub is a more advanced and improved metadata management product compared to WhereHows. 

Unfortunately, we have to stop supporting WhereHows to better focus on DataHub and offer more help to DataHub users. Therefore, we will drop all issues related to WhereHows and will not accept any contribution for it. Active development for DataHub has already started on `datahub` branch and will continue to live in there until it's finally merged to master and project is renamed to DataHub. 

Please check the `datahub` branch to get familar with DataHub.

Best,
DataHub team
