### ISSUE TITLE
Deploy experience share

### ISSUE THREAD

**Issue by YunKillerE** [linkedin/WhereHows#1449]
***tag v1.0.0***

- Open DEBUG
- Com not add Owner
- LDAP User import method
- Azkaban Lineage import error
- Chinese garbled（中文乱码）
- can't add comments

## 1. Open DEBUG

wherehows-frontend/conf/logback.xml
wherehows-backend/conf/logback.xml

![image](https://user-images.githubusercontent.com/12254857/47471470-f67fad00-d83c-11e8-9183-3432e3d0ca41.png)

![image](https://user-images.githubusercontent.com/12254857/47471529-4199c000-d83d-11e8-84e1-5d82b60e78d8.png)

And you need to rebuild the project and redeploy.

Then you can click the UI, and you can find the query SQL from the WEB log

## 2. Com not add Owner

Analysis the debug log..

#1446 

Then you nedd to import the LDAP Users, will share it soon..

## 3. LDAP User import method

My company use OpenLDAP........

The important config:

```
ldap.search.domains=["cn=xxx,ou=xxx,dc=xxx,dc=com"]
ldap.search.return.attributes=["uidNumber", "cn", "sn","sn","sn","uid","cn","mail","gidNumber","cn","createTimestamp","uid"]
ldap.inactive.domain=
```
```
ldap.group.search.domains=["cn=xxx,ou=xxx,dc=xxx,dc=com"]
ldap.group.search.return.attributes=["gidNumber", "cn"]
```

You need known Openldap administrator username/password, and you can use the tool **ApacheDirectoryStudio** to connect openladp, then you can see the attributes etc.

And the attributes  need to Corresponding to the shell wherehows-etl/src/main/resources/jython/LdapExtract.py

```
return_attributes_standard = ['user_id', 'distinct_name', 'name', 'display_name', 'title', 'employee_number',
                                  'manager', 'mail', 'department_number', 'department', 'start_date', 'mobile']
return_attributes_standard = ['group_id', 'member_ids']
```

## 4. Azkaban Lineage import error

- NullPointerException

HadoopJobHistoryNodeExtractor.java

```
System.setProperty("java.security.auth.login.config", findFileInSearchPath(searchPath, "gss-jaas.conf"));
System.setProperty("java.security.krb5.conf", findFileInSearchPath(searchPath, "krb5.conf"));
System.setProperty("java.security.krb5.realm", prop.getProperty(Constant.KRB5_REALM));
System.setProperty("java.security.krb5.kdc", prop.getProperty(Constant.KRB5_KDC));
```

You need to set those some parameters or delete it.

I hope someone can solve the.

- After import the Azkaban data, but com't see at the UI

#1441 

- Can't import Azkaban metadata

#1448 

- Then Azkaban metadata imported, but UI can't see the Lineage

Analysis the Debug log, I find **abstracted_object_name** can't match the values

```
SELECT ca.app_id, ca.app_code as cluster, jedl.job_name, fj.job_path, fj.job_type, jedl.flow_path, jedl.storage_type, 
jedl.source_target_type, jedl.operation, MAX(jedl.source_srl_no), MAX(jedl.srl_no), MAX(jedl.job_exec_id) as job_exec_id 
FROM job_execution_data_lineage jedl 
JOIN cfg_application ca on ca.app_id = jedl.app_id 
LEFT JOIN job_execution je on jedl.app_id = je.app_id and jedl.flow_exec_id = je.flow_exec_id and jedl.job_exec_id = je.job_exec_id 
LEFT JOIN flow_job fj on je.app_id = fj.app_id and je.flow_id = fj.flow_id and je.job_id = fj.job_id 
WHERE abstracted_object_name in ("/xx/xx")
and jedl.flow_path not REGEXP '^(rent-metrics:|tracking-investigation:)'
and FROM_UNIXTIME(job_finished_unixtime) >  CURRENT_DATE - INTERVAL (1) DAY 
GROUP BY ca.app_id, cluster, jedl.job_name, fj.job_path, fj.job_type, jedl.flow_path, jedl.source_target_type, jedl.storage_type, jedl.operation 
ORDER BY jedl.source_target_type DESC, job_exec_id
```

The UI query SQL is **/xx/xx**
But the mysql values is **viewfs://xx/xx/xx/hive/warehouse/xx.db/xx/xx/dt=20181022**

So I change the code LineageCombiner.java and AzLineageExtractor.java

LineageCombiner.java
```
+        String abo = "";
+        if(datasetPath.abstractPath.contains("viewfs")  & datasetPath.abstractPath.length() > 7) {
+          String[] aboArray = datasetPath.abstractPath.split("/");
+          for(String s:aboArray){
+            logger.debug("add by yc abstractPath1===================" + s);
+          }
+          abo = "/" + aboArray[7].replace(".db", "") + "/" + aboArray[8];
+          logger.debug("add by yc abstractPath1===================" + abo);
+        }else{
+          abo = datasetPath.abstractPath;
+          String[] aboArray = datasetPath.abstractPath.split("/");
+          for(String s:aboArray){
+            logger.debug("add by yc abstractPath2===================" + s);
+          }
+          logger.debug("add by yc abstractPath2 FULL===================" + abo);
+        }
+        lr.setAbstractObjectName(abo);
```

AzLineageExtractor.java
```
+    logger.error("add by yc: get flowSequence value");
     String[] flowSequence = message.azkabanJobExecution.getFlowPath().split(":")[1].split("/");
+    logger.error("add by yc: get flowSequence length:"+flowSequence.length);
+    for(String s: flowSequence) {
+      logger.error("add by yc: get flowSequence value: \""+s+"\"");
+    }
     String jobPrefix = "";
-    for (int i = 1; i < flowSequence.length; i++) {
-      jobPrefix += flowSequence[i] + ":";
+
+    if(flowSequence.length > 2) {
+      for (int i = 1; i < flowSequence.length; i++) {
+        logger.error("add by yc: flowSequence[i] \""+flowSequence[i]+"\"");
+        jobPrefix += flowSequence[i] + ":";
+      }
     }

.....

-    lineageCombiner.addAll(oneAzkabanJobLineage);
+    lineageCombiner.addAllWoPartitionUpdate(oneAzkabanJobLineage);
....
-    lineageCombiner.addAll(lineageFromLog);
+    lineageCombiner.addAllWoPartitionUpdate(lineageFromLog);

```

 **For reference only, such as have mistake please correct me**

So I can see the HIVE metadata and can owner it、Azkaban metadata、Lineage.

But part of the lack of Lineage, Feeling is that some rules table configuration problems.

## Chinese garbled（中文乱码）

![image](https://user-images.githubusercontent.com/12254857/49361997-69bbef00-f718-11e8-984d-83cb0917b732.png)

add 
```
?useUnicode=true&characterEncoding=UTF-8
```
to mysql WHZ_DB_URL

```
jdbc:mysql://x.x.x.x/wherehows?useUnicode=true&characterEncoding=UTF-8
```

## can't add comments

#1460 

@Ash-Mishra thanks

![image](https://user-images.githubusercontent.com/12254857/49361869-09c54880-f718-11e8-8efb-43b6a202634a.png)

![image](https://user-images.githubusercontent.com/12254857/49361910-25305380-f718-11e8-9757-2318b24d5813.png)

## 5. Could someone knwon this?

#1447 

Why Metrics/Schema History no data? And how to import?

Thanks.

**Comment by jimmy-src** [comment]
#1457 

加微信群讨论

**Comment by jimmy-src** [comment]
Schema History can import

```
select id as dataset_id, urn,  FROM_UNIXTIME(modified_time) as modified_date, `schema` from dict_dataset order by dataset_id desc limit 10

insert into dict_dataset_schema_history(dataset_id,urn,modified_date,`schema`) select id as dataset_id, urn,  FROM_UNIXTIME(modified_time) as modified_date, `schema` from dict_dataset where id > 0

```

Anyone knowns how to auto import ?

**Comment by Ash-Mishra** [comment]
I have got a solution for this. After every Etl job we want the schema history to be updated based on the data in dict_dataset.
I have added an extra function in the corresponding Load.py file for which you want the schema history.

Just use this funtion in your load.py file

```
def update_schema_history(self):
    update_schema_history_cmd = '''
    insert into
      dict_dataset_schema_history(dataset_id, urn, modified_date, `schema`)
    select
      id as dataset_id,
      urn,
      FROM_UNIXTIME(modified_time) as modified_date,
      `schema`
    from
      dict_dataset as s
    where
      s.id > 0
      and date(FROM_UNIXTIME(s.modified_time)) not in (
        select
          modified_date
        from
          dict_dataset_schema_history
        where
          urn = s.urn
      );
    
    
    update
      dict_dataset_schema_history
      inner join dict_dataset on (
        dict_dataset_schema_history.dataset_id = dict_dataset.id
        and dict_dataset_schema_history.modified_date = date(FROM_UNIXTIME(dict_dataset.modified_time))
      )
    set
      dict_dataset_schema_history.schema = dict_dataset.schema;
    '''
    self.logger.info(update_schema_history_cmd)
    self.executeCommands(update_schema_history_cmd)
    self.logger.info("finish updating schema history")```

**Comment by keremsahin1** [comment]
Dear issue owner,

Thanks for your interest in WhereHows. We have recently announced DataHub which is the rebranding of WhereHows. LinkedIn improved the architecture of WhereHows and rebranded WhereHows into DataHub and replaced its metadata infrastructure in this direction. DataHub is a more advanced and improved metadata management product compared to WhereHows. 

Unfortunately, we have to stop supporting WhereHows to better focus on DataHub and offer more help to DataHub users. Therefore, we will drop all issues related to WhereHows and will not accept any contribution for it. Active development for DataHub has already started on `datahub` branch and will continue to live in there until it's finally merged to master and project is renamed to DataHub. 

Please check the `datahub` branch to get familar with DataHub.

Best,
DataHub team
