### ISSUE TITLE
Build not completing while running (../gradlew runPlayBinary) in master branch

### ISSUE THREAD

**Issue by shantanusaini1395** [linkedin/WhereHows#1450]
Build process stuck on command "Waiting for changes to input files of tasks...".
![selection_012](https://user-images.githubusercontent.com/42576607/47633097-b721cb00-db72-11e8-8f47-ae29862fd8a4.png)

**Comment by jimmy-src** [comment]
用v1.0.0就没问题

#1457

加微信群讨论

**Comment by LightSunshine** [comment]
请问，这个问题解决了吗，我遇到了一样的问题

**Comment by keremsahin1** [comment]
Dear issue owner,

Thanks for your interest in WhereHows. We have recently announced DataHub which is the rebranding of WhereHows. LinkedIn improved the architecture of WhereHows and rebranded WhereHows into DataHub and replaced its metadata infrastructure in this direction. DataHub is a more advanced and improved metadata management product compared to WhereHows. 

Unfortunately, we have to stop supporting WhereHows to better focus on DataHub and offer more help to DataHub users. Therefore, we will drop all issues related to WhereHows and will not accept any contribution for it. Active development for DataHub has already started on `datahub` branch and will continue to live in there until it's finally merged to master and project is renamed to DataHub. 

Please check the `datahub` branch to get familar with DataHub.

Best,
DataHub team
