### ISSUE TITLE
VM Image File / Download Link

### ISSUE THREAD

**Issue by useracn** [linkedin/WhereHows#1451]
Greetings! I would like to know if we have other links to download the Wherehows VM file.
I tried the #2 instruction of "Steps to exploring the WhereHows application" since the cloudera vm image is not available, but we have issues logging in using LinkedIn account.

Also we have issues downloading also the wherehows vm file using the china link which it was blocked on our end.

Kindly advise if there are other ways to download the warehouse vm image file.

Thanks in advance :)

**Comment by useracn** [comment]
Hello xiao321. I manage to download the china link (using baidu). See details below:

1. You need to download a windows 10 VM. Select MS Edge of Windows 10 (file is around 5gb) 
 (https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/). I used the VMware Workstation 15 player.
2. You must create a baidu account in order to continue. If you are in overseas outside of china, you can create a baidu account with validation using your mobile number. Charges apply.
3. Access the baidu link using the Windows 10 VM as well as login thru the site.
4. When downloading file, you will be prompted to download their application to download the files.
5. When the application was installed, you are required to login using the baidu account. Afterwards, try to download each file to start downloading the files.

**Comment by xiao321** [comment]
i can download from baidu network disk. but i can not decompression. Indicates that the compressed package is damaged

**Comment by xiao321** [comment]
i can download the vm files from the baidu network disk. but i can not decompression . Indicates the compressed file broken.

**Comment by useracn** [comment]
You may try to re-download. I have actually storage issues where I can't complete the decompression of the files due to having 36gb left in my HD. I'm not sure but the extracted files may required 70+gb or more.

**Comment by useracn** [comment]
001 file should display the application icon (winzip,winrar,7z). My files successfully doing the extraction, except on my storage issues.

**Comment by xiao321** [comment]
oh, i know. i should download all file from 001 to 007 , put them together, then decompression

**Comment by useracn** [comment]
Thanks :). Do we have other ways to reach you out aside from wechat?
