### ISSUE TITLE
Schema History shows nothing

### ISSUE THREAD

**Issue by Ash-Mishra** [linkedin/WhereHows#1452]
Is this feature completed as i am not able to see anything under schema history? If i add data manually to dict_dataset_schema_history then i am able to se that data. In the whole project nowhere is any data inserted to dict_dataset_schema_history.
Is this feature complete? @czbernard

**Comment by jimmy-src** [comment]
The same to me...

解决了吗？分享一下哈

#1457

加微信群讨论

**Comment by jimmy-src** [comment]
insert into dict_dataset_schema_history(dataset_id,urn,modified_date,`schema`) select id as dataset_id, urn,  FROM_UNIXTIME(modified_time ) as modified_date, `schema` from dict_dataset where id > 0

And it works

**Comment by Ash-Mishra** [comment]
We are just adding straight to the database but there is no mentioning of adding to that table from the code. I was able to get the Schema history working in the same way but was not able to identify the flow of how the data values goes into the table

**Comment by Ash-Mishra** [comment]
I have got a solution for this. After every Etl job we want the schema history to be updated based on the data in dict_dataset.
I have added an extra function in the corresponding Load.py file for which you want the schema history.

Just use theis funtion in your load.py file

```def update_schema_history(self):
    update_schema_history_cmd = '''
    insert into
      dict_dataset_schema_history(dataset_id, urn, modified_date, `schema`)
    select
      id as dataset_id,
      urn,
      FROM_UNIXTIME(modified_time) as modified_date,
      `schema`
    from
      dict_dataset as s
    where
      s.id > 0
      and date(FROM_UNIXTIME(s.modified_time)) not in (
        select
          modified_date
        from
          dict_dataset_schema_history
        where
          urn = s.urn
      );
    
    
    update
      dict_dataset_schema_history
      inner join dict_dataset on (
        dict_dataset_schema_history.dataset_id = dict_dataset.id
        and dict_dataset_schema_history.modified_date = date(FROM_UNIXTIME(dict_dataset.modified_time))
      )
    set
      dict_dataset_schema_history.schema = dict_dataset.schema;
    '''
    self.logger.info(update_schema_history_cmd)
    self.executeCommands(update_schema_history_cmd)
    self.logger.info("finish updating schema history")```
