### ISSUE TITLE
WhereHows Extend/Expand Functionality

### ISSUE THREAD

**Issue by useracn** [linkedin/WhereHows#1455]
Hello. I would like to ask how can we expand or extend the current WhereHows functionality? Thanks in advance.

**Comment by Ash-Mishra** [comment]
We can add jobs and functionality for SQL server and MySql, which are similar to Oracle.
They have already created it for MySql but that part is not yet open source.
They might be releasing that in some later releases.

**Comment by useracn** [comment]
Thanks. It is possible to update also the front end UI design in case?

**Comment by keremsahin1** [comment]
Dear issue owner,

Thanks for your interest in WhereHows. We have recently announced DataHub which is the rebranding of WhereHows. LinkedIn improved the architecture of WhereHows and rebranded WhereHows into DataHub and replaced its metadata infrastructure in this direction. DataHub is a more advanced and improved metadata management product compared to WhereHows. 

Unfortunately, we have to stop supporting WhereHows to better focus on DataHub and offer more help to DataHub users. Therefore, we will drop all issues related to WhereHows and will not accept any contribution for it. Active development for DataHub has already started on `datahub` branch and will continue to live in there until it's finally merged to master and project is renamed to DataHub. 

Please check the `datahub` branch to get familar with DataHub.

Best,
DataHub team
