### ISSUE TITLE
建个微信群一起交流一下部署使用问题

### ISSUE THREAD

**Issue by YunKillerE** [linkedin/WhereHows#1457]
目前我在公司已经部署成功了1.0.0，已成功导入hive数据，导入ldap数据，导入azkaban数据
#1449 

但是界面很多地方都无法点击，没数据，不知道没开发好还是需要哪里配置
#1447 

希望大家一起交流一下经验，能成功在公司内部推广使用wherehows这个不错的元数据管理平台

直接扫描进群

![image](https://user-images.githubusercontent.com/12254857/49486273-b9193100-f878-11e8-8788-492c39596c15.png)

如果过期了直接加我，我拉你进群

![image](https://user-images.githubusercontent.com/12254857/48474163-eef86600-e834-11e8-8015-113ed90294ff.png)

**Comment by GOUYONGCHAO** [comment]
感觉没有linkin的人，很难弄。

**Comment by mrzhangboss** [comment]
已弃坑WherHows，官方文档不全，部署困难，而且感觉很久没有维护了，推荐Apache 的Atlas，已经到2.0.0版本，尝试安装了一下对Hive，Sqoop，Kafka支持都很棒，血缘关系也支持到列级别，而且相比WhereHows被动更新关系，Atlas使用钩子来动态更新，几乎准实时，而且部署起来也非常简单

**Comment by hanwangabc** [comment]
好啊




| |
a
|
|
邮箱：hanwangabc@126.com
|

Signature is customized by Netease Mail Master

在2019年05月16日 17:59，mrzhangboss 写道：

已弃坑WherHows，官方文档不全，部署困难，而且感觉很久没有维护了，推荐Apache 的Atlas，已经到2.0.0版本，尝试安装了一下对Hive，Sqoop，Kafka支持都很棒，血缘关系也支持到列级别，而且相比WhereHows被动更新关系，Atlas使用钩子来动态更新，几乎准实时，而且部署起来也非常简单

**Comment by springs101** [comment]
wherehows太辣鸡了，实在是没法用了，果断弃坑！

**Comment by feng-tao** [comment]
可以考虑https://github.com/lyft/amundsen

**Comment by feng-tao** [comment]
@YunKillerE 你这个微信群还ACTIVE吗，如果ACTIVE,能否拉下我进去？谢谢

**Comment by lonely7345** [comment]
> 可以考虑https://github.com/lyft/amundsen

看了一下，相当不错，打算体验一下

**Comment by keremsahin1** [comment]
Dear issue owner,

Thanks for your interest in WhereHows. We have recently announced DataHub which is the rebranding of WhereHows. LinkedIn improved the architecture of WhereHows and rebranded WhereHows into DataHub and replaced its metadata infrastructure in this direction. DataHub is a more advanced and improved metadata management product compared to WhereHows. 

Unfortunately, we have to stop supporting WhereHows to better focus on DataHub and offer more help to DataHub users. Therefore, we will drop all issues related to WhereHows and will not accept any contribution for it. Active development for DataHub has already started on `datahub` branch and will continue to live in there until it's finally merged to master and project is renamed to DataHub. 

Please check the `datahub` branch to get familar with DataHub.

Best,
DataHub team
