### ISSUE TITLE
Amazon AWS S3 configuration

### ISSUE THREAD

**Issue by useracn** [linkedin/WhereHows#1463]
Hello. I see in issue [#297](https://github.com/linkedin/WhereHows/issues/297) that amazon s3 datasets can be configured but wasn't sure where in the wherehows configuration can this be set. 

I'm pretty new to wherehows where I successfully build mysql databases and frontend and able to access wherehows UI, although I have no available data yet. I'm also still new to the backend/ETL configurations and trying my best to try on what available references available.

**Comment by shutianxu** [comment]
> Hello. I see in issue [#297](https://github.com/linkedin/WhereHows/issues/297) that amazon s3 datasets can be configured but wasn't sure where in the wherehows configuration can this be set.
> 
> I'm pretty new to wherehows where I successfully build mysql databases and frontend and able to access wherehows UI, although I have no available data yet. I'm also still new to the backend/ETL configurations and trying my best to try on what available references available.

Have you configured s3 datasets in wherehows? I meet same the problem.

**Comment by useracn** [comment]
Hello, I see a ticket somewhere that API setup approach is now deprecated. This is in connection to the configuration in issue 297. Currently I'm using oracle docker for the ETL.

**Comment by keremsahin1** [comment]
Dear issue owner,

Thanks for your interest in WhereHows. We have recently announced DataHub which is the rebranding of WhereHows. LinkedIn improved the architecture of WhereHows and rebranded WhereHows into DataHub and replaced its metadata infrastructure in this direction. DataHub is a more advanced and improved metadata management product compared to WhereHows. 

Unfortunately, we have to stop supporting WhereHows to better focus on DataHub and offer more help to DataHub users. Therefore, we will drop all issues related to WhereHows and will not accept any contribution for it. Active development for DataHub has already started on `datahub` branch and will continue to live in there until it's finally merged to master and project is renamed to DataHub. 

Please check the `datahub` branch to get familar with DataHub.

Best,
DataHub team
