### ISSUE TITLE
Is this poject dead?

### ISSUE THREAD

**Issue by thinking-aloud** [linkedin/WhereHows#1467]
Hi,
there were no commits for month, and I run into mayor issues with any of the install methods, hence the question:
Is WhereHows under active development?

**Comment by mars-lan** [comment]
We're currently developing the next generation of production which is significantly better. Please keep any eye out on future announcements.

**Comment by mars-lan** [comment]
We'll make announcement both on this repo and LinkedIn's engineering blog: https://engineering.linkedin.com/blog
