### ISSUE TITLE
Bad link in documentation wiki

### ISSUE THREAD

**Issue by drewsonne** [linkedin/WhereHows#1469]
No sure how to do a PR or edit a wiki on github, but there's a typo in https://github.com/LinkedIn/Wherehows/wiki at the very end of the page, as a part of 

> UI and API You can do all the above things by clicking through the UI. But if you want to use metadata to automate your application, you can also use the Backend API.

The link `https://github.com/LinkedIn/Wherehows/wiki#Backend-API` should be `https://github.com/LinkedIn/Wherehows/wiki/Backend-API`.

**Comment by mars-lan** [comment]
Thanks for reporting. The link has been fixed.
