### ISSUE TITLE
unable to setup

### ISSUE THREAD

**Issue by jojoho921** [linkedin/WhereHows#1470]
Attempted to set it up, but it failed at the building the gradle source code. Per log, Some codes are missing or out of date even with the latest git pull. Any suggestion to resolve this? 

> Task :wherehows-common:compileJava FAILED
Task ':wherehows-common:compileJava' is not up-to-date because:
  Task has failed previously.
All input files are considered out-of-date for incremental task ':wherehows-common:compileJava'.
Compiling with JDK Java compiler API.
:wherehows-common:compileJava (Thread[Task worker for ':',5,main]) completed. Took 0.189 secs.

**Comment by keremsahin1** [comment]
Dear issue owner,

Thanks for your interest in WhereHows. We have recently announced DataHub which is the rebranding of WhereHows. LinkedIn improved the architecture of WhereHows and rebranded WhereHows into DataHub and replaced its metadata infrastructure in this direction. DataHub is a more advanced and improved metadata management product compared to WhereHows. 

Unfortunately, we have to stop supporting WhereHows to better focus on DataHub and offer more help to DataHub users. Therefore, we will drop all issues related to WhereHows and will not accept any contribution for it. Active development for DataHub has already started on `datahub` branch and will continue to live in there until it's finally merged to master and project is renamed to DataHub. 

Please check the `datahub` branch to get familar with DataHub.

Best,
DataHub team
