### ISSUE TITLE
wherehows-web:emberBuild FAILED with SyntaxError: missing ) after argument list

### ISSUE THREAD

**Issue by mvankadari** [linkedin/WhereHows#1473]
Hi,

Can anyone please give a resolution for this issue? Attached the build log with error details from console.

[wherehows-web build log.txt](https://github.com/linkedin/WhereHows/files/2812132/wherehows-web.build.log.txt)

**Comment by zing000a** [comment]
I have the same problem,did you have solve this issus?

`basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':wherehows-web:emberBuild'.
> Process 'command 'D:\git\WhereHows\wherehows-web\build\nodejs\node-v8.12.0-win-x64\node.exe'' finished with non-zero exit value 1
`

**Comment by zing000a** [comment]
`sdfffffffffffff`

**Comment by keremsahin1** [comment]
Dear issue owner,

Thanks for your interest in WhereHows. We have recently announced DataHub which is the rebranding of WhereHows. LinkedIn improved the architecture of WhereHows and rebranded WhereHows into DataHub and replaced its metadata infrastructure in this direction. DataHub is a more advanced and improved metadata management product compared to WhereHows. 

Unfortunately, we have to stop supporting WhereHows to better focus on DataHub and offer more help to DataHub users. Therefore, we will drop all issues related to WhereHows and will not accept any contribution for it. Active development for DataHub has already started on `datahub` branch and will continue to live in there until it's finally merged to master and project is renamed to DataHub. 

Please check the `datahub` branch to get familar with DataHub.

Best,
DataHub team
