### ISSUE TITLE
Data truncation: Out of range value for column 'process_id' at row 1

### ISSUE THREAD

**Issue by zing000a** [linkedin/WhereHows#1478]
Hi,while getPid() method return -1,then update wh_etl_job_history excute
` UPDATE wh_etl_job_history SET process_id=-1, host_name=NULL WHERE wh_etl_exec_id =8;`
  will throws excption:

`SQL [UPDATE wh_etl_job_history SET process_id=?, host_name=? WHERE wh_etl_exec_id =?]; Data truncation: Out of range value for column 'process_id' at row 1; nested exception is com.mysql.jdbc.MysqlDataTruncation: Data truncation: Out of range value for column 'process_id' at row 1`

EtlJobActor.getPid() return -1;

**Comment by blouson** [comment]
wherehows can only run on linux platform.

**Comment by keremsahin1** [comment]
Dear issue owner,

Thanks for your interest in WhereHows. We have recently announced DataHub which is the rebranding of WhereHows. LinkedIn improved the architecture of WhereHows and rebranded WhereHows into DataHub and replaced its metadata infrastructure in this direction. DataHub is a more advanced and improved metadata management product compared to WhereHows. 

Unfortunately, we have to stop supporting WhereHows to better focus on DataHub and offer more help to DataHub users. Therefore, we will drop all issues related to WhereHows and will not accept any contribution for it. Active development for DataHub has already started on `datahub` branch and will continue to live in there until it's finally merged to master and project is renamed to DataHub. 

Please check the `datahub` branch to get familar with DataHub.

Best,
DataHub team
