### ISSUE TITLE
cannot download vm image

### ISSUE THREAD

**Issue by arthur78** [linkedin/WhereHows#1484]
Hi,

I cannot download the VM image mentioned in step #2 on https://github.com/linkedin/WhereHows/wiki/Quick-Start-With-VM.

"Download the all partitions of image in WhereHows. (If you are in China, download from here WhereHows china link )".

The first link https://linkedin.box.com/wherehows-demo-in-cloudera-vm doesn't work to me. I have neither a LinkedIn nor Box account. I tried to create a temporary Box account, but that didn't help – clicking the link now opened a page which says that the link is not available anymore.

I tried the China option, but this didn't work for me either. I'm not in China and don't have (cannot create) a Baidu account.

Is there a way to get links to the image files? I'd like to roll out your demo on my AWS EC2 box.

Thanks.

**Comment by useracn** [comment]
You can create a baidu overseas account:
https://passport.baidu.com/v2/?reg&u=http://pan.baidu.com&regType=1&tpl=netdisk&overseas=1

translate the page to english. On registration, refer to area code based on your originating country. It will register with your fone number for validation.

**Comment by keremsahin1** [comment]
Dear issue owner,

Thanks for your interest in WhereHows. We have recently announced DataHub which is the rebranding of WhereHows. LinkedIn improved the architecture of WhereHows and rebranded WhereHows into DataHub and replaced its metadata infrastructure in this direction. DataHub is a more advanced and improved metadata management product compared to WhereHows. 

Unfortunately, we have to stop supporting WhereHows to better focus on DataHub and offer more help to DataHub users. Therefore, we will drop all issues related to WhereHows and will not accept any contribution for it. Active development for DataHub has already started on `datahub` branch and will continue to live in there until it's finally merged to master and project is renamed to DataHub. 

Please check the `datahub` branch to get familar with DataHub.

Best,
DataHub team
