### ISSUE TITLE
docker backend rest endpoint not working

### ISSUE THREAD

**Issue by dibyaranjansahoo1988** [linkedin/WhereHows#1485]
Hi Team,

I am using wherehows v1.1.0 and I have started the backend using docker. I want to create dataset or see datasets using the rest endpoint but not getting proper response.

Test:
GET http://localhost:9200

resp:
{
    "name": "node-1",
    "cluster_name": "wherehow-elasticsearch",
    "cluster_uuid": "AHLi5aE0S6O3KpnUBp8AqA",
    "version": {
        "number": "5.5.1",
        "build_hash": "19c13d0",
        "build_date": "2017-07-18T20:44:24.823Z",
        "build_snapshot": false,
        "lucene_version": "6.6.0"
    },
    "tagline": "You Know, for Search"
}

req:
GET http://localhost:9200/dataset?datasetId=1 
resp:
{
    "error": {
        "root_cause": [
            {
                "type": "illegal_argument_exception",
                "reason": "request [/dataset] contains unrecognized parameter: [datasetId]"
            }
        ],
        "type": "illegal_argument_exception",
        "reason": "request [/dataset] contains unrecognized parameter: [datasetId]"
    },
    "status": 400
}

req:
POST http://localhost:9200/dataset
header: Content-Type application/json
body : {
  "name" : "DUMMY4",
  "urn" : "teradata:///DWH_TMP/DUMMY4",
  "schema" : "{\"name\": \"DUMMY\", \"fields\": [{\"accessCount\": null, \"lastAccessTime\": null, \"nullable\": \"Y\", \"format\": null, \"type\": \"INT\", \"maxByteLength\": 4, \"name\": \"DUMMY\", \"doc\": \"\"}]}",
  "properties" : "{\"storage_type\": \"View\", \"accessCount\": 2670, \"lastAccessTime\": null, \"sizeInMbytes\": null, \"referenceTables\": [\"DWH_DIM.DUMMY\"], \"viewSqlText\": \"REPLACE VIEW DWH_STG.DUMMY AS\nLOCKING ROW FOR ACCESS\n SELECT * \n   FROM DWH_DIM.DUMMY;\", \"createTime\": \"2015-03-06 10:43:58\", \"lastAlterTime\": \"2015-03-10 20:57:16\"}",
  "schema_type" : "JSON",
  "fields" :  "{\"DUMMY\": {\"type\": \"INT\", \"maxByteLength\": 4}}",
  "source" : "Teradata",
  "source_created_time" : null,
  "location_prefix" : "DWH_STG",
  "ref_dataset_urn" : null,
  "is_partitioned" : "Y",
  "sample_partition_full_path": null,
  "parent_name" : null,
  "storage_type" : null,
  "dataset_type" : null,
  "hive_serdes_class" : null
}

resp: 
No handler found for uri [/dataset] and method [POST]

am I using the correct end point ?
If yes, could you please explain what is the issue here and how to insert any data using backend.
 
I got these endpoint details from the below URL.
https://github.com/linkedin/wherehows/wiki/Backend-API#dataset-get

**Comment by keremsahin1** [comment]
Dear issue owner,

Thanks for your interest in WhereHows. We have recently announced DataHub which is the rebranding of WhereHows. LinkedIn improved the architecture of WhereHows and rebranded WhereHows into DataHub and replaced its metadata infrastructure in this direction. DataHub is a more advanced and improved metadata management product compared to WhereHows. 

Unfortunately, we have to stop supporting WhereHows to better focus on DataHub and offer more help to DataHub users. Therefore, we will drop all issues related to WhereHows and will not accept any contribution for it. Active development for DataHub has already started on `datahub` branch and will continue to live in there until it's finally merged to master and project is renamed to DataHub. 

Please check the `datahub` branch to get familar with DataHub.

Best,
DataHub team
