### ISSUE TITLE
Lineage POST api

### ISSUE THREAD

**Issue by planckiii** [linkedin/WhereHows#149]
Hi,
did you have some examples / detailed descriptions about Lineage POST api. 
Json presented in documentation: https://github.com/linkedin/WhereHows/wiki/Backend-API#lineage-post isn't self descriptive :)
There are three sections, where two have source_target_type described as "source" and last one is "destination". Thats unclear because it looks like some lineage source and data source.
Thanks in advance :)

**Comment by jerrybai2009** [comment]
The three sections are 3 different dataset, there are 2 options for "source_target_type", "source" and "target".
For the wiki page example, there is a job read data from datasets "/data/test-lineage-source" and "data/databases/abc/source1" then write data into "/data/test-lineage-target".

Does that answer your question?

Thanks!

**Comment by planckiii** [comment]
Thanks for response. It's now clear what is idea behind "source_target_type".
Unfortunatelly I have still problem loading some lineage, getting "{"return_code":404,"error_message":"Incorrect result size: expected 1, actual 0"}"

I wonder which keys could cause that error. 
Tested so far:
1. registered application and configured proper "app_id" while posting json
2. "app_name" is equal to "app_code"
3. flow_path - i'm not sure if it refer to some datasets / flows ?
4. "abstracted_object_name" = urn withount prefix and "full_object_name" = urn

Thanks for help :)

**Comment by planckiii** [comment]
You could close that issue - there were problem with connection string to DB for backend service - already everything works fine :)
