### ISSUE TITLE
Unable to access frontend Exception  java.sql.SQLException: Access denied for user 'wherehows'@'172.18.0.4' (using password: YES)

### ISSUE THREAD

**Issue by satishjb** [linkedin/WhereHows#1491]
wherehows-frontend_1       | java.sql.SQLException: Access denied for user 'wherehows'@'172.18.0.4' (using password: YES)
wherehows-frontend_1       | 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:964) ~[mysql-mysql-connector-java-5.1.44.jar:5.1.44]
wherehows-frontend_1       | 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973) ~[mysql-mysql-connector-java-5.1.44.jar:5.1.44]
wherehows-frontend_1       | 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909) ~[mysql-mysql-connector-java-5.1.44.jar:5.1.44]
wherehows-frontend_1       | 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:873) ~[mysql-mysql-connector-java-5.1.44.jar:5.1.44]
wherehows-frontend_1       | 	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1710) ~[mysql-mysql-connector-java-5.1.44.jar:5.1.44]
wherehows-frontend_1       | 	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1226) ~[mysql-mysql-connector-java-5.1.44.jar:5.1.44]
wherehows-frontend_1       | 	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2191) ~[mysql-mysql-connector-java-5.1.44.jar:5.1.44]
wherehows-frontend_1       | 	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2222) ~[mysql-mysql-connector-java-5.1.44.jar:5.1.44]
wherehows-frontend_1       | 	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2017) ~[mysql-mysql-connector-java-5.1.44.jar:5.1.44]
wherehows-frontend_1       | 	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:779) ~[mysql-mysql-connector-java-5.1.44.jar:5.1.44]
wherehows-frontend_1       | 	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47) ~[mysql-mysql-connector-java-5.1.44.jar:5.1.44]
wherehows-frontend_1       | 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_222]
wherehows-frontend_1       | 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_222]
wherehows-frontend_1       | 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_222]
wherehows-frontend_1       | 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_222]
wherehows-frontend_1       | 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[mysql-mysql-connector-java-5.1.44.jar:5.1.44]
wherehows-frontend_1       | 	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:389) ~[mysql-mysql-connector-java-5.1.44.jar:5.1.44]
wherehows-frontend_1       | 	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330) ~[mysql-mysql-connector-java-5.1.44.jar:5.1.44]
wherehows-frontend_1       | 	at com.mysql.jdbc.jdbc2.optional.MysqlDataSource.getConnection(MysqlDataSource.java:428) ~[mysql-mysql-connector-java-5.1.44.jar:5.1.44]
wherehows-frontend_1       | 	at com.mysql.jdbc.jdbc2.optional.MysqlDataSource.getConnection(MysqlDataSource.java:136) ~[mysql-mysql-connector-java-5.1.44.jar:5.1.44]
wherehows-frontend_1       | 	at com.mysql.jdbc.jdbc2.optional.MysqlDataSource.getConnection(MysqlDataSource.java:107) ~[mysql-mysql-connector-java-5.1.44.jar:5.1.44]
wherehows-frontend_1       | 	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:365) ~[com.zaxxer-HikariCP-2.7.8.jar:na]
wherehows-frontend_1       | 	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:194) ~[com.zaxxer-HikariCP-2.7.8.jar:na]
wherehows-frontend_1       | 	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:460) [com.zaxxer-HikariCP-2.7.8.jar:na]
wherehows-frontend_1       | 	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:534) [com.zaxxer-HikariCP-2.7.8.jar:na]
wherehows-frontend_1       | 	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115) [com.zaxxer-HikariCP-2.7.8.jar:na]
wherehows-frontend_1       | 	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81) [com.zaxxer-HikariCP-2.7.8.jar:na]
wherehows-frontend_1       | 	at com.zaxxer.hikari.hibernate.HikariConnectionProvider.configure(HikariConnectionProvider.java:87) [com.zaxxer-HikariCP-2.7.8.jar:na]
wherehows-frontend_1       | 	at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.configureService(StandardServiceRegistryImpl.java:94) [org.hibernate-hibernate-core-5.2.16.Final.jar:5.2.16.Final]
wherehows-frontend_1       | 	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:242) [org.hibernate-hibernate-core-5.2.16.Final.jar:5.2.16.Final]
wherehows-frontend_1       | 	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:210) [org.hibernate-hibernate-core-5.2.16.Final.jar:5.2.16.Final]
wherehows-frontend_1       | 	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.buildJdbcConnectionAccess(JdbcEnvironmentInitiator.java:145) [org.hibernate-hibernate-core-5.2.16.Final.jar:5.2.16.Final]
wherehows-frontend_1       | 	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:66) [org.hibernate-hibernate-core-5.2.16.Final.jar:5.2.16.Final]
wherehows-frontend_1       | 	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:35) [org.hibernate-hibernate-core-5.2.16.Final.jar:5.2.16.Final]
wherehows-frontend_1       | 	at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.initiateService(StandardServiceRegistryImpl.java:88) [org.hibernate-hibernate-core-5.2.16.Final.jar:5.2.16.Final]
wherehows-frontend_1       | 	at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:259) [org.hibernate-hibernate-core-5.2.16.Final.jar:5.2.16.Final]
wherehows-frontend_1       | 	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:233) [org.hibernate-hibernate-core-5.2.16.Final.jar:5.2.16.Final]
wherehows-frontend_1       | 	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:210) [org.hibernate-hibernate-core-5.2.16.Final.jar:5.2.16.Final]
wherehows-frontend_1       | 	at org.hibernate.engine.jdbc.internal.JdbcServicesImpl.configure(JdbcServicesImpl.java:51) [org.hibernate-hibernate-core-5.2.16.Final.jar:5.2.16.Final]
wherehows-frontend_1       | 	at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.configureService(StandardServiceRegistryImpl.java:94) [org.hibernate-hibernate-core-5.2.16.Final.jar:5.2.16.Final]
wherehows-frontend_1       | 	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:242) [org.hibernate-hibernate-core-5.2.16.Final.jar:5.2.16.Final]
wherehows-frontend_1       | 	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:210) [org.hibernate-hibernate-core-5.2.16.Final.jar:5.2.16.Final]
wherehows-frontend_1       | 	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.handleTypes(MetadataBuildingProcess.java:352) [org.hibernate-hibernate-core-5.2.16.Final.jar:5.2.16.Final]
wherehows-frontend_1       | 	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:111) [org.hibernate-hibernate-core-5.2.16.Final.jar:5.2.16.Final]
wherehows-frontend_1       | 	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.metadata(EntityManagerFactoryBuilderImpl.java:861) [org.hibernate-hibernate-core-5.2.16.Final.jar:5.2.16.Final]
wherehows-frontend_1       | 	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:888) [org.hibernate-hibernate-core-5.2.16.Final.jar:5.2.16.Final]
wherehows-frontend_1       | 	at org.hibernate.jpa.HibernatePersistenceProvider.createEntityManagerFactory(HibernatePersistenceProvider.java:58) [org.hibernate-hibernate-core-5.2.16.Final.jar:5.2.16.Final]
wherehows-frontend_1       | 	at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:55) [org.hibernate.javax.persistence-hibernate-jpa-2.1-api-1.0.0.Final.jar:1.0.0.Final]
wherehows-frontend_1       | 	at wherehows.dao.ConnectionPoolProperties.buildEntityManagerFactory(ConnectionPoolProperties.java:64) [wherehows-dao-wherehows-dao.jar:na]
wherehows-frontend_1       | 	at controllers.Application.<clinit>(Application.java:131) [wherehows-frontend.jar:na]
wherehows-frontend_1       | 	at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$1$$anonfun$apply$1.apply(Routes.scala:2358) [wherehows-frontend.jar:na]
wherehows-frontend_1       | 	at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$1$$anonfun$apply$1.apply(Routes.scala:2358) [wherehows-frontend.jar:na]
wherehows-frontend_1       | 	at play.core.routing.HandlerInvokerFactory$$anon$4.resultCall(HandlerInvoker.scala:136) [com.typesafe.play-play_2.11-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at play.core.routing.HandlerInvokerFactory$JavaActionInvokerFactory$$anon$14$$anon$3$$anon$1.invocation(HandlerInvoker.scala:127) [com.typesafe.play-play_2.11-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:70) [com.typesafe.play-play_2.11-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at play.http.DefaultHttpRequestHandler$1.call(DefaultHttpRequestHandler.java:20) [com.typesafe.play-play_2.11-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at play.core.j.JavaAction$$anonfun$7.apply(JavaAction.scala:94) [com.typesafe.play-play_2.11-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at play.core.j.JavaAction$$anonfun$7.apply(JavaAction.scala:94) [com.typesafe.play-play_2.11-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) [org.scala-lang-scala-library-2.11.6.jar:na]
wherehows-frontend_1       | 	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) [org.scala-lang-scala-library-2.11.6.jar:na]
wherehows-frontend_1       | 	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:40) [com.typesafe.play-play_2.11-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:70) [com.typesafe.play-play-iteratees_2.11-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at play.core.j.HttpExecutionContext.execute(HttpExecutionContext.scala:32) [com.typesafe.play-play_2.11-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at scala.concurrent.impl.Future$.apply(Future.scala:31) [org.scala-lang-scala-library-2.11.6.jar:na]
wherehows-frontend_1       | 	at scala.concurrent.Future$.apply(Future.scala:492) [org.scala-lang-scala-library-2.11.6.jar:na]
wherehows-frontend_1       | 	at play.core.j.JavaAction.apply(JavaAction.scala:94) [com.typesafe.play-play_2.11-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:105) [com.typesafe.play-play_2.11-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:105) [com.typesafe.play-play_2.11-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at play.utils.Threads$.withContextClassLoader(Threads.scala:21) [com.typesafe.play-play_2.11-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:104) [com.typesafe.play-play_2.11-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:103) [com.typesafe.play-play_2.11-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at scala.Option.map(Option.scala:146) [org.scala-lang-scala-library-2.11.6.jar:na]
wherehows-frontend_1       | 	at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:103) [com.typesafe.play-play_2.11-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:96) [com.typesafe.play-play_2.11-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:524) [com.typesafe.play-play-iteratees_2.11-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:524) [com.typesafe.play-play-iteratees_2.11-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:560) [com.typesafe.play-play-iteratees_2.11-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:560) [com.typesafe.play-play-iteratees_2.11-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$13.apply(Iteratee.scala:536) [com.typesafe.play-play-iteratees_2.11-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$13.apply(Iteratee.scala:536) [com.typesafe.play-play-iteratees_2.11-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) [org.scala-lang-scala-library-2.11.6.jar:na]
wherehows-frontend_1       | 	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) [org.scala-lang-scala-library-2.11.6.jar:na]
wherehows-frontend_1       | 	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40) [com.typesafe.akka-akka-actor_2.11-2.3.13.jar:na]
wherehows-frontend_1       | 	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [com.typesafe.akka-akka-actor_2.11-2.3.13.jar:na]
wherehows-frontend_1       | 	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [org.scala-lang-scala-library-2.11.6.jar:na]
wherehows-frontend_1       | 	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [org.scala-lang-scala-library-2.11.6.jar:na]
wherehows-frontend_1       | 	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [org.scala-lang-scala-library-2.11.6.jar:na]
wherehows-frontend_1       | 	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [org.scala-lang-scala-library-2.11.6.jar:na]
wherehows-frontend_1       | 2019-07-28 16:57:20 ERROR a.a.ActorSystemImpl:66 - Uncaught fatal error from thread [application-akka.actor.default-dispatcher-5] shutting down ActorSystem [application]
wherehows-frontend_1       | java.lang.ExceptionInInitializerError: null

**Comment by satishjb** [comment]
is this project active

**Comment by hangzhang925** [comment]
> is this project active

Please move your `issue` to questions,  PR is not a place for submitting issues and you are not sending this issue to anyone, just yourself and people who `subscribed` this project.

**Comment by keremsahin1** [comment]
Dear issue owner,

Thanks for your interest in WhereHows. We have recently announced DataHub which is the rebranding of WhereHows. LinkedIn improved the architecture of WhereHows and rebranded WhereHows into DataHub and replaced its metadata infrastructure in this direction. DataHub is a more advanced and improved metadata management product compared to WhereHows. 

Unfortunately, we have to stop supporting WhereHows to better focus on DataHub and offer more help to DataHub users. Therefore, we will drop all issues related to WhereHows and will not accept any contribution for it. Active development for DataHub has already started on `datahub` branch and will continue to live in there until it's finally merged to master and project is renamed to DataHub. 

Please check the `datahub` branch to get familar with DataHub.

Best,
DataHub team
