### ISSUE TITLE
wherehows-backend Command exited with error: exit status 1

### ISSUE THREAD

**Issue by satishjb** [linkedin/WhereHows#1492]
wherehows-mysql_1     | Version: '5.6.45'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server (GPL)
wherehows-frontend_1  | NettyServer.main is deprecated. Please start your Play server with the ${ProdServerStart.getClass.getName}.main.
wherehows-backend_1   | NettyServer.main is deprecated. Please start your Play server with the ${ProdServerStart.getClass.getName}.main.
wherehows-backend_1   **| Exception in thread "main" java.lang.NoSuchMethodError: scala.Predef$.ArrowAssoc(Ljava/lang/Object;)Ljava/lang/Object;**
wherehows-backend_1   | 	at play.api.Logger$.configure(Logger.scala:209)
wherehows-backend_1   | 	at play.api.inject.guice.GuiceApplicationBuilder.applicationModule(GuiceApplicationBuilder.scala:73)
wherehows-backend_1   | 	at play.api.inject.guice.GuiceBuilder.injector(GuiceInjectorBuilder.scala:126)
wherehows-backend_1   | 	at play.api.inject.guice.GuiceApplicationBuilder.build(GuiceApplicationBuilder.scala:93)
wherehows-backend_1   | 	at play.api.inject.guice.GuiceApplicationLoader.load(GuiceApplicationLoader.scala:21)
wherehows-backend_1   | 	at play.core.server.ProdServerStart$.start(ProdServerStart.scala:52)
wherehows-backend_1   | 	at play.core.server.ProdServerStart$.main(ProdServerStart.scala:27)
wherehows-backend_1   | 	at play.core.server.NettyServer$.main(NettyServer.scala:230)
wherehows-backend_1   | 	at play.core.server.NettyServer.main(NettyServer.scala)
wherehows-backend_1   | 2019/08/06 17:25:17 Command exited with error: exit status 1

**Comment by keremsahin1** [comment]
Dear issue owner,

Thanks for your interest in WhereHows. We have recently announced DataHub which is the rebranding of WhereHows. LinkedIn improved the architecture of WhereHows and rebranded WhereHows into DataHub and replaced its metadata infrastructure in this direction. DataHub is a more advanced and improved metadata management product compared to WhereHows. 

Unfortunately, we have to stop supporting WhereHows to better focus on DataHub and offer more help to DataHub users. Therefore, we will drop all issues related to WhereHows and will not accept any contribution for it. Active development for DataHub has already started on `datahub` branch and will continue to live in there until it's finally merged to master and project is renamed to DataHub. 

Please check the `datahub` branch to get familar with DataHub.

Best,
DataHub team
