### ISSUE TITLE
Missing DDLs for tables added in #146

### ISSUE THREAD

**Issue by rkluszczynski** [linkedin/WhereHows#150]
Hello, 
I have updated code to latest version today and there are missing DDLs in data-model for new tables added dataset dependency api (#146). I mean here tables used in Hive ETL job:

- cfg_object_name_map
- dict_dataset_instance
- stg_cfg_object_name_map
- stg_dict_dataset_instance

Could you provide them, please? 

At the moment I have got error:

> ERROR jython script : HiveLoad:-2 - Table 'wherehows.stg_dict_dataset_instance' doesn't exist [SQLCode: 1146], [SQLState: 42S02]

Kind regards,
Rafal Kluszczynski

**Comment by ericsun2** [comment]
@rkluszczynski 
DDL files have been synced in master

**Comment by rkluszczynski** [comment]
Thanks!
