### ISSUE TITLE
How I can login this page at frontend?I try to use sql.And user_login_histry table tells me I login success.But page and log tell me throws a exception.

### ISSUE THREAD

**Issue by EverRoads** [linkedin/WhereHows#1505]

**Comment by EverRoads** [comment]
![后台报错1](https://user-images.githubusercontent.com/36840761/66804067-116a9600-ef54-11e9-9cba-f24298eb9c06.png)
![后台报错2](https://user-images.githubusercontent.com/36840761/66804068-12032c80-ef54-11e9-9833-31d3f7e2bab2.png)
![微信截图_20191015135943](https://user-images.githubusercontent.com/36840761/66804069-129bc300-ef54-11e9-87c3-292aa8a703b4.png)

**Comment by EverRoads** [comment]
![微信截图_20191015140214](https://user-images.githubusercontent.com/36840761/66804205-71f9d300-ef54-11e9-824c-ced2b960c32e.png)
I can konw what I login success。

**Comment by keremsahin1** [comment]
Dear issue owner,

Thanks for your interest in WhereHows. We have recently announced DataHub which is the rebranding of WhereHows. LinkedIn improved the architecture of WhereHows and rebranded WhereHows into DataHub and replaced its metadata infrastructure in this direction. DataHub is a more advanced and improved metadata management product compared to WhereHows. 

Unfortunately, we have to stop supporting WhereHows to better focus on DataHub and offer more help to DataHub users. Therefore, we will drop all issues related to WhereHows and will not accept any contribution for it. Active development for DataHub has already started on `datahub` branch and will continue to live in there until it's finally merged to master and project is renamed to DataHub. 

Please check the `datahub` branch to get familar with DataHub.

Best,
DataHub team
