### ISSUE TITLE
Issue with ./gradlew build

### ISSUE THREAD

**Issue by RDDOUB** [linkedin/WhereHows#151]
I went to install WhereHows on a new server following the same instructions I used for an old server and I'm now getting errors like below when I do a gradle build. It looks like there were some code updates in github in the last week, but I don't see where it's related to these errors. Any thoughts???

[error] /home/ubuntu/WhereHows/backend-service/app/msgs/EtlJobMessage.java:18: object metadata is not a member of package <root>
[error] import metadata.etl.models.EtlJobName;
[error]        ^
[error] /home/ubuntu/WhereHows/backend-service/app/msgs/EtlJobMessage.java:35: not found: type EtlJobName
[error]   public EtlJobMessage(EtlJobName etlJobName, EtlType etlType, Integer whEtlJobId, Integer refId, RefIdType refIdType, String cmdParam) {
[error]                        ^
[error] /home/ubuntu/WhereHows/backend-service/app/msgs/EtlJobMessage.java:17: object metadata is not a member of package <root>
[error] import metadata.etl.models.EtlType;
[error]        ^
[error] /home/ubuntu/WhereHows/backend-service/app/msgs/EtlJobMessage.java:35: not found: type EtlType
[error]   public EtlJobMessage(EtlJobName etlJobName, EtlType etlType, Integer whEtlJobId, Integer refId, RefIdType refIdType, String cmdParam) {
[error]                                               ^
[error] /home/ubuntu/WhereHows/backend-service/app/msgs/EtlJobMessage.java:19: object metadata is not a member of package <root>
[error] import metadata.etl.models.RefIdType;

**Comment by jerrybai2009** [comment]
We just fixed this problem. 
Please get the latest code and try again.

Thanks!

**Comment by RDDOUB** [comment]
that worked, thanks
