### ISSUE TITLE
Docker Quickstart - Can't bootstrap sample data

### ISSUE THREAD

**Issue by PieterJanVanAeken** [linkedin/WhereHows#1510]
I am following the bootstrapping guide, but I cannot get the data import to work. The events are published onto Kafka and consumed by the MCE consumer but the call to the GMS fails with a 503 error. Looking at the GMS logs, it seems like its not loading the DAO's correctly?

`org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'restliRequestHandler' defined in ServletContext resource [/WEB-INF/beans.xml]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.linkedin.restli.server.spring.ParallelRestliHttpRequestHandler]: Constructor threw exception; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'corpGroupSearchDAO' available`

Any help would be greatly appreciated.

**Comment by keremsahin1** [comment]
Hi @PieterJanVanAeken ,

Thanks for your interest in Data Hub. This is a bug introduced with the latest changeset yesterday. I've already pushed a fix for that https://github.com/linkedin/WhereHows/commit/c766165b84987b60732ed900e71dc8f6ddbeeead.

But please do understand that, there will be sometime required to generate new Docker images in Docker Hub.

**Comment by PieterJanVanAeken** [comment]
No worries, it is alpha software after all ;)

Now that I know how to fix it, I'll just build the images myself. Thanks for the help!

**Comment by keremsahin1** [comment]
Thanks @PieterJanVanAeken. `latest` tagged Docker containers should work right now.
