### ISSUE TITLE
Problem about import mysql table

### ISSUE THREAD

**Issue by jiajie999** [linkedin/WhereHows#1514]
I have done the bootstrapping and example under dir mce-cli works fine.
But when I use the script `mysql_etl.py` under `WhereHows/metadata-ingestion/mysql-etl` to import a test table from MySQL, I got a table without schema.

![empty_schme](https://user-images.githubusercontent.com/1141716/70323172-17e80080-1867-11ea-8007-671a518dadbb.png)

**Comment by RealChrisL** [comment]
Hi @jiajie999, thanks for dropping by the Data Hub, 

As for the metadata ingestion ETLs, those are intended to provide a generic layer to demonstrate the compatibility of Data Hub with various platform types. So to speak, some metadata information in the `metadatachangeevent` will be ad-hoc on your scenario.

In the latest patch, you will be able to play with primitive metadata, strongly recommending to start with database metadata in MySQL the `INFORMATION_SCHEMA` to figure out what the ETL can be leveraged and extending it to your storyline.

Have a wonderful exploration and feel free to let us know if you have any questions!

Chris

**Comment by jiajie999** [comment]
It's working after your commit. Great job!
Thanks!

**Comment by animeshinvinci** [comment]
@RealChrisL  as I know this issue closed. but I am also facing similar issue. please let me know what was the fix?
