### ISSUE TITLE
pdsc and avsc have different definition for same field.

### ISSUE THREAD

**Issue by clojurians-org** [linkedin/WhereHows#1533]
as i know, avsc file is generated from pdsc.
but when i check the schema, i find the two file has different definition for same field[urn].
so i can't get concrete field refinement from avro file only.

avro format:
```
./metadata-events/mxe-schemas/src/renamed/avro/com/linkedin/mxe/MetadataChangeEvent.avsc
the [proposedSnapshot :> DatasetSnapshot :> urn] has "string" type.
```

pdsc format
```
./metadata-models/src/main/pegasus/com/linkedin/mxe/MetadataChangeEvent.pdsc
urn => com.linkedin.common.DatasetUrn

./li-utils/src/main/pegasus/com/linkedin/common/DatasetUrn.pdsc
urn.platform => string
urn.datasetName => string
urn.origin => enum ["DEV", "EI", "PROD", "CORP", "LIT", "PRIME", "MANDA", "AZURECONTROL", "AZUREPROD", "AZUREEI"]
```

**Comment by keremsahin1** [comment]
Hi @clojurians-org 
`DatasetUrn`, like any other Urn provided in `li-utils` is essentially a typeref to `String`. Please check below link for `typeref`s in Pegasus.
https://linkedin.github.io/rest.li/DATA-Data-Schema-and-Templates#typeref

**Comment by mars-lan** [comment]
Assuming the question has been answered. Let us know otherwise.

**Comment by geosmart** [comment]
> Hi @clojurians-org
> `DatasetUrn`, like any other Urn provided in `li-utils`, is essentially a typeref to `String`. Please check below link for `typeref`s in Pegasus.
> [linkedin.github.io/rest.li/DATA-Data-Schema-and-Templates#typeref](https://linkedin.github.io/rest.li/DATA-Data-Schema-and-Templates#typeref)

link broken 
try [DATA-Data-Schema-and-Templates](https://github.com/linkedin/rest.li/wiki/DATA-Data-Schema-and-Templates)
