### ISSUE TITLE
Question about URN validation in endpoint GET:/dataset

### ISSUE THREAD

**Issue by rkluszczynski** [linkedin/WhereHows#160]
Hello,
we have one question about endpoint **GET:/dataset**. When asking with urn query parameter, it is validated against storage types hardcoded in line: https://github.com/linkedin/WhereHows/blob/master/backend-service/app/models/utils/Urn.java#L31.

Is there particular reason why it is only **teradata** and **hdfs**?

I'm asking because we are adding our type of storage (**Hermes**, http://hermes-pubsub.readthedocs.io/en/latest/) and we are trying to feed lineage information. We want to do it by API, and when asking about dataset we are now getting "**Urn format wrong!**" ;-( 

I want to move that into configuration file, but before that I want to make sure if it is OK with you:)
I would appreciate any thoughts and remarks.

Kind regards,
Rafal Kluszczynski

**Comment by ericsun2** [comment]
Hi @rkluszczynski, we will fix this and allow all **dataset_type**(s) in dict_dataset.
