### ISSUE TITLE
DDL execute fail

### ISSUE THREAD

**Issue by foojolt** [linkedin/WhereHows#201]
Sql syntax error in file:  WhereHows/data-model/DDL/ETL_DDL/kafka_tracking.sql

line 148, missing comma:  

PRIMARY KEY(dataset_id,db_id,data_time_epoch,partition_grain,partition_expr)

Did you ever try execute the DDL after modify the sql?

**Comment by alyiwang** [comment]
It's fixed in #202. Thanks!
