### ISSUE TITLE
MissingRequirementError: object scala.runtime in compiler mirror not found

### ISSUE THREAD

**Issue by sunny1978** [linkedin/WhereHows#210]
scala.reflect.internal.MissingRequirementError: object scala.runtime in compiler mirror not found

:backend-service:playCompile
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=512M; support was removed in 8.0
[info] Loading project definition from /home/conflux/WhereHows/backend-service/project
[info] Set current project to backend-service (in build file:/home/conflux/WhereHows/backend-service/)
[info] Updating {file:/home/conflux/WhereHows/backend-service/}backend-service...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Compiling 4 Scala sources and 37 Java sources to /home/conflux/WhereHows/backend-service/target/scala-2.10/classes...
[error] error while loading <root>, error in opening zip file
scala.reflect.internal.MissingRequirementError: object scala.runtime in compiler mirror not found.
	at scala.reflect.internal.MissingRequirementError$.signal(MissingRequirementError.scala:16)
	at scala.reflect.internal.MissingRequirementError$.notFound(MissingRequirementError.scala:17)

My Env:
CentOS 6
JDK 1.8
User: usera (with sudo access). However ran it with just "gradle build". Should I do "sudo gradle build" ?

**Comment by sunny1978** [comment]
I have tried same steps - but as a "root" user on CentOS6, JDK1.8. Saw same set of errors

#1:
A problem occurred evaluating project ':backend-service'.
> Could not find method module() for arguments [org.slf4j:slf4j-log4j12] on org.gradle.api.internal.artifacts.ivyservice.resolutionstrategy.DefaultResolutionStrategy_Decorated@4ce267cc.

Fix: Went to each build file and commented out the slf4j line. All projects

#2: Above Error.
However after running as "root" - this is gone

#3:
[info] downloading http://repo1.maven.org/maven2/org/xerial/snappy/snappy-java/1.1.2.4/snappy-java-1.1.2.4.jar ...
[info] 	[SUCCESSFUL ] org.xerial.snappy#snappy-java;1.1.2.4!snappy-java.jar(bundle) (110ms)
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::              FAILED DOWNLOADS            ::
[warn] 	:: ^ see resolution messages for details  ^ ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: commons-logging#commons-logging;1.1.3!commons-logging.jar
[warn] 	:: jline#jline;0.9.94!jline.jar
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
sbt.ResolveException: download failed: commons-logging#commons-logging;1.1.3!commons-logging.jar
download failed: jline#jline;0.9.94!jline.jar

Tried - But No luck: Added following in WhereHows/build.gradle
to external dependencies
commons-logging:commons-logging:1.1.3
jline:jline:0.9.94

Went past the issue - but then ran in to above listed 
"scala.reflect.internal.MissingRequirementError: object scala.runtime in compiler mirror not found"

**Comment by sunny1978** [comment]
Same process compiled fine in Mac OSX El Capitan.
Note: I still have to comment out the slf4j12 part.

**Comment by PettterPan** [comment]
do u have idea to sloving this problem , share to me ,thx
