### ISSUE TITLE
which branch  is the latest stable release version?

### ISSUE THREAD

**Issue by superwood** [linkedin/WhereHows#218]
which branch  is the latest stable release version?

**Comment by ericsun2** [comment]
Please use master branch

**Comment by superwood** [comment]
Which  version can work well . I find out serval version in master branch  uses  different   mysql table schemal !

**Comment by ericsun2** [comment]
@superwood the latest version is "master" is working.
Please kindly report the mismatch in MySql DDL, we will address such issues immediately.

**Comment by mars-lan** [comment]
We have only one branch now (master), with each stable release is tagged
