### ISSUE TITLE
whether WhereHows support DB2/Oracle/Postgres data sources or not?

### ISSUE THREAD

**Issue by xumwdb2** [linkedin/WhereHows#228]
We want to choose WhereHows  as metadata tool at one datawarehouse project,  could you please whether WhereHows can support relational databases, such as DB2/Postgress data source? 

Thank a lot.

**Comment by ericsun2** [comment]
@xumwdb2 if you take a look at the existing metadata ETL code for [Teradata](https://github.com/linkedin/WhereHows/blob/master/metadata-etl/src/main/resources/jython/TeradataExtract.py) and [Oracle](https://github.com/linkedin/WhereHows/blob/master/metadata-etl/src/main/resources/jython/OracleExtract.py), you will probably make the DB2/Postgress pipeline with little extra effort.

You can setup the proper connection parameters in wh_etl_job and wh_etl_job_property and [EtlJobName.java](https://github.com/linkedin/WhereHows/blob/master/metadata-etl/src/main/java/metadata/etl/models/EtlJobName.java)
