### ISSUE TITLE
wherehows项目是否支持字段级别的追溯?

### ISSUE THREAD

**Issue by wmky** [linkedin/WhereHows#238]
希望能够得到表与表之间的字段的血缘关系,目前刚接触,所以提前来问问.谢谢

**Comment by SunZhaonan** [comment]
目前不支持
字段间的血缘关系，靠目前的从日志中获取信息的逆向工程方式几乎是不可行的。
要想得到这种更加底层的血缘信息，需要在执行引擎中加入嵌入部件，作业执行时，使用推送模式把这些信息送入血缘关系收集系统。
例如在Hive execution hook 里就可以收集字段间的血缘关系。（参考cloudera navigator)
但是对于执行引擎不开源或者嵌入式架构不够灵活的数据处理系统来说，想拿到他们的这种级别的血统就更难了。目前还没有更好的办法。

**Comment by wmky** [comment]
谢谢您的及时回复，基于这样情况，我们准备考虑二次开发，预计得调研一段时间。我是互联网电商大数据的，准备做个元数据系统，所以先看看能否二次开发实现想要的功能。对了，额外请教您一个问题，关于dataset和operation data是如何插入到系统的，因为发现wherehows系统界面并不能插入数据集的表和字段等。我目前也是在调研这个项目的阶段。谢谢.

**Comment by lisongfeng9213** [comment]
我们这边也想做字段级别的血缘关系。在考虑解析Hive sql 来做这个，但感觉略困难。

**Comment by ericsun2** [comment]
WhereHows can add the import schema feature:
- import schema from file (avro schema json, hive/oracle/teradata/mysql DDL, thrift idl...)
- import schema from a location (hdfs path, hive table) if WhereHows can use the same user login to connect to the live data system

The operational metadata can be ingested via Kafka event topics, we are adding job execution lineage right now.

In terms of field-level lineage, it will require deep integration with the execution engine, such as Hive, Spark. We will update the progress for Hive AST based attempt later.

**Comment by AristocratW** [comment]
Hi ericsun2,
I'm wondering if the fearure you said had already been made?

**Comment by keremsahin1** [comment]
Dear issue owner,

Thanks for your interest in WhereHows. We have recently announced DataHub which is the rebranding of WhereHows. LinkedIn improved the architecture of WhereHows and rebranded WhereHows into DataHub and replaced its metadata infrastructure in this direction. DataHub is a more advanced and improved metadata management product compared to WhereHows. 

Unfortunately, we have to stop supporting WhereHows to better focus on DataHub and offer more help to DataHub users. Therefore, we will drop all issues related to WhereHows and will not accept any contribution for it. Active development for DataHub has already started on `datahub` branch and will continue to live in there until it's finally merged to master and project is renamed to DataHub. 

Please check the `datahub` branch to get familar with DataHub.

Best,
DataHub team
