### ISSUE TITLE
Class path contains multiple SLF4J bindings #155

### ISSUE THREAD

**Issue by superwood** [linkedin/WhereHows#260]
I have the same issue with branch master and commit commit 753de7d .

Has the problem been solved yet？

**Comment by alyiwang** [comment]
@superwood Could you try using the latest commit after we upgrade to play 2.4.8, and let us know if the issue still exists.

You can follow the new installation [root/README.md](https://github.com/linkedin/WhereHows/blob/master/README.md) instruction for that.

**Comment by alyiwang** [comment]
We are aware of the "multiple SLF4J bindings" warnings during program start-up. A ticket has been created for further investigation.

**Comment by keremsahin1** [comment]
Dear issue owner,

Thanks for your interest in WhereHows. We have recently announced DataHub which is the rebranding of WhereHows. LinkedIn improved the architecture of WhereHows and rebranded WhereHows into DataHub and replaced its metadata infrastructure in this direction. DataHub is a more advanced and improved metadata management product compared to WhereHows. 

Unfortunately, we have to stop supporting WhereHows to better focus on DataHub and offer more help to DataHub users. Therefore, we will drop all issues related to WhereHows and will not accept any contribution for it. Active development for DataHub has already started on `datahub` branch and will continue to live in there until it's finally merged to master and project is renamed to DataHub. 

Please check the `datahub` branch to get familar with DataHub.

Best,
DataHub team
