### ISSUE TITLE
Get "KeyError: projectName"  when   running  "AzkabanExtract.py collect_flow_execs" function. 

### ISSUE THREAD

**Issue by superwood** [linkedin/WhereHows#262]
The flow_data   selected  from azkaban db. execution_flows  do not has a json field "projectName" but  "projectId".

{"executionOptions":{"failureAction":"FINISH_CURRENTLY_RUNNING","queueLevel":0,"pipelineExecId":null,"concurrentOption":"skip","notifyOnFirstFailure":true,"notifyOnLastFailure":true,"pipelineLevel":null,"successEmailsOverride":false,"failureEmails":["ben@mobvista.com"],"disabled":[],"flowParameters":{"ScheduleTime":"2016-11-01 19:36:00"},"successEmails":[],"mailCreator":"default","failureEmailsOverride":true},"type":"executableflow","version":16,"executionPath":"executions/113070","executionId":113070,"submitTime":-1,"nodes":[{"paused":false,"level":3,"jobSource":"notice_log/finish_notice.job","updateTime":1478001109904,"externalExecutionId":null,"inNodes":["etl_notice_agentapi_request_exception","etl_notice_agentapi_click_exception","etl_notice_request_exception_seriveice_init","elt_notice_request_exception_return_empty"],"outNodes":[],"propSource":null,"startTime":1478001109798,"id":"finish_notice","endTime":1478001109868,"jobType":"command","status":"SUCCEEDED"},{"paused":false,"level":1,"jobSource":"notice_log/etl_notice_click_impression_exception.job","updateTime":1478000822403,"externalExecutionId":null,"inNodes":["st_notice_all"],"outNodes":["etl_notice_agentapi_request_exception","etl_notice_agentapi_click_exception"],"propSource":null,"startTime":1478000392251,"id":"etl_notice_click_impression_exception","endTime":1478000822351,"jobType":"command","status":"SUCCEEDED"},{"paused":false,"level":2,"jobSource":"notice_log/etl_notice_agentapi_click_exception.job","updateTime":1478001008306,"externalExecutionId":null,"inNodes":["etl_notice_click_impression_exception","etl_notice_install_exception"],"outNodes":["finish_notice"],"propSource":null,"startTime":1478000822436,"id":"etl_notice_agentapi_click_exception","endTime":1478001008268,"jobType":"command","status":"SUCCEEDED"},{"paused":false,"level":2,"jobSource":"notice_log/etl_notice_agentapi_request_exception.job","updateTime":1478000963983,"externalExecutionId":null,"inNodes":["etl_notice_click_impression_exception","etl_notice_install_exception"],"outNodes":["finish_notice"],"propSource":null,"startTime":1478000822441,"id":"etl_notice_agentapi_request_exception","endTime":1478000963914,"jobType":"command","status":"SUCCEEDED"},{"paused":false,"level":1,"jobSource":"notice_log/etl_notice_install_exception.job","updateTime":1478000532615,"externalExecutionId":null,"inNodes":["st_notice_all"],"outNodes":["etl_notice_agentapi_click_exception","etl_notice_agentapi_request_exception"],"propSource":null,"startTime":1478000392254,"id":"etl_notice_install_exception","endTime":1478000532576,"jobType":"command","status":"SUCCEEDED"},{"paused":false,"level":1,"jobSource":"notice_log/etl_notice_request_exception_seriveice_init.job","updateTime":1478000850527,"externalExecutionId":null,"inNodes":["st_notice_all"],"outNodes":["finish_notice"],"propSource":null,"startTime":1478000392257,"id":"etl_notice_request_exception_seriveice_init","endTime":1478000850481,"jobType":"command","status":"SUCCEEDED"},{"paused":false,"level":1,"jobSource":"notice_log/elt_notice_request_exception_return_empty.job","updateTime":1478001109773,"externalExecutionId":null,"inNodes":["st_notice_all"],"outNodes":["finish_notice"],"propSource":null,"startTime":1478000392260,"id":"elt_notice_request_exception_return_empty","endTime":1478001109722,"jobType":"command","status":"SUCCEEDED"},{"paused":false,"level":0,"jobSource":"notice_log/st_notice_all.job","updateTime":1478000392226,"externalExecutionId":null,"inNodes":[],"outNodes":["etl_notice_click_impression_exception","etl_notice_request_exception_seriveice_init","etl_notice_install_exception","elt_notice_request_exception_return_empty"],"propSource":null,"startTime":1478000213737,"id":"st_notice_all","endTime":1478000392186,"jobType":"command","status":"SUCCEEDED"}],"submitUser":"msystem","startTime":1478000213665,"endTime":1478001109926,"flowId":"finish_notice","projectId":858,"proxyUsers":["msystem"],"properties":[],"status":"SUCCEEDED"}

**Comment by alyiwang** [comment]
This maybe due to different Azkaban version or config. If the Azkaban db results doesn't contain certain field, you can adjust the result parsing steps accordingly to fit the needs.
