### ISSUE TITLE
自动分析azkaban作业的血缘关系和数据血缘关系？

### ISSUE THREAD

**Issue by superwood** [linkedin/WhereHows#263]
目前是否能自动分析azkaban作业的血缘关系和数据血缘关系？

还是说血缘关系需要我们手动去建立关联?

**Comment by peculiarhyp** [comment]
ember.js这一块没更新了吗？这代码都是那个版本的了哦……太古老了吧

**Comment by alyiwang** [comment]
@peculiarhyp We are revamping our UI with new design. It's currently under development on Linkedin branch and will be merged to master branch soon.

**Comment by diaowenyang** [comment]
@superwood @peculiarhyp 怎么样获取血缘关系的数据呢？能帮帮我吗？

**Comment by superwood** [comment]
@diaowenyang    

1. 所有mr作业，都能通过track url 获取到它的输入路径和输出路径
2. azkaban上提交的mr 都能追踪到track url

**Comment by diaowenyang** [comment]
@superwood 感谢你的答复。我对这个还是不太懂。我在研究另外一个元数据管理工具 Apache Atlas 的时候，只要在数据库中创建有血缘关系的表，Atlas就能自动识别抽取到。
比如下面：
`
create table parent_table(
user_name string comment 'user_name value',
user_id int comment 'user_id value')
partitioned by(reg_month string)
row format delimited
fields terminated by '\t'
fields terminated by '\t'
lines terminated by '\n';

create table child_table as select user_name ,user_id,reg_month from parent_table;
`
我以为wherehows也能这么智能。为什么wherehows需要用azkaban获取血缘关系，为什么获取血缘关系还要mapreduce作业，你能帮我解释一下吗？

**Comment by superwood** [comment]
@diaowenyang 
这是血缘关系获取方式不同。
wherehows 在意的是0侵入性的去获取分析血缘关系。 正常的业务作业不需要做任何额外动作即可获取血缘关系。每个etl任务发布，无需发布者做额外的事情。

Atlas 需要人为去注册(创建表)才做血缘关系抽取。在大规模的etl情况下，每个etl的任务发布都去注册是难以做到的。atlas比较依赖人的自觉。

**Comment by diaowenyang** [comment]
@superwood 非常感谢。
wiki里有“To test whether the backend service have run successfully, you can add some dataset to hdfs (in avro format) and/or run some pig/hive/mapreduce jobs that read/write to some datasets. ”是不是可以理解成当前wherehows不能支持oracle的血缘关系，只能支持hadoop方面的血缘关系呢？

**Comment by ali8zake** [comment]
请问，业内还有其他类似的开源组件吗？想对比下。

**Comment by keremsahin1** [comment]
Dear issue owner,

Thanks for your interest in WhereHows. We have recently announced DataHub which is the rebranding of WhereHows. LinkedIn improved the architecture of WhereHows and rebranded WhereHows into DataHub and replaced its metadata infrastructure in this direction. DataHub is a more advanced and improved metadata management product compared to WhereHows. 

Unfortunately, we have to stop supporting WhereHows to better focus on DataHub and offer more help to DataHub users. Therefore, we will drop all issues related to WhereHows and will not accept any contribution for it. Active development for DataHub has already started on `datahub` branch and will continue to live in there until it's finally merged to master and project is renamed to DataHub. 

Please check the `datahub` branch to get familar with DataHub.

Best,
DataHub team
