### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by simplesteph** [linkedin/WhereHows#266]
Hi,

I've been trying to use wherehows and I'd like to give a little bit of constructive feedback. 
I think the user interface is great for the front-end, it really achieves its goal. 

But I think the backend could be way better. As per my understanding, the backend is what's allowing data to go into the mysql database, which will in turn feed the front-end. 
I have given up trying to make the backend work. I see where it's headed, but I don't think it's usable nor maintainable for an average user. It probably is working as intended when configured, but configuring it is way too hard.  

Here is what I think is missing to make this product great: a backend UI:
- Filling the properties in `wh_property` table should be the first thing asked by the user in case these properties don't exist. 
   - Any API call shouldn't succeed until these properties are filled. There, a UI would be great. 
   - Some of these properties could be filled by the backend itself I think: jdbc connection url, username, password, etc... all accessible properties within the backend play app. 
   - the encryption file could be randomly generated and placed at a well defined location. Think of how much the average user (like me) shouldn't know about
   - wherehows.ui.tree.dataset.file	: these should be standard if you also reference a location for these in your front-end application.conf. 

Already as you can see, a bit of hurdle just getting this one table right.

- Adding a database: 
   - there should be a UI for that. If I'm supposed to reference a few details to allow the backend to connect to my db, I don't want to make an API call for it, I just want to fill that info in a form. I also would like to see all the databases that my backend covers without logging in directly into mysql database. Getting stats such as last job date, how long it took to run, how much metadata was extracted, would be amazing too! 
   - The backend should check whether or not the provided driver class exist. If it doesn't, it should offer a way to download the drivers, and the backend itself should place these drivers into the jar folder. I guess you don't want to bundle any drivers for licensing issues, but there's a lot of added value to just guiding the user in that process, by automating it entirely. *In the end, as a guy who has information about a few databases my company uses, I just want a UI to reference them, and I expect WhereHows to do its magic.*

- Adding an application: same as above, an UI would be great to put everything together. 

- Pretty much any endpoint of the API: if the user is expected to manually run a query, create a UI for it (form / table, not much more).

Also:
- **Distribute binaries, or docker images of these binaries.** Show people which config file they should edit, and that's how much anyone trying to setup your product should do. In today's IT world, I think it's key to have as little setup steps as possible. 
- Be consistent in your config variables. `web/application.conf` and `backend-service/application.conf` both reference the WHZ database, but one uses env variables, one doesn't. IMO they both should. 
- Clarity of the documentation. I'm having a lot of trouble navigating the documentation, reading the main README.md or the Getting Started Wiki, jumping around between pages, etc etc. I suggest you take someone within your company, and try to have them install / run wherehows from scratch. Just observe how they read the docs, what they don't understand, etc. 
- If you don't want to re-write the docs, I understand you, it's long and painful. You guys are the ones who truly own and understand the product, so why not make a short video, that shows the entire process to stand wherehows up? Just show me how to install, configure, deploy, and add one application and one database (hive, oracle, teradata, whatever). The rest, the users can figure out. At least they'll get a good understanding. 
- You might have included some confidential LinkedIn information somewhere. Please contact me at stephane at simplemachines dot com dot au to discuss that. 

Hopefully this feedback helps. Happy to see your thoughts on it. You guys have an amazing product, it just needs a tiny push to become an amazing, and an usable product. 

Best regards,
Stephane

**Comment by superwood** [comment]
It sounds great! The cmd line is too hard to use.

**Comment by alyiwang** [comment]
Thanks for the great feedback!

WhereHows has planed several usability improvement besides our feature development. 
1. Documentation improvement. 
2. Configuration simplification, including config files.
3. (Long term) Backend admin UI for configuration, management and monitoring.

Stay tuned for our updates!

**Comment by keremsahin1** [comment]
Dear issue owner,

Thanks for your interest in WhereHows. We have recently announced DataHub which is the rebranding of WhereHows. LinkedIn improved the architecture of WhereHows and rebranded WhereHows into DataHub and replaced its metadata infrastructure in this direction. DataHub is a more advanced and improved metadata management product compared to WhereHows. 

Unfortunately, we have to stop supporting WhereHows to better focus on DataHub and offer more help to DataHub users. Therefore, we will drop all issues related to WhereHows and will not accept any contribution for it. Active development for DataHub has already started on `datahub` branch and will continue to live in there until it's finally merged to master and project is renamed to DataHub. 

Please check the `datahub` branch to get familar with DataHub.

Best,
DataHub team
