### ISSUE TITLE
HIVE DATASET ERROR.  A bug need be fixed。

### ISSUE THREAD

**Issue by superwood** [linkedin/WhereHows#267]
The table  "stg_dict_dataset_instance"  schema do not have fields "schema_text, ddl_text" which are used by HiveLoad.py  function "load_dataset_instance"。

**Comment by alyiwang** [comment]
Thanks for the bug report! We've created a ticket for that.

**Comment by alyiwang** [comment]
Thanks for the input, fixed in pull request #314
