### ISSUE TITLE
gradlew build error

### ISSUE THREAD

**Issue by dragon5151** [linkedin/WhereHows#281]
HI:
    When I was build,it was in error.

[root@localhost backend-service]# ../gradlew build
Defining custom 'build' task when using the standard Gradle lifecycle plugins has been deprecated and is scheduled to be removed in Gradle 3.0
Defining custom 'check' task when using the standard Gradle lifecycle plugins has been deprecated and is scheduled to be removed in Gradle 3.0
Defining custom 'assemble' task when using the standard Gradle lifecycle plugins has been deprecated and is scheduled to be removed in Gradle 3.0
:backend-service:playClean
[info] Loading project definition from /usr/local/wherehows/WhereHows/backend-service/project
[info] Set current project to backend-service (in build file:/usr/local/wherehows/WhereHows/backend-service/)
[success] Total time: 1 s, completed 2016-11-25 17:19:47
:wherehows-common:compileJava UP-TO-DATE
:wherehows-common:processResources UP-TO-DATE
:wherehows-common:classes UP-TO-DATE
:wherehows-common:jar UP-TO-DATE
:hadoop-dataset-extractor-standalone:compileJava UP-TO-DATE
:hadoop-dataset-extractor-standalone:processResources UP-TO-DATE
:hadoop-dataset-extractor-standalone:classes UP-TO-DATE
:hadoop-dataset-extractor-standalone:jar UP-TO-DATE
:metadata-etl:compileJava UP-TO-DATE
:metadata-etl:processResources UP-TO-DATE
:metadata-etl:classes UP-TO-DATE
:metadata-etl:copyFiles UP-TO-DATE
:metadata-etl:jar UP-TO-DATE
:backend-service:copyPlayLibs UP-TO-DATE
:backend-service:playCompile
[info] Loading project definition from /usr/local/wherehows/WhereHows/backend-service/project
[info] Set current project to backend-service (in build file:/usr/local/wherehows/WhereHows/backend-service/)
[info] Updating {file:/usr/local/wherehows/WhereHows/backend-service/}root...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Compiling 6 Scala sources and 46 Java sources to /usr/local/wherehows/WhereHows/backend-service/target/scala-2.10/classes...
**[error] error while loading <root>, error in opening zip file
scala.reflect.internal.MissingRequirementError: object scala.runtime in compiler mirror not found.**
[error] (compile:compileIncremental) scala.reflect.internal.MissingRequirementError: object scala.runtime in compiler mirror not found.
[error] Total time: 13 s, completed 2016-11-25 17:20:55
:backend-service:playCompile FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':backend-service:playCompile'.
**> Process 'command '/usr/local/wherehows/activator-1.3.11-minimal/bin/activator'' finished with non-zero exit value 1**

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Hope to get answers,thx

**Comment by alyiwang** [comment]
Are you using the Master branch or Linkedin branch? 
It seems you might need to install Scala and include it in the classpath for sbt to run.

**Comment by dragon5151** [comment]
Problem has been solved.
I move the WhereHows to the root directory.
the build is success.

**Comment by dragon5151** [comment]
test
