### ISSUE TITLE
Why  the "java.security.auth.login.config" or "java.security.krb5.conf"  is needed for  HadoopJobHistoryNodeExtractor?

### ISSUE THREAD

**Issue by superwood** [linkedin/WhereHows#283]
In java code  file(HadoopJobHistoryNodeExtractor.java,line 91) , the code force us to  config at least one of them？ 

 if (System.getProperty("java.security.auth.login.config") == null
      || System.getProperty("java.security.krb5.conf") == null) {
      throw new Exception("Can't find java security config files");
    }

**Comment by ericsun2** [comment]
@superwood for a Hadoop w/o security configured, this may not be needed. 
A warning in log can be sufficient.

**Comment by ericsun2** [comment]
#299 should relax the expectation for krb5.conf and gss-jaas.conf.
If your Hadoop cluster is secured by Kerberos, you have to provide both config files accordingly.
