### ISSUE TITLE
can support  aws s3  for dataset?

### ISSUE THREAD

**Issue by superwood** [linkedin/WhereHows#297]
can support  aws s3  for dataset?

**Comment by ericsun2** [comment]
Yeah.
dataset_type = s3
urn = s3a://\<bucket\>/\<key path\> or s3://\<bucket\>/\<key path\>

Similarly, file:///\<full path\> is for general file system

**Comment by rilma** [comment]
Hello, where can the "dataset_type" and "urn" parameters be set?

**Comment by tooptoop4** [comment]
@ericsun2 @alyiwang can wherehows import object tags from s3?
