### ISSUE TITLE
  global  Lineage   for  azkaban  may be better 。 

### ISSUE THREAD

**Issue by superwood** [linkedin/WhereHows#301]
At this time, the lineage  with azkaban  is only for  one work  flow。 
Now that   WhereHows  got all the   MR configuration with inputfilepath and outputfilepath,   I think  it 's no hard to draw  the  lineage map for all  jobs  launched by  azkaban .

**Comment by ericsun2** [comment]
@superwood 
Currently we don't have a good layout algorithm to render a graph with too many jobs. So we only display all jobs within a single Azkaban flows (by selecting the flow from "Flows" tab and then clicking "Lineage". See the example screenshot.). Are you asking for a graph with jobs from multiple flows?
![az flow lineage](https://cloud.githubusercontent.com/assets/8866410/21274956/868028a0-c37f-11e6-9d4e-aa40e444dedf.png)

**Comment by superwood** [comment]
@ericsun2    

Yes,  graph with jobs from all flows  in azkaban . We already collect all input and output  file path  with job. 

A graph with jobs for all flows is good 。

**Comment by ericsun2** [comment]
The challenge is we may get a spaghetti layout with too many flows in a single graph.

We used to have the option to add multiple flows into the graph, we can bring that option back, yet we should realistically expect no more than a few flows (instead of all flows) for human viewable graph.

**Comment by superwood** [comment]
@ericsun2  every well.  

Multiple flows into the graph is good.  For the cost of  layout many flows in a single graph, We can layout the points ( one point mean one job/data) one by one.  At first , one (or three ) point(s) in a single graph. Then , if wants to know which the job(data) is come from  ,   people can click somewhere(  name "parent"  for example) and then layout the parent job(data).



An other suggestion,  We now can search job by name and find what data  it process.   Some time , data is given  and we want to know which jobs are processing it .  How to do that?

**Comment by keremsahin1** [comment]
Dear issue owner,

Thanks for your interest in WhereHows. We have recently announced DataHub which is the rebranding of WhereHows. LinkedIn improved the architecture of WhereHows and rebranded WhereHows into DataHub and replaced its metadata infrastructure in this direction. DataHub is a more advanced and improved metadata management product compared to WhereHows. 

Unfortunately, we have to stop supporting WhereHows to better focus on DataHub and offer more help to DataHub users. Therefore, we will drop all issues related to WhereHows and will not accept any contribution for it. Active development for DataHub has already started on `datahub` branch and will continue to live in there until it's finally merged to master and project is renamed to DataHub. 

Please check the `datahub` branch to get familar with DataHub.

Best,
DataHub team
