### ISSUE TITLE
Search azkaban jobs with  filepath key words.

### ISSUE THREAD

**Issue by superwood** [linkedin/WhereHows#302]
Some times , We want to know  which jobs  are processing  the file  we concern。

Now that WhereHows collected the   configuration of azkaban jobs with inputfile/outputfile,  It is easy to  search azkaban jobs using filepath .

**Comment by alyiwang** [comment]
Thanks for the input. We are designing our brand new search experience and UI. We will take the search of azkaban jobs into consideration.

**Comment by keremsahin1** [comment]
Dear issue owner,

Thanks for your interest in WhereHows. We have recently announced DataHub which is the rebranding of WhereHows. LinkedIn improved the architecture of WhereHows and rebranded WhereHows into DataHub and replaced its metadata infrastructure in this direction. DataHub is a more advanced and improved metadata management product compared to WhereHows. 

Unfortunately, we have to stop supporting WhereHows to better focus on DataHub and offer more help to DataHub users. Therefore, we will drop all issues related to WhereHows and will not accept any contribution for it. Active development for DataHub has already started on `datahub` branch and will continue to live in there until it's finally merged to master and project is renamed to DataHub. 

Please check the `datahub` branch to get familar with DataHub.

Best,
DataHub team
