### ISSUE TITLE
how to import new dataset into WhereHows

### ISSUE THREAD

**Issue by wangfeijs** [linkedin/WhereHows#304]
WhereHows works successful, how to import new dataset into WhereHows,thanks.

**Comment by PettterPan** [comment]
you can do a new instance yourself in the etl mode

**Comment by sunny1978** [comment]
Hi - were you able to import new datasets thru etl mode or sql inserts or rest?
I would like to insert hdfs dataset. Servers (web and backedn) both started fine, but couldnt load them. 
Kindly give us some samples to load HDFS, HIVE and HBase datasets - assuming we have 1 all in one cluster/sandbox environment.

**Comment by dmoore247** [comment]
And Gitter: https://gitter.im/wherehows/Lobby

**Comment by keremsahin1** [comment]
Dear issue owner,

Thanks for your interest in WhereHows. We have recently announced DataHub which is the rebranding of WhereHows. LinkedIn improved the architecture of WhereHows and rebranded WhereHows into DataHub and replaced its metadata infrastructure in this direction. DataHub is a more advanced and improved metadata management product compared to WhereHows. 

Unfortunately, we have to stop supporting WhereHows to better focus on DataHub and offer more help to DataHub users. Therefore, we will drop all issues related to WhereHows and will not accept any contribution for it. Active development for DataHub has already started on `datahub` branch and will continue to live in there until it's finally merged to master and project is renamed to DataHub. 

Please check the `datahub` branch to get familar with DataHub.

Best,
DataHub team
