### ISSUE TITLE
about the  lineage for hive job

### ISSUE THREAD

**Issue by PettterPan** [linkedin/WhereHows#305]
Recently, I would like to put the lineage feature into our metadata management system,but when i use the table  log_lineage_pattern met problems , can you give me some demos for the regrex. thank you very much

**Comment by ericsun2** [comment]
Hi @PettterPan, please try some regex patterns in log_lineage_pattern

`
INSERT INTO log_lineage_pattern(pattern_type, regex, database_type, database_name_index, dataset_index, operation_type, record_count_index, record_byte_index, insert_count_index, insert_byte_index, delete_count_index, delete_byte_index, update_count_index, update_byte_index, comments, source_target_type)
VALUES
  ('hourglass', 'Moving from staged path\\[\\S*\\] to final resting place\\[(\\/(?!tmp)[\\S]*)\\]', 'hdfs', NULL, 1, 'write', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'hourglass', 'target')
 ,('hourglass', 'Moving \\S* to (\\/(?!tmp)[\\S]*)', 'hdfs', NULL, 1, 'write', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'hourglass', 'target')
 ,('build and push', 'Pushing to cluster URL: (tcp:\\S*)[\\s\\S]*Initiating swap of (\\S*) with dataDir', 'voldermont', 1, 2, 'push', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'build and push voldermort', 'target')
 ,('pig log', 'Successfully read (\\d+) records( \\(\\d+ bytes\\))? from: "(.*)"', 'hdfs', NULL, 3, 'read', 1, 2, NULL, NULL, NULL, NULL, NULL, NULL, 'pig log', 'source')
 ,('pig log', 'Successfully stored (\\d+) records( \\(\\d+ bytes\\))? in: "(.*)"', 'hdfs', NULL, 3, 'write', 1, 2, NULL, NULL, NULL, NULL, NULL, NULL, 'pig log', 'target')
 ,('cubert log', 'INFO - \\[Dependency Analyzer\\] Program inputs: \\[(.*)\\]', 'hdfs', NULL, 1, 'read', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'cubert log', 'source')
 ,('cubert log', 'INFO - STORE \\w+ INTO "(.*)" USING \\w+', 'hdfs', NULL, 1, 'write', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'cubert log', 'target')
 ,('ump log', 'INFO (baseInput|Snapshot input) path(:)? (\\S+)', 'hdfs', NULL, 3, 'read', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'ump log: input', 'source')
 ,('ump log', 'INFO (Output path:|Snapshot output path:|- output path :|\\w+ multioutput. Path =) (\\S+)', 'hdfs', NULL, 2, 'write', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'ump log: output', 'target')
 ,('hive insert', '\\b?(INSERT|insert|Insert)\\s+(INTO|into|Into|OVERWRITE|overwrite|Overwrite)\\s+(TABLE|table|Table)\\s+(\\w+\\.\\w+)', 'hive', NULL, 4, 'write', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'hive: insert', 'target')
 ,('hive update', '\\b?(UPDATE|update|Update)\\s+(\\w+\\.\\w+)', 'hive', NULL, 2, 'update', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'hive: update', 'target')
;
`

**Comment by PettterPan** [comment]
@ericsun2   thx very much
