### ISSUE TITLE
Permissions In VM

### ISSUE THREAD

**Issue by lzm7455** [linkedin/WhereHows#307]
New to WhereHows. 
Just start to check the function in the VM U provided, trying to match WhereHows to my job issues.
I wanna have a full understanding about the abilities of WhereHows and its env. Is it possible to tell us the **root password in the VM U provided**?
Thx.

**Comment by mars-lan** [comment]
We're deprecating VM in favor of docker images. Please keep an eye on wherehows-docker directory.
