### ISSUE TITLE
more examples

### ISSUE THREAD

**Issue by sambazhu** [linkedin/WhereHows#309]
hi,
    目前在基于wherehows做hadoop元数据抽取。请问后期版本会提供支持抽取Oozie得到dataset和job的血缘关系的ETLjob吗，如果是从sql解析中获取表之间和字段之间的血缘关系是不是更合适呢

**Comment by alyiwang** [comment]
We do have Oozie ETL jobs for extracting the operational metadata. But since Linkedin does not use Oozie, this job hasn't been updated for some time. You probably need to test to see if it works. The idea is similar to the Azkaban jobs.

**Comment by diaowenyang** [comment]
@sambazhu  血缘关系获取到了吗？怎么样才能抽取到血缘关系的数据呢？

**Comment by keremsahin1** [comment]
Dear issue owner,

Thanks for your interest in WhereHows. We have recently announced DataHub which is the rebranding of WhereHows. LinkedIn improved the architecture of WhereHows and rebranded WhereHows into DataHub and replaced its metadata infrastructure in this direction. DataHub is a more advanced and improved metadata management product compared to WhereHows. 

Unfortunately, we have to stop supporting WhereHows to better focus on DataHub and offer more help to DataHub users. Therefore, we will drop all issues related to WhereHows and will not accept any contribution for it. Active development for DataHub has already started on `datahub` branch and will continue to live in there until it's finally merged to master and project is renamed to DataHub. 

Please check the `datahub` branch to get familar with DataHub.

Best,
DataHub team
