### ISSUE TITLE
report bug：HDFS Dataset HdfsLoad.py ERROR

### ISSUE THREAD

**Issue by sambazhu** [linkedin/WhereHows#312]
调用HdfsLoad.py时报错：
zxJDBC.Error: Unknown column 'schema_text' in 'field list' [SQLCode: 1054], [SQLState: 42S22]。

此时发现表stg_dict_dataset_instance不存在字段schema_text，而是schema。
在HdfsLoad.py中的代码：
INSERT INTO stg_dict_dataset_instance
( dataset_urn,
db_id,
deployment_tier,
data_center,
server_cluster,
slice,
status_id,
native_name,
logical_name,
`version`,
instance_created_time,
created_time,
wh_etl_exec_id,
abstract_dataset_urn,
schema_text
)
……
是否需要修改stg_dict_dataset_instance的表字段为schema_text呢？

**Comment by rkluszczynski** [comment]
Hello,
after some time of not working with Wherehows, this month I'm trying to run latest version. Last week I've encountred the same error - fortunately error is in english;)

I did not managed to debug it yet, so any help with @sambazhu issue would be also appreciate by me:)

Kind regards,
Rafal Kluszczynski

**Comment by alyiwang** [comment]
Thanks for the input, fixed in pull request #314
