### ISSUE TITLE
problems met when running etl job

### ISSUE THREAD

**Issue by thomas-young-2013** [linkedin/WhereHows#327]
I create a job about monitoring data in HIVE Datasets and have the ETL Jobs pickup and run. When I started the backend, I got the problem "Error: Could not find or load main class metadata.etl.Launcher" below:
    [info] - application - total 1 jobs due, white list : null
    [info] - application - running job: job id :21
    [info] - application - Current running jobs : 
    [info] - application - Send message : (jobType:HIVE_DATASET_METADATA_ETL refIdType:DB refId: 61 whEtlJobId:  21 whEtlExecId:    4)
    [debug] - application - run command : java -cp '/thomas/activator/activator-dist-1.3.12/libexec/activator-launch-1.3.12.jar' -Dconfig=/var/tmp/wherehows/exec/4.properties -DCONTEXT=HIVE_DATASET_METADATA_ETL metadata.etl.Launcher
    [error] - application - *** Process + 17125 failed, status: 1
    [error] - application - Error Details:
    **## Error: Could not find or load main class metadata.etl.Launcher**

I need this service up and running and monitoring data flowing in the cluster. Can anybody help me out?

**Comment by xkcoding** [comment]
how to solve this error?
