### ISSUE TITLE
Suspicious code fragments

### ISSUE THREAD

**Issue by AppChecker** [linkedin/WhereHows#328]
Hi!

Static code analyzer [AppChecker](https://cnpo.ru/en/solutions/appchecker.php) found several suspicious code fragments:
1) [backend-service/app/controllers/DatasetController.java](https://github.com/linkedin/WhereHows/blob/156e4a80159c41acae95fbb54aa69ce3c1ffc74d/backend-service/app/controllers/DatasetController.java#L183-L185)
```
    if (dataset_path.indexOf(".") > 0) {
      dataset_path.replace(".", "/");
    }
```
variable dataset_path will not change.
Probably it should be:
```
    if (dataset_path.indexOf(".") > 0) {
      dataset_path = dataset_path.replace(".", "/");
    }
```

2) [wherehows-common/src/main/java/wherehows/common/schemas/DatasetConstraintRecord.java](https://github.com/linkedin/WhereHows/blob/156e4a80159c41acae95fbb54aa69ce3c1ffc74d/wherehows-common/src/main/java/wherehows/common/schemas/DatasetConstraintRecord.java#L115-L117)

```
  public void setAdditionalReferences(Map<String, String> additionalReferences) {
    this.additionalReferences = this.additionalReferences;
  }
```
this.additionalReferences is assigned to itself.
Probably it should be:

```
  public void setAdditionalReferences(Map<String, String> additionalReferences) {
    this.additionalReferences = additionalReferences;
  }
```
3)  [web/app/dao/DatasetColumnCommentRowMapper.java](https://github.com/linkedin/WhereHows/blob/156e4a80159c41acae95fbb54aa69ce3c1ffc74d/web/app/dao/DatasetColumnCommentRowMapper.java#L43)

` if (StringUtils.isNotBlank(strIsDefault) && strIsDefault == "Y")`

Using equals() is better to compare string.

4) [web/app/dao/LineageDAO.java](https://github.com/linkedin/WhereHows/blob/156e4a80159c41acae95fbb54aa69ce3c1ffc74d/web/app/dao/LineageDAO.java#L281)

`if (target.partition_end == node.partition_end)`

Similarly.

These possible defects found with [AppChecker](https://cnpo.ru/en/solutions/appchecker.php)

**Comment by alyiwang** [comment]
Fixed in PR #335
