### ISSUE TITLE
Get stuck when "gradlew build" from source.

### ISSUE THREAD

**Issue by superwood** [linkedin/WhereHows#331]
Get stuck when "gradlew build" from source.

Things went on like that for one hour!!!

There are last messages:  

Defining custom 'build' task when using the standard Gradle lifecycle plugins has been deprecated and is scheduled to be removed in Gradle 3.0
Defining custom 'check' task when using the standard Gradle lifecycle plugins has been deprecated and is scheduled to be removed in Gradle 3.0
Defining custom 'assemble' task when using the standard Gradle lifecycle plugins has been deprecated and is scheduled to be removed in Gradle 3.0
:backend-service:playClean
[info] Loading project definition from /Users/xxxxx/work/mygithub/WhereHows/backend-service/project
> Building 0% > :backend-service:playClean

**Comment by alyiwang** [comment]
Hi, which branch are you building from. Does this happen frequently? Please let us know since we don't experience such issue.

**Comment by superwood** [comment]
The master  branch.  So far  ,which is stable branch ? Should I use the tag v0.2.0? @alyiwang

**Comment by passionke** [comment]
I had the same problom, for an chinese behind the gwf..

**Comment by ddzzfg** [comment]
I had also this problem....
[hadoop@mdw WhereHows]$ ./gradlew build
Defining custom 'build' task when using the standard Gradle lifecycle plugins has been deprecated and is scheduled to be removed in Gradle 3.0
Defining custom 'check' task when using the standard Gradle lifecycle plugins has been deprecated and is scheduled to be removed in Gradle 3.0
Defining custom 'assemble' task when using the standard Gradle lifecycle plugins has been deprecated and is scheduled to be removed in Gradle 3.0
:backend-service:playClean
[info] Loading project definition from /home/hadoop/WhereHows/backend-service/project
[error] Server access Error:  (Connection refused) url=https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.apache.ant/ant/1.9.3/ivys/ivy.xml

**Comment by ddzzfg** [comment]
I also had  this problem...
[hadoop@mdw WhereHows]$ ./gradlew build
Defining custom 'build' task when using the standard Gradle lifecycle plugins has been deprecated and is scheduled to be removed in Gradle 3.0
Defining custom 'check' task when using the standard Gradle lifecycle plugins has been deprecated and is scheduled to be removed in Gradle 3.0
Defining custom 'assemble' task when using the standard Gradle lifecycle plugins has been deprecated and is scheduled to be removed in Gradle 3.0
:backend-service:playClean
[info] Loading project definition from /home/hadoop/WhereHows/backend-service/project
[error] Server access Error:  (Connection refused) url=https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.apache.ant/ant/1.9.3/ivys/ivy.xml

**Comment by alyiwang** [comment]
WhereHows included several repositories for pulling the build dependencies, including maven, jcenter. If this build failure is due to certain dependencies URLs not available because of network or firewall, then we might need to work around this by downloading the jar and add to classpath. 

As for the stable release of WhereHows asked by @superwood , we have several development changes planed for WhereHows very soon (Early next month). One is to merge to branches into one, so we only need to focus on one branch. Another is to have a release cycle for a stable version. Please stay tuned. Currently the master branch should be more stable.

**Comment by Icrush** [comment]
I  also had the same problem, any one can fix this ?
thx in advance

**Comment by mars-lan** [comment]
Can you try again on master's tip?

**Comment by keremsahin1** [comment]
Dear issue owner,

Thanks for your interest in WhereHows. We have recently announced DataHub which is the rebranding of WhereHows. LinkedIn improved the architecture of WhereHows and rebranded WhereHows into DataHub and replaced its metadata infrastructure in this direction. DataHub is a more advanced and improved metadata management product compared to WhereHows. 

Unfortunately, we have to stop supporting WhereHows to better focus on DataHub and offer more help to DataHub users. Therefore, we will drop all issues related to WhereHows and will not accept any contribution for it. Active development for DataHub has already started on `datahub` branch and will continue to live in there until it's finally merged to master and project is renamed to DataHub. 

Please check the `datahub` branch to get familar with DataHub.

Best,
DataHub team
