### ISSUE TITLE
 No module named SchemaUrlHelper

### ISSUE THREAD

**Issue by superwood** [linkedin/WhereHows#337]
Hive   HiveExtract.py job run fail.  
 No module named SchemaUrlHelper

application - 13:11:26 [WhereHowsETLService-akka.actor.default-dispatcher-9] INFO   - ImportError: No module named SchemaUrlHelper
application - 13:11:26 [WhereHowsETLService-akka.actor.default-dispatcher-9] INFO   - 
application - 13:11:26 [WhereHowsETLService-akka.actor.default-dispatcher-9] INFO   - 	at org.python.core.Py.ImportError(Py.java:328)
application - 13:11:26 [WhereHowsETLService-akka.actor.default-dispatcher-9] INFO   - 	at org.python.core.imp.import_first(imp.java:877)
application - 13:11:26 [WhereHowsETLService-akka.actor.default-dispatcher-9] INFO   - 	at org.python.core.imp.import_module_level(imp.java:972)
application - 13:11:26 [WhereHowsETLService-akka.actor.default-dispatcher-9] INFO   - 	at org.python.core.imp.importName(imp.java:1062)
application - 13:11:26 [WhereHowsETLService-akka.actor.default-dispatcher-9] INFO   - 	at org.python.core.ImportFunction.__call__(__builtin__.java:1280)
application - 13:11:26 [WhereHowsETLService-akka.actor.default-dispatcher-9] INFO   - 	at org.python.core.PyObject.__call__(PyObject.java:431)
application - 13:11:26 [WhereHowsETLService-akka.actor.default-dispatcher-9] INFO   - 	at org.python.core.__builtin__.__import__(__builtin__.java:1232)
application - 13:11:26 [WhereHowsETLService-akka.actor.default-dispatcher-9] INFO   - 	at org.python.core.imp.importOne(imp.java:1081)
application - 13:11:26 [WhereHowsETLService-akka.actor.default-dispatcher-9] INFO   - 	at org.python.pycode._pyx0.f$0(<iostream>:511)
application - 13:11:26 [WhereHowsETLService-akka.actor.default-dispatcher-9] INFO   - 	at org.python.pycode._pyx0.call_function(<iostream>)
application - 13:11:26 [WhereHowsETLService-akka.actor.default-dispatcher-9] INFO   - 	at org.python.core.PyTableCode.call(PyTableCode.java:167)
application - 13:11:26 [WhereHowsETLService-akka.actor.default-dispatcher-9] INFO   - 	at org.python.core.PyCode.call(PyCode.java:18)
application - 13:11:26 [WhereHowsETLService-akka.actor.default-dispatcher-9] INFO   - 	at org.python.core.Py.runCode(Py.java:1386)
application - 13:11:26 [WhereHowsETLService-akka.actor.default-dispatcher-9] INFO   - 	at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:296)
application - 13:11:26 [WhereHowsETLService-akka.actor.default-dispatcher-9] INFO   - 	at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:291)
application - 13:11:26 [WhereHowsETLService-akka.actor.default-dispatcher-9] INFO   - 	at metadata.etl.dataset.hive.HiveMetadataEtl.extract(HiveMetadataEtl.java:42)
application - 13:11:26 [WhereHowsETLService-akka.actor.default-dispatcher-9] INFO   - 	at metadata.etl.EtlJob.run(EtlJob.java:179)
application - 13:11:26 [WhereHowsETLService-akka.actor.default-dispatcher-9] INFO   - 	at metadata.etl.Launcher.main(Launcher.java:79)

**Comment by alyiwang** [comment]
This might be similar to #308 . We also experience random job failures due to certain python module can't be imported during runtime (even though the file is in the distribution jar). The quick fix we had is to add a re-try for 3 times if job fails fast. This reduced the early job fail to small rate. 

We are planning to rewrite the backend job scheduler (Q2 2017), it should fix several operation issues including this one.

**Comment by keremsahin1** [comment]
Dear issue owner,

Thanks for your interest in WhereHows. We have recently announced DataHub which is the rebranding of WhereHows. LinkedIn improved the architecture of WhereHows and rebranded WhereHows into DataHub and replaced its metadata infrastructure in this direction. DataHub is a more advanced and improved metadata management product compared to WhereHows. 

Unfortunately, we have to stop supporting WhereHows to better focus on DataHub and offer more help to DataHub users. Therefore, we will drop all issues related to WhereHows and will not accept any contribution for it. Active development for DataHub has already started on `datahub` branch and will continue to live in there until it's finally merged to master and project is renamed to DataHub. 

Please check the `datahub` branch to get familar with DataHub.

Best,
DataHub team
