### ISSUE TITLE
zxJDBC.DatabaseError: driver ["com.mysql.jdbc.Driver"] not found

### ISSUE THREAD

**Issue by msharma011** [linkedin/WhereHows#339]
While running OracleMetatdataEtlTest - dynamic loading of libraries is not working

**Comment by alyiwang** [comment]
Could you give more detail about the error message? At which stage extract/load did this happen? Stacktrace? Thanks. 

We don't experience such issues in production. Maybe it's due to parameters not set correctly. I will need more information to get a clear picture.

**Comment by keremsahin1** [comment]
Dear issue owner,

Thanks for your interest in WhereHows. We have recently announced DataHub which is the rebranding of WhereHows. LinkedIn improved the architecture of WhereHows and rebranded WhereHows into DataHub and replaced its metadata infrastructure in this direction. DataHub is a more advanced and improved metadata management product compared to WhereHows. 

Unfortunately, we have to stop supporting WhereHows to better focus on DataHub and offer more help to DataHub users. Therefore, we will drop all issues related to WhereHows and will not accept any contribution for it. Active development for DataHub has already started on `datahub` branch and will continue to live in there until it's finally merged to master and project is renamed to DataHub. 

Please check the `datahub` branch to get familar with DataHub.

Best,
DataHub team
