### ISSUE TITLE
服务安装完了，怎么注册hive 的dataset？文档写的太不清楚了，也没有demo

### ISSUE THREAD

**Issue by taylorzhangInSohu** [linkedin/WhereHows#342]
能不能提供一下api注册hive、azkaban等JSON的样式

**Comment by thomas-young-2013** [comment]
you can look the front&backend API in wiki and see the source code for more details

**Comment by ericsun2** [comment]
https://github.com/linkedin/WhereHows/wiki/Backend-API#etl-job-post

Hive datasets are extracted from MySql metastore, so we need to 
- register an entry in cfg_database for Hive instance with db_id = 123 for example
- add an ETL job with type = DATASET and name = HIVE_DATASET_METADATA_ETL and ref_id = 123 and ref_id_type = DB
- supply the JDBC connection info to the metastore database as ETL job's properties
- configure the crontab expression for it scheduling

**Comment by taylorzhangInSohu** [comment]
Got it, thanks a lot, I'm going to try
