### ISSUE TITLE
when integrating Oozie_Lineage_Metadata_ETL job

### ISSUE THREAD

**Issue by sambazhu** [linkedin/WhereHows#344]
In the Future Plan, WH will support Oozie lineage info integratition. 
so when the function can be used ?

**Comment by alyiwang** [comment]
Further Oozie integration is not currently in the plan for WhereHows dev at Linkedin. We might rely on community contribution to improve this. We are working with potential contributors to discuss this.

**Comment by keremsahin1** [comment]
Dear issue owner,

Thanks for your interest in WhereHows. We have recently announced DataHub which is the rebranding of WhereHows. LinkedIn improved the architecture of WhereHows and rebranded WhereHows into DataHub and replaced its metadata infrastructure in this direction. DataHub is a more advanced and improved metadata management product compared to WhereHows. 

Unfortunately, we have to stop supporting WhereHows to better focus on DataHub and offer more help to DataHub users. Therefore, we will drop all issues related to WhereHows and will not accept any contribution for it. Active development for DataHub has already started on `datahub` branch and will continue to live in there until it's finally merged to master and project is renamed to DataHub. 

Please check the `datahub` branch to get familar with DataHub.

Best,
DataHub team
