### ISSUE TITLE
How to configure Play LDAP ?

### ISSUE THREAD

**Issue by suuuch** [linkedin/WhereHows#346]
I am not good at Play ,so I don't know how to configure .Somebody can help?

authentication.ldap.url = "${YOU_LDAP_URL}"
authentication.ldap.context_factory_class = "com.sun.jndi.ldap.LdapCtxFactory"
authentication.principal.domain = "localhost"
authentication.ldap.search.base = "$YOUR_LDAP_SEARCH_BASE"

**Comment by alyiwang** [comment]
Usually it comes from the ldap server settings. 
The config could look like:
authentication.ldap.context_factory_class = "com.sun.jndi.ldap.LdapCtxFactory"
authentication.ldap.url = "ldaps://x.x.com:port"
authentication.principal.domain = "@x.com"
authentication.ldap.search.base = "ou=?,dc=?,dc=?"

**Comment by suuuch** [comment]
@alyiwang  THANK YOU！
