### ISSUE TITLE
Missing ';' in advancedSearch.js

### ISSUE THREAD

**Issue by yanshuining** [linkedin/WhereHows#354]
Errors in javascript, missing ";" at the end of the statement. 

https://github.com/linkedin/WhereHows/blob/d9438dc5bc4df6afbb34b95516b6004a1b665bd3/web/public/javascripts/routers/advancedSearch.js#L21-L23

**Comment by msropp** [comment]
Running inspector with HEAD check of master branch of WhereHows checkout, I actually get several JavaScript errors: 

SyntaxError: missing ; before statement1 search.js:29:8
SyntaxError: missing ; before statement1 advancedSearch.js:20:8
SyntaxError: missing ; before statement1 datasets.js:140:10

@mars-lan, @abhishek-agwl, can you guys address?   Could this be causing the inability to see the Vertica data that I have loaded in my dev enviroment (URNs look fine) or Hive data @yanshuining has loaded into hers?

**Comment by theseyi** [comment]
Hello,

Thanks for the feedback, we are in the process of rewriting and refactoring most of the JS code powering the ui client. We hope to cover a lot of these syntax errors and hopefully resolve any issue you may be experiencing.
This issue should be resolved in the next couple weeks.

Thanks.

Seyi



On Mar 30, 2017, at 2:35 AM, Matthew Ropp <notifications@github.com<mailto:notifications@github.com>> wrote:


Running inspector with HEAD check of master branch of WhereHows checkout, I actually get several JavaScript errors:

SyntaxError: missing ; before statement1 search.js:29:8
SyntaxError: missing ; before statement1 advancedSearch.js:20:8
SyntaxError: missing ; before statement1 datasets.js:140:10

@mars-lan<https://github.com/mars-lan>, @abhishek-agwl<https://github.com/abhishek-agwl>, can you guys address? Could this be causing the inability to see the Vertica data that I have loaded in my dev enviroment (URNs look fine) or Hive data @yanshuining<https://github.com/yanshuining> has loaded into hers?

**Comment by mars-lan** [comment]
The frontend has been greatly refactored. Problems should have been all fixed.
