### ISSUE TITLE
How can I get the metadata of an upload HDFS file 

### ISSUE THREAD

**Issue by bayernkimi** [linkedin/WhereHows#355]
sry for my bad English ,In the quick-started VM,I just upload a file to hdfs ,and then ,what should I do to get the metadata of this file. Thanks a lot :)

**Comment by alyiwang** [comment]
You need to set up the HADOOP etl job to fetch the metadata for hdfs 
https://github.com/linkedin/WhereHows/wiki/Set-Up-New-Metadata-ETL-Jobs

Please note that the VM hasn't been maintained for a while, so it might have some potential issues. We are getting some community help to set up a docker image for quick-start.

**Comment by keremsahin1** [comment]
Dear issue owner,

Thanks for your interest in WhereHows. We have recently announced DataHub which is the rebranding of WhereHows. LinkedIn improved the architecture of WhereHows and rebranded WhereHows into DataHub and replaced its metadata infrastructure in this direction. DataHub is a more advanced and improved metadata management product compared to WhereHows. 

Unfortunately, we have to stop supporting WhereHows to better focus on DataHub and offer more help to DataHub users. Therefore, we will drop all issues related to WhereHows and will not accept any contribution for it. Active development for DataHub has already started on `datahub` branch and will continue to live in there until it's finally merged to master and project is renamed to DataHub. 

Please check the `datahub` branch to get familar with DataHub.

Best,
DataHub team
