### ISSUE TITLE
Save tree data (dataset.json and flow.json) in DB.

### ISSUE THREAD

**Issue by tsukaby** [linkedin/WhereHows#500]
dataset.json and flow.json are saved as files. It is useful if the web application and the backend-service application are running on the same host, but it is inconvenient if it is running on a different host such as docker.

I think that it is better to save dataset.json and flow.json in the DB.
How do you think about it?

Thank you!

**Comment by tsukaby** [comment]
Sorry, this is a duplicated issue.
https://github.com/linkedin/WhereHows/pull/124

**Comment by keremsahin1** [comment]
Dear issue owner,

Thanks for your interest in WhereHows. We have recently announced DataHub which is the rebranding of WhereHows. LinkedIn improved the architecture of WhereHows and rebranded WhereHows into DataHub and replaced its metadata infrastructure in this direction. DataHub is a more advanced and improved metadata management product compared to WhereHows. 

Unfortunately, we have to stop supporting WhereHows to better focus on DataHub and offer more help to DataHub users. Therefore, we will drop all issues related to WhereHows and will not accept any contribution for it. Active development for DataHub has already started on `datahub` branch and will continue to live in there until it's finally merged to master and project is renamed to DataHub. 

Please check the `datahub` branch to get familar with DataHub.

Best,
DataHub team
