### ISSUE TITLE
How to use nginx proxy_pass rewrite base URL

### ISSUE THREAD

**Issue by rickywu** [linkedin/WhereHows#504]
I installed WhereHows and the web app listen on 9000
How to rewrite url so that access http://hostname/wherehows pass to http://hostname:9000?

I tried conf like this:
        location /wherehows {
            proxy_pass http://127.0.0.1:9000;        
        }

**Comment by keremsahin1** [comment]
Dear issue owner,

Thanks for your interest in WhereHows. We have recently announced DataHub which is the rebranding of WhereHows. LinkedIn improved the architecture of WhereHows and rebranded WhereHows into DataHub and replaced its metadata infrastructure in this direction. DataHub is a more advanced and improved metadata management product compared to WhereHows. 

Unfortunately, we have to stop supporting WhereHows to better focus on DataHub and offer more help to DataHub users. Therefore, we will drop all issues related to WhereHows and will not accept any contribution for it. Active development for DataHub has already started on `datahub` branch and will continue to live in there until it's finally merged to master and project is renamed to DataHub. 

Please check the `datahub` branch to get familar with DataHub.

Best,
DataHub team
