### ISSUE TITLE
Missing dependencies of linkedin branch

### ISSUE THREAD

**Issue by terrencehan** [linkedin/WhereHows#506]
Hi there, 
Will someone explain the relationship between master and linkedin branch? I'm newbie to WhereHows and kind of confused.
While compiling linkedin branch from source according guide,  a fatal exception occurred. It seemed that com.linkedin.common package was not installed or something else.  After a little bit researching, I still can not find anything valuable.  If I missied something, please point out.  Thanks.

`➜  WhereHows git:(linkedin) ✗ ./gradlew build
:restli-client:compileJava
/Users/terrence/github/linkedin/WhereHows/restli-client/src/main/java/metastore/client/Datasets.java:16: error: cannot find symbol
import com.linkedin.common.AuditStamp;
                          ^
  symbol:   class AuditStamp
  location: package com.linkedin.common
/Users/terrence/github/linkedin/WhereHows/restli-client/src/main/java/metastore/client/Datasets.java:17: error: package com.linkedin.common.urn does not exist
import com.linkedin.common.urn.Urn;
                              ^
/Users/terrence/github/linkedin/WhereHows/restli-client/src/main/java/metastore/client/Datasets.java:19: error: package com.linkedin.dataset does not exist
import com.linkedin.dataset.Dataset;
                           ^
/Users/terrence/github/linkedin/WhereHows/restli-client/src/main/java/metastore/client/Datasets.java:20: error: package com.linkedin.dataset does not exist
import com.linkedin.dataset.DatasetKey;
                           ^
/Users/terrence/github/linkedin/WhereHows/restli-client/src/main/java/metastore/client/Datasets.java:21: error: package com.linkedin.dataset does not exist
import com.linkedin.dataset.DatasetsGetRequestBuilder;
                           ^
/Users/terrence/github/linkedin/WhereHows/restli-client/src/main/java/metastore/client/Datasets.java:22: error: package com.linkedin.dataset does not exist
import com.linkedin.dataset.DatasetsRequestBuilders;
                           ^
/Users/terrence/github/linkedin/WhereHows/restli-client/src/main/java/metastore/client/Datasets.java:23: error: package com.linkedin.dataset does not exist
import com.linkedin.dataset.DeploymentInfoArray;
                           ^
/Users/terrence/github/linkedin/WhereHows/restli-client/src/main/java/metastore/client/Datasets.java:24: error: package com.linkedin.dataset does not exist
import com.linkedin.dataset.VersionedDataset;
                           ^
/Users/terrence/github/linkedin/WhereHows/restli-client/src/main/java/metastore/client/Datasets.java:25: error: package com.linkedin.dataset does not exist
import com.linkedin.dataset.VersionedDatasetsRequestBuilders;
                           ^
/Users/terrence/github/linkedin/WhereHows/restli-client/src/main/java/metastore/util/UrnUtil.java:16: error: cannot find symbol
import com.linkedin.common.FabricType;
                          ^
  symbol:   class FabricType
  location: package com.linkedin.common
/Users/terrence/github/linkedin/WhereHows/restli-client/src/main/java/metastore/util/UrnUtil.java:17: error: package com.linkedin.common.urn does not exist
import com.linkedin.common.urn.CorpuserUrn;`

**Comment by mars-lan** [comment]
The linkedin branch is for internal development so please use the master branch. However, we are in the process of combining the two branches, and the build error should be resolved after the merge.
