### ISSUE TITLE
URL encoding is not perfect.

### ISSUE THREAD

**Issue by tsukaby** [linkedin/WhereHows#515]
See below for details.
https://github.com/linkedin/WhereHows/pull/498

This problem occurs if the character "=" is included in the HDFS path.
This character should be URL encoding.

**Comment by alyiwang** [comment]
Currently the WhereHows hadoop job can't recognize this directory pattern. You could add this pattern to the SchemaFetch.java

**Comment by tsukaby** [comment]
@alyiwang  Thank you!
I changed SchemaFetch.java on my forked repository.
