### ISSUE TITLE
How to configure this framework & how to get this worked?

### ISSUE THREAD

**Issue by AristocratW** [linkedin/WhereHows#531]
Hi all,
Recently, I'm trying to use this great framework for a project.
I have a pseudo-cluster Hadoop on my computer, and I just want to find out what Wherehows can do.

I know I should start from the configuration in backend-service/conf/application.conf:
So I changed the configuration like this:

db.wherehows.driver = com.mysql.jdbc.Driver
db.wherehows.url = "jdbc:mysql://localhost/wherehows?charset=utf8&zeroDateTimeBehavior=convertToNull"
db.wherehows.username = wherehows
db.wherehows.password = wherehows
db.wherehows.host = localhost

Is this right?

And then, I have no idea about what to do next.
Should I run some example in metadata-etl module first?
And how can I overview those ETL information through the web page?
Do I need sign up for wherehows first?

Any idea will be appreciated. Thanks very much.

**Comment by alyiwang** [comment]
You can follow the getting-start guide:
https://github.com/linkedin/WhereHows/wiki/Getting-Started
and let us know if you have any problem. Thanks

**Comment by AristocratW** [comment]
Hi, @alyiwang  Thanks for your response.
Today , I follow the backend-service/README.md document and get the precondition done.
That is , I have dumped data for table 'wh_etl_job'&'wh_etl_job_property' and so on...
Then I run backend_service by activator run -Dhttp.port=9001,
Unfortunately, I got error as below:
![image](https://cloud.githubusercontent.com/assets/16303575/26776413/a10b0f88-4a0b-11e7-84b2-9959803cf58e.png)
![2017-06-05 16-22-39](https://cloud.githubusercontent.com/assets/16303575/26776421/aa948048-4a0b-11e7-8cdc-b3a7a0d9f120.jpg)

It looks like a 'can't load main class' problem, could you give me a little advice about this?
I'll be very appreciated.

**Comment by thomas-young-2013** [comment]
you can run backend by executing the script `runBackend` in backend-service!

**Comment by keremsahin1** [comment]
Dear issue owner,

Thanks for your interest in WhereHows. We have recently announced DataHub which is the rebranding of WhereHows. LinkedIn improved the architecture of WhereHows and rebranded WhereHows into DataHub and replaced its metadata infrastructure in this direction. DataHub is a more advanced and improved metadata management product compared to WhereHows. 

Unfortunately, we have to stop supporting WhereHows to better focus on DataHub and offer more help to DataHub users. Therefore, we will drop all issues related to WhereHows and will not accept any contribution for it. Active development for DataHub has already started on `datahub` branch and will continue to live in there until it's finally merged to master and project is renamed to DataHub. 

Please check the `datahub` branch to get familar with DataHub.

Best,
DataHub team
