### ISSUE TITLE
HiveLoad ERROR : Duplicate entry 

### ISSUE THREAD

**Issue by bleachzk** [linkedin/WhereHows#532]
Status of Job recorded in wh_etl_job_execution is "SUCCEEDED", but all dataset table is emptry. There is Error throw :
2017-05-25 09:33:18 ERROR HiveLoad[16]:-2 - Duplicate entry '16419-9' for key 'uix_dict_field__datasetid_sortid' [SQLCode: 1062], [SQLState: 23000]

**Comment by alyiwang** [comment]
Could you check if the staging tables stg_dict_dataset and stg_dict_field_detail has data in it? If not, could you check if the HiveExtract has produced output file that contains data.

**Comment by keremsahin1** [comment]
Dear issue owner,

Thanks for your interest in WhereHows. We have recently announced DataHub which is the rebranding of WhereHows. LinkedIn improved the architecture of WhereHows and rebranded WhereHows into DataHub and replaced its metadata infrastructure in this direction. DataHub is a more advanced and improved metadata management product compared to WhereHows. 

Unfortunately, we have to stop supporting WhereHows to better focus on DataHub and offer more help to DataHub users. Therefore, we will drop all issues related to WhereHows and will not accept any contribution for it. Active development for DataHub has already started on `datahub` branch and will continue to live in there until it's finally merged to master and project is renamed to DataHub. 

Please check the `datahub` branch to get familar with DataHub.

Best,
DataHub team
