### ISSUE TITLE
为什么HiveLoad.py里面没有load_sample()方法？

### ISSUE THREAD

**Issue by 7568** [linkedin/WhereHows#539]
我看到oracle的load里面有load_sample()方法，但是被注释了，而hive的load里面没有load_sample()方法，是有什么原因使它们不能去load_sample吗？

**Comment by alyiwang** [comment]
The sampling function for Oracle and hive hasn't been properly implemented yet. We are currently redesigning our ETL workflows with new pipeline to fetch metadata as well as sample data. I will probably be released towards end of Q3.

**Comment by 7568** [comment]
好的，谢谢

**Comment by ericsun2** [comment]
The Hive sample collection can end up as a M/R job unless we force it to local mode.
@alyiwang, are you thinking about using local mode?

**Comment by Ash-Mishra** [comment]
Is the sampling function for Hive and Oracle fixed yet? as I am still facing the problem while getting the sample data for Oracle database

**Comment by keremsahin1** [comment]
Dear issue owner,

Thanks for your interest in WhereHows. We have recently announced DataHub which is the rebranding of WhereHows. LinkedIn improved the architecture of WhereHows and rebranded WhereHows into DataHub and replaced its metadata infrastructure in this direction. DataHub is a more advanced and improved metadata management product compared to WhereHows. 

Unfortunately, we have to stop supporting WhereHows to better focus on DataHub and offer more help to DataHub users. Therefore, we will drop all issues related to WhereHows and will not accept any contribution for it. Active development for DataHub has already started on `datahub` branch and will continue to live in there until it's finally merged to master and project is renamed to DataHub. 

Please check the `datahub` branch to get familar with DataHub.

Best,
DataHub team
