### ISSUE TITLE
Metric and Business Glossary: "Coming soon" or already here?

### ISSUE THREAD

**Issue by baogorek** [linkedin/WhereHows#544]
Hi,

I see that a Metrics and Business Glossary is listed as "Coming soon" on the [Wiki](https://github.com/linkedin/WhereHows/wiki), but from the [LinkedIn Blog](https://engineering.linkedin.com/blog/2016/03/open-sourcing-wherehows--a-data-discovery-and-lineage-portal), it appears it's already there:

"In addition to machine-based pattern detection and association between business glossary and dataset, the community participation and collaboration aspect enables us to create a self-maintaining repository of documentation on the entities by encouraging conversations and pride in ownership."

If the glossary is still TBD, I'd like to add an official feature request. If it is already there, then I guess this story will be about modifying a sentence in the Wiki.

Thanks,
Ben

**Comment by nikhiltanwar** [comment]
In current build i can see comments can be added to a table/field/file etc. in dataset using user interface but definitions are not there yet i believe.

**Comment by keremsahin1** [comment]
Dear issue owner,

Thanks for your interest in WhereHows. We have recently announced DataHub which is the rebranding of WhereHows. LinkedIn improved the architecture of WhereHows and rebranded WhereHows into DataHub and replaced its metadata infrastructure in this direction. DataHub is a more advanced and improved metadata management product compared to WhereHows. 

Unfortunately, we have to stop supporting WhereHows to better focus on DataHub and offer more help to DataHub users. Therefore, we will drop all issues related to WhereHows and will not accept any contribution for it. Active development for DataHub has already started on `datahub` branch and will continue to live in there until it's finally merged to master and project is renamed to DataHub. 

Please check the `datahub` branch to get familar with DataHub.

Best,
DataHub team
