### ISSUE TITLE
Feature Request: Generic RDBMS_DATASET_METADATA_ETL

### ISSUE THREAD

**Issue by nikhiltanwar** [linkedin/WhereHows#546]
Hi Guys,

I plan to make a generic RDBMS extract which would be similar to ORACLE extract but would pull metadata from any engine using SQLAlchemy. See supported [engines](http://docs.sqlalchemy.org/en/latest/dialects/index.html) . This would enable massive list of possibilities of datasets from a number of RDBMS databases. My company plan to use it for Redshift hence trying to develop a generic solution.

Anything like this in roadmap? if not then maybe i can take a shot at it. I am a python developer and not a jython developer though. I will need some learning curve.

Here is a sample code for printing table, column and its datatype(It can do much more like get primary key and other constraints etc.):

```

from sqlalchemy import *

engine = create_engine('mysql://wherehows:wherehows@localhost:3306/wherehows')
metadata = MetaData()
metadata.reflect(bind=engine)
for table in metadata.sorted_tables:
	#print a table
	print("TABLE: "+str(table.name))
	for column in table.c.values():
		#print a column and datatype
		print("COLUMN: "+str(column.key)+" DATATYPE: "+str(column.type))



```

Look forward to comments/suggestions on above.

**Comment by mars-lan** [comment]
Yes, please do create a PR! I'm sure this will help many of WhereHow's users and can replace the current Oracle ETL script!

**Comment by thomas-young-2013** [comment]
Looking forward to it! expected

**Comment by keremsahin1** [comment]
Dear issue owner,

Thanks for your interest in WhereHows. We have recently announced DataHub which is the rebranding of WhereHows. LinkedIn improved the architecture of WhereHows and rebranded WhereHows into DataHub and replaced its metadata infrastructure in this direction. DataHub is a more advanced and improved metadata management product compared to WhereHows. 

Unfortunately, we have to stop supporting WhereHows to better focus on DataHub and offer more help to DataHub users. Therefore, we will drop all issues related to WhereHows and will not accept any contribution for it. Active development for DataHub has already started on `datahub` branch and will continue to live in there until it's finally merged to master and project is renamed to DataHub. 

Please check the `datahub` branch to get familar with DataHub.

Best,
DataHub team
