### ISSUE TITLE
disable new packages in metadata-etl module?

### ISSUE THREAD

**Issue by wbwpyin** [linkedin/WhereHows#550]
I have a question below,
     When I added my java code files which contains new packages into the module "metadata-etl" ,  then I  used the order "./gradlew bulid" in the "Terminal" window to build the  whole WhereHows project. It always gives the error tips: "metadata-etl: licenseMain FAILED".   However, if I only add a piece of codes into the      existing files which project Wherehows have , it built  "Build Successful" . So I  was confused,  why  I  can't add my new files or directories  into the  "metadata-etl"  module  ? How could I do if I want to add my own new packages?

**Comment by alyiwang** [comment]
You might need to add the license section at the beginning of each source code file, just like the other java files.

**Comment by wbwpyin** [comment]
You are handsome! Thanks for your help~
