### ISSUE TITLE
I want to ask how I can't find dataset. Json and flow.json files in my project.

### ISSUE THREAD

**Issue by fchen521** [linkedin/WhereHows#553]
ERROR application:34 - /var/tmp/wherehows/resource/dataset.json (No such file or directory)

**Comment by ChrisJamesC** [comment]
If you look at this README: https://github.com/linkedin/WhereHows/tree/master/backend-service
you need to run the following commands: 

```
sudo mkdir /var/tmp/wherehows
sudo chmod a+rw /var/tmp/wherehows
sudo mkdir /var/tmp/wherehows/resource
```

**Comment by cfmygit** [comment]
I've already run these commands, I've got the resource directory, but I can't find the json file.

**Comment by ChrisJamesC** [comment]
Oh then I don't know sorry :( It might be that there is no data yet (I'm stuck at a similar step)

**Comment by cfmygit** [comment]
Well, thanks, I'll take a look myself

**Comment by kiranalda** [comment]
Are you running ./runBackend script ????

**Comment by keremsahin1** [comment]
Dear issue owner,

Thanks for your interest in WhereHows. We have recently announced DataHub which is the rebranding of WhereHows. LinkedIn improved the architecture of WhereHows and rebranded WhereHows into DataHub and replaced its metadata infrastructure in this direction. DataHub is a more advanced and improved metadata management product compared to WhereHows. 

Unfortunately, we have to stop supporting WhereHows to better focus on DataHub and offer more help to DataHub users. Therefore, we will drop all issues related to WhereHows and will not accept any contribution for it. Active development for DataHub has already started on `datahub` branch and will continue to live in there until it's finally merged to master and project is renamed to DataHub. 

Please check the `datahub` branch to get familar with DataHub.

Best,
DataHub team
