### ISSUE TITLE
How to use Kafka in wherehows

### ISSUE THREAD

**Issue by thomas-young-2013** [linkedin/WhereHows#560]
I want to integrate kafka into wherehows, and I have read the source relative. 
But I am confused about `what is the message producer (kafka is message middleware: producer and consumer, what does produce the message of some topic; the trigger is?)`, I have found that the consumer and processor in source code. 
Hope anyone can help me

**Comment by alyiwang** [comment]
We are experimenting a new ETL pipeline using kafka, more specifically the MetadataChangeEvent. The intention is letting the source platform (or out own ETL job) to send metadata snapshots via this event to kafka system, and WhereHows will run the consumer to get kafka messages and write to DB. 
We will have a more detailed documentation once we finalize the Event schema and the consumer.

**Comment by keremsahin1** [comment]
Dear issue owner,

Thanks for your interest in WhereHows. We have recently announced DataHub which is the rebranding of WhereHows. LinkedIn improved the architecture of WhereHows and rebranded WhereHows into DataHub and replaced its metadata infrastructure in this direction. DataHub is a more advanced and improved metadata management product compared to WhereHows. 

Unfortunately, we have to stop supporting WhereHows to better focus on DataHub and offer more help to DataHub users. Therefore, we will drop all issues related to WhereHows and will not accept any contribution for it. Active development for DataHub has already started on `datahub` branch and will continue to live in there until it's finally merged to master and project is renamed to DataHub. 

Please check the `datahub` branch to get familar with DataHub.

Best,
DataHub team
