### ISSUE TITLE
How to lineage Hive job in azkaban

### ISSUE THREAD

**Issue by xiashiwendao** [linkedin/WhereHows#572]
I have defined the flow in azkaban, jobtype is Hive, but I find it can't be analyzed for Wherehows, then I found in the log_lineage_pattern don't contain the hive type. 
I have read the log in azkaban for Hive, its complex for regx, If is there some simple solution for hive job type in azkaban?

Thanks.

**Comment by xiashiwendao** [comment]
I found in the VM version is too old, 0.0.1ver, suggest to update to latest version. In the VM version don't support Hive, just support HDFS, mygod.

**Comment by diaowenyang** [comment]
@xiashiwendao How to fix it ? Would you give some suggessions for me，Thank you.
