### ISSUE TITLE
extract vm file error 

### ISSUE THREAD

**Issue by Icrush** [linkedin/WhereHows#580]
I downloaded vm files from [ WhereHows china link](https://pan.baidu.com/s/1qXi2XWg#list/path=%2F), when I extract files with the command `7za e WhereHows-VM.7z.001`  or `7z e WhereHows-VM.7z.001` even or `7zr e WhereHows-VM.7z.001`,
it returns error

➜  /Users/libing/Downloads/WhereHows-VM > ll
total 26844864
-rw-r--r--@ 1 libing  staff   2.0G  6 27 02:05 WhereHows-VM.7z.001
-rw-r--r--@ 1 libing  staff   2.0G  6 27 01:09 WhereHows-VM.7z.002
-rw-r--r--@ 1 libing  staff   2.0G  6 27 01:00 WhereHows-VM.7z.003
-rw-r--r--@ 1 libing  staff   2.0G  6 27 01:53 WhereHows-VM.7z.004
-rw-r--r--@ 1 libing  staff   2.0G  6 27 00:34 WhereHows-VM.7z.005
-rw-r--r--@ 1 libing  staff   2.0G  6 27 01:15 WhereHows-VM.7z.006
-rw-r--r--@ 1 libing  staff   820M  6 27 01:28 WhereHows-VM.7z.007
➜  /Users/libing/Downloads/WhereHows-VM > 7za e WhereHows-VM.7z.001

7-Zip (a) [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=utf8,Utf16=on,HugeFiles=on,64 bits,4 CPUs x64)

Scanning the drive for archives:
1 file, 2147483648 bytes (2048 MiB)

Extracting archive: WhereHows-VM.7z.001
Path = WhereHows-VM.7z.001
Type = Split
Physical Size = 2147483648
Volumes = 7
Total Physical Size = 13744566617
Path = WhereHows-VM.7z
Size = 13744566617
Path = WhereHows-VM.7z
Type = 7z
Physical Size = 13744566617
Headers Size = 652
Method = LZMA:24
Solid = +
Blocks = 25
ERROR: Data Error : cloudera-quickstart-vm-5.4.2-0-vmware-s002.vmdk
ERROR: Data Error : cloudera-quickstart-vm-5.4.2-0-vmware-s003.vmdk
Sub items Errors: 2

any help would be grateful

**Comment by Icrush** [comment]
resolved .

➜  /Users/libing/Downloads/WhereHows-VM > md5 WhereHows-VM.7z.001
MD5 (WhereHows-VM.7z.001) = 8996fc9b9afc08f17edbdb4e5f4d0fde
➜  /Users/libing/Downloads/WhereHows-VM > md5 WhereHows-VM.7z.001_baidu
MD5 (WhereHows-VM.7z.001_baidu) = 2cddb960342cdd7f9f54ae90dd9593e8

I downloaded the file from two links ,found md5 is not the same 

please check it

**Comment by mars-lan** [comment]
We're in the process of deprecating the VM in favor of docker images. Keep an eye on the  wherehows-docker directory.
