### ISSUE TITLE
How to get the lineage from hive On Spark?

### ISSUE THREAD

**Issue by xiashiwendao** [linkedin/WhereHows#581]
Hi, We define a Azkaban job which built by Hive On Spar, we found that in the log don't have the Source Table info(there is just target table info), Anybody meet this question? How to resolve it?

Thank you!

**Comment by ericsun2** [comment]
I'd implement a Hive Post Execution Hook to get the source and target table/view info, and dump them to the log for the lineage instrumentation purpose.

**Comment by xiashiwendao** [comment]
Great! How to get it? just download the latest version?

**Comment by diaowenyang** [comment]
@xiashiwendao have you get lineage from wherehows ?

**Comment by keremsahin1** [comment]
Dear issue owner,

Thanks for your interest in WhereHows. We have recently announced DataHub which is the rebranding of WhereHows. LinkedIn improved the architecture of WhereHows and rebranded WhereHows into DataHub and replaced its metadata infrastructure in this direction. DataHub is a more advanced and improved metadata management product compared to WhereHows. 

Unfortunately, we have to stop supporting WhereHows to better focus on DataHub and offer more help to DataHub users. Therefore, we will drop all issues related to WhereHows and will not accept any contribution for it. Active development for DataHub has already started on `datahub` branch and will continue to live in there until it's finally merged to master and project is renamed to DataHub. 

Please check the `datahub` branch to get familar with DataHub.

Best,
DataHub team

**Comment by SemanticBeeng** [comment]
> I'd implement a Hive Post Execution Hook to get the source and target table/view info, and dump them to the log for the lineage instrumentation purpose.

Discussion in slack https://datahubspace.slack.com/archives/CUMUWQU66/p1617211779054300?thread_ts=1617189684.051700&cid=CUMUWQU66
