### ISSUE TITLE
Does it Support Pulling Metadata from Redshift/Postgres

### ISSUE THREAD

**Issue by rajivchodisetti** [linkedin/WhereHows#59]
HI ,

Does this tool support pulling the database metadata from redshift/postgres db ?

**Comment by SunZhaonan** [comment]
Not support yet, but we have planning to integrate more online data storage system soon. If you are interested in contribute, I can guide you through it. We are also very welcome for contributions :)

**Comment by rajivchodisetti** [comment]
can you please let me know what all files need to be touched for integrating a new database

**Comment by SunZhaonan** [comment]
See the comments in #60

**Comment by alisaraa** [comment]
Any update on this?
