### ISSUE TITLE
Query - How to insert multiple level lineage manually.

### ISSUE THREAD

**Issue by nikhiltanwar** [linkedin/WhereHows#591]
Right now i am able to insert single level lineage with array [{source1},{source2},{target1}] using [backend api](https://github.com/linkedin/WhereHows/wiki/Backend-API#lineage-post )
What if i want to use Target1 as another source in same flow and feed to new target 2 . How will i achieve multiple levels in this. does the order in the array matter? Sorry wiki documentation lacks this info hence asking.

**Comment by dmoore247** [comment]
I called the API twice, I get something like below, I'm sure we both want all the objects connected.

![image](https://user-images.githubusercontent.com/1122251/28128863-36a665d2-66ff-11e7-85af-d727b900294c.png)

**Comment by nikhiltanwar** [comment]
Yes exactly! I am not sure if array is the right data structure to connect multi level lineage but it might work partially here but its not given in documentation. 
 @mars-lan Please help us with your comment on above if its possible to have multiple level lineage connections in one view. Not sure if you are right person to answer this backend api question though.

**Comment by diaowenyang** [comment]
@nikhiltanwar @dmoore247 I cannot get any infomations about lineage,Can you give me some help, How get lineage by wherehows ?

**Comment by nikhiltanwar** [comment]
@diaowenyang  to understand everything, i suggest you try to insert the lineage from REST API 

That is the best way to understand how the data model is getting filled.

**Comment by keremsahin1** [comment]
Dear issue owner,

Thanks for your interest in WhereHows. We have recently announced DataHub which is the rebranding of WhereHows. LinkedIn improved the architecture of WhereHows and rebranded WhereHows into DataHub and replaced its metadata infrastructure in this direction. DataHub is a more advanced and improved metadata management product compared to WhereHows. 

Unfortunately, we have to stop supporting WhereHows to better focus on DataHub and offer more help to DataHub users. Therefore, we will drop all issues related to WhereHows and will not accept any contribution for it. Active development for DataHub has already started on `datahub` branch and will continue to live in there until it's finally merged to master and project is renamed to DataHub. 

Please check the `datahub` branch to get familar with DataHub.

Best,
DataHub team
