### ISSUE TITLE
User authentication, only support for LDAP?

### ISSUE THREAD

**Issue by BillLucky** [linkedin/WhereHows#598]
If i want to use the database authentication, then how to configure?

The document describes too little and can not be installed according to the document.

  -- Looking forward to your reply, thank you

**Comment by mars-lan** [comment]
We currently only support LDAP-based authentication. There's plan to migrate to JAAS in the future to support many more options.

**Comment by BillLucky** [comment]
If this is the case, it would like to build the environment are very strenuous ah, if there is no use of LDAP?

It is recommended to support the configuration file to manually control the choice of authentication, thank you.

**Comment by jywadhwani** [comment]
We are now supporting other forms of authentication methods/modules using JAAS (relevant PR: https://github.com/linkedin/WhereHows/pull/1280). Closing this issue, feel free to create new one if there are questions.
