### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by rajivchodisetti** [linkedin/WhereHows#60]
HI ,

I am trying to build it on my mac and running into the below issue , Any idea on how to fix it ?

EN-RajivC:metadata-etl rajiv.chodisetti$ gradle build
Defining custom 'build' task when using the standard Gradle lifecycle plugins has been deprecated and is scheduled to be removed in Gradle 3.0
:wherehows-common:compileJava
/Users/rajiv.chodisetti/WhereHows/wherehows-common/src/main/java/wherehows/common/utils/PartitionPatternMatcher.java:30: error: ')' expected
    Collections.sort(layoutList, (PartitionLayout o1, PartitionLayout o2) -> o1.getSortId().compareTo(o2.getSortId()));
                                                 ^
/Users/rajiv.chodisetti/WhereHows/wherehows-common/src/main/java/wherehows/common/utils/PartitionPatternMatcher.java:30: error: ')' expected
    Collections.sort(layoutList, (PartitionLayout o1, PartitionLayout o2) -> o1.getSortId().compareTo(o2.getSortId()));
                                                                     ^
/Users/rajiv.chodisetti/WhereHows/wherehows-common/src/main/java/wherehows/common/utils/PartitionPatternMatcher.java:30: error: illegal start of expression
    Collections.sort(layoutList, (PartitionLayout o1, PartitionLayout o2) -> o1.getSortId().compareTo(o2.getSortId()));
                                                                        ^
/Users/rajiv.chodisetti/WhereHows/wherehows-common/src/main/java/wherehows/common/utils/PartitionPatternMatcher.java:30: error: illegal start of expression
    Collections.sort(layoutList, (PartitionLayout o1, PartitionLayout o2) -> o1.getSortId().compareTo(o2.getSortId()));
                                                                           ^
/Users/rajiv.chodisetti/WhereHows/wherehows-common/src/main/java/wherehows/common/utils/PartitionPatternMatcher.java:30: error: ';' expected
    Collections.sort(layoutList, (PartitionLayout o1, PartitionLayout o2) -> o1.getSortId().compareTo(o2.getSortId()));
                                                                                                                     ^
5 errors
:wherehows-common:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':wherehows-common:compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 4.9 secs

**Comment by czbernard** [comment]
Seems like the gradle build does not recognize Java 8 syntax, what is the JDK version in your mac?

**Comment by SunZhaonan** [comment]
Looks like the java version problem, are you using java 8 on your mac?

**Comment by rajivchodisetti** [comment]
Thanks guys , yes this is a java version problem , have switched to 1.7 to build some other project and forgot to revert it back to 1.8  :) 

Now the build is successful and when I am launching the UI and getting the below exception , does the application come with some sample data sets to play with or not ?

[error] application - /var/tmp/wherehows/resource/dataset.json (No such file or directory)
[error] application - /var/tmp/wherehows/resource/flow.json (No such file or directory)

**Comment by SunZhaonan** [comment]
Thank you for catch up this. This two files are used for tree directory in the front end. They need to generate by backend service, which means you have to run one of the dataset collecting process (HDFS or Teradata or Hive) and one of the execution collecting process (Azkaban or Oozie). The set up process instruction is here : https://github.com/linkedin/WhereHows/wiki/Set-Up-New-Metadata-ETL-Jobs

 We could put a sample json there to show up the tree directory. But even after that if database is empty, they are all not clickable, and show empty pages. But this exception should be fixed @jerrybai2009 .


If you want to quick play with it, the easiest way is play with VM, there are several samples in it : https://github.com/linkedin/WhereHows/wiki/Quick-Start-With-VM .

**Comment by rajivchodisetti** [comment]
Thank you for the immediate responses . But unfortunately we are neither using HDFS or Teradata or Hive , We run EMR on AWS and the source systems are all Mysql,Cassandra and Mongo and the datawarehouse is running on top of Redshift(Postgres driver should work ) .

So I don't think we will be able to play with it and see if it fit for our organizational needs but any how thanks again for the support

**Comment by SunZhaonan** [comment]
No two companies will use the same data ecosystems. As a data management tools whose core part is integration, this is the major pain point when we considering open source. Our solution is the data model we have for WhereHows is a very general data model, and ETL part need to highly customized based on the source systems used in different companies. When onboarding a new source systems, (say, Redshift), what you need to do is add a new job type, and write your own ETL scripts, fetch metadata to fit in the data model. Here is a brief version of integration guide :(https://github.com/linkedin/WhereHows/wiki/Integration-Guide) . I'll definitely write more detail in future.

**Comment by ashitabh** [comment]
VM Player is just hanging at step
**Starting Wherehows..
loginLoggerObjName is null, make sure there is a logger with name azkaban.webapp.servelet.LoginAbstractAzkabanServlet **

Any idea how to get around this issue?
thanks
