### ISSUE TITLE
package gudusoft.gsqlparser does not exist

### ISSUE THREAD

**Issue by kiranalda** [linkedin/WhereHows#613]
I am getting this error : - 
package gudusoft.gsqlparser does not exist

I Want to know which is the dependent jar?

**Comment by shpark76** [comment]
It's a SQLParser jar package. Download it from this blow link, then copy a gsp.jar into wherehows-etl/extralibs.
http://www.sqlparser.com/dlaction.php?fid=gspjava&ftitle=General%20SQL%20Parser%20Java%20version

Document link:
https://github.com/linkedin/WhereHows/tree/master/wherehows-etl/extralibs
