### ISSUE TITLE
How to establish a blood relationship to the two tables?

### ISSUE THREAD

**Issue by BillLucky** [linkedin/WhereHows#619]
Version used: WhereHows 0.2.1
Has now been built successfully, and the Hive metadata has been extracted to the system, would like to establish the relationship between the various table, but can not be established.

I read the wiki on the instructions or failed to understand the two table is how to set up how to set up.
All the API I have tested, unable to establish the relationship between the line, I understand that: there should be an api can be passed into the two dataset id them together, but there is no such api?

**Comment by BillLucky** [comment]
Lineage is collected from the log inside? Not specified by API? Very strange ah

**Comment by keremsahin1** [comment]
Dear issue owner,

Thanks for your interest in WhereHows. We have recently announced DataHub which is the rebranding of WhereHows. LinkedIn improved the architecture of WhereHows and rebranded WhereHows into DataHub and replaced its metadata infrastructure in this direction. DataHub is a more advanced and improved metadata management product compared to WhereHows. 

Unfortunately, we have to stop supporting WhereHows to better focus on DataHub and offer more help to DataHub users. Therefore, we will drop all issues related to WhereHows and will not accept any contribution for it. Active development for DataHub has already started on `datahub` branch and will continue to live in there until it's finally merged to master and project is renamed to DataHub. 

Please check the `datahub` branch to get familar with DataHub.

Best,
DataHub team

**Comment by BillLucky** [comment]
okay, thank you @keremsahin1
