### ISSUE TITLE
Incorrect query generated when hierarchy is empty

### ISSUE THREAD

**Issue by wenhuaOpenx** [linkedin/WhereHows#661]
When no users in hierarchy list, generated query would be 

                           update <table> stg
                            set org_hierarchy = CASE  END,
                                org_hierarchy_depth = CASE  END
                            where app_id = <app_id> and user_id in ()

https://github.com/linkedin/WhereHows/blob/b02c386da1473556aee2c758853709ecb81011f4/wherehows-etl/src/main/resources/jython/LdapTransform.py#L186

Can you help test the case of empty hierarchy as well, and see if the query works fine?

**Comment by alyiwang** [comment]
You are right, if there is no users, then the generated SQL is invalid. though we never run into trouble in production due to this case. 
In general, those manually generated SQL statement in this Py code is UGLY and should be replaced by SQL parameters or data persist frameworks. Modifying LDAP ETL is not currently our priority, thus we welcome any contribution to make it better!

**Comment by keremsahin1** [comment]
Dear issue owner,

Thanks for your interest in WhereHows. We have recently announced DataHub which is the rebranding of WhereHows. LinkedIn improved the architecture of WhereHows and rebranded WhereHows into DataHub and replaced its metadata infrastructure in this direction. DataHub is a more advanced and improved metadata management product compared to WhereHows. 

Unfortunately, we have to stop supporting WhereHows to better focus on DataHub and offer more help to DataHub users. Therefore, we will drop all issues related to WhereHows and will not accept any contribution for it. Active development for DataHub has already started on `datahub` branch and will continue to live in there until it's finally merged to master and project is renamed to DataHub. 

Please check the `datahub` branch to get familar with DataHub.

Best,
DataHub team
