### ISSUE TITLE
VM Player is just hanging at step Starting Wherehows...

### ISSUE THREAD

**Issue by ashitabh** [linkedin/WhereHows#68]
VM Player is just hanging at step
Starting Wherehows..
loginLoggerObjName is null, make sure there is a logger with name azkaban.webapp.servelet.LoginAbstractAzkabanServlet 

Any idea how to get around this issue?
thanks

**Comment by jpegado** [comment]
I'm getting the same error. VM starts, CentOS load bar is full, but then it gets stuck at that error.
I've downloaded the VM image yesterday.

Can anyone help?

Thanks

**Comment by ericsun2** [comment]
We have uploaded a new VM image to address this issue.

You can also quickly fix this issue by starting the VM in single user mode and removing "**wait**" from the **/home/cloudera/wherehows/runfrontend** shell script

**Comment by jpegado** [comment]
Thank you so much ericsun2! removing the "wait" solved the problem!

Cheers,
Joao

**Comment by ashitabh** [comment]
Thanks Eric Sun,
It worked after removing "wait"
