### ISSUE TITLE
How to generate application secret for WhereHows to run in prod mode?

### ISSUE THREAD

**Issue by huangjun** [linkedin/WhereHows#706]
"./gradlew wherehows-backend:runPlayBinary" or "./gradlew wherehows-frontend:runPlayBinary" works well with source code checked out.

When I tried to extract the zip files under distributions to run bin/playBinary directly, the started service complained about "application secret is not set". Tried to use activator to generate the secret but WhereHows does not seem to be an activator project. Any pointers? Thanks!

**Comment by diaowenyang** [comment]
请问这个问题石怎么修复的？
