### ISSUE TITLE
VM - Data Lineage rendering issue

### ISSUE THREAD

**Issue by jpegado** [linkedin/WhereHows#71]
Hi,

I'm using the VM (downloaded in 07/03/2016) to get to know the tool.
Although, I'm having some problems visualizing the Data lineage in the Front End, when I select one flow or dataset.

if I select a dataset, only the dataset box appears, and if I select a job (for instance the one shown in "Front User Guide" EmployeeAnalyze) it does show nothing but the job's name on top right.

Can anyone help?
Thank you.
Joao

**Comment by SunZhaonan** [comment]
Hi,

The lineage default show recent 30 days jobs lineage. It looks like the VM haven't run those job for a long time. We'll upload a new version VM soon. You can also try this on your VM:

1  open azkaban : localhost:8081, login as azkaban, run the sample jobs of 'twitter' and 'retail'
2  make sure the backend service is running : ```cd ~/wherehows; ./runbackend```
3  activate the `AZKABAN_LINEAGE_METADATA_ETL` job and `AZKABAN_EXECUTION_METADATA_ETL` job by API : 

```
curl -H "Content-Type: application/json" -X PUT -d '{"wh_etl_job_name":"AZKABAN_LINEAGE_METADATA_ETL", "ref_id":1, "control":"activate"}' http://localhost:19001/etl/control 
```
``` 
curl -H "Content-Type: application/json" -X PUT -d '{"wh_etl_job_name":"AZKABAN_EXECUTION_METADATA_ETL", "ref_id":1, "control":"activate"} 'http://localhost:19001/etl/control 
```

4 You can check the backend log by ```tail -f /var/tmp/wherehows/wherehows.log```

After you see these two jobs have been finished, refresh the wherehows page, you should be able to see the lineage.

**Comment by jpegado** [comment]
Hi,

Thanks a lot. It worked!

Cheers

**Comment by SunZhaonan** [comment]
This actually is a good way to let user know how WhereHows works. I'll update these steps into the documents. Thank you @jpegado
