### ISSUE TITLE
login wherehows stuck in 94% at wherehows-frontend and 96% at wherehows-backend

### ISSUE THREAD

**Issue by diaowenyang** [linkedin/WhereHows#724]
Hello
When I execute “cd wherehows-frontend and ../gradlew runPlayBinary”，9001 port has been monitored, but the progress has been stuck in 94%.

When I execute “cd wherehows-backend and ../gradlew runPlayBinary”，19001 port has been monitored, but the progress has been stuck in 96%.

Without any errors?

---- wherehows-frontend logs:
 - dist/legacy-app/vendors/json.human.js-master/lib/require-5d0408926b69adbf55ee1056a4590d02.js: 80.69 KB (19.75 KB gzipped)
 - dist/legacy-app/vendors/json.human.js-master/src/json.human-26df5c11f2989387e2b17e8ab43c2457.js: 11.39 KB (2.51 KB gzipped)
 - dist/legacy-app/vendors/jsondiffpatch-master/annotated-c1dfb644a780a5026a045249445ea73d.css: 895 B (307 B gzipped)
 - dist/legacy-app/vendors/jsondiffpatch-master/diff_match_patch_uncompressed-349510f2ba2666a778e520ac59cd2c08.js: 73.37 KB (17.35 KB gzipped)
 - dist/legacy-app/vendors/jsondiffpatch-master/html-641b734971c4ea90e9ffb68ccb41ac8d.css: 3.45 KB (736 B gzipped)
 - dist/legacy-app/vendors/jsondiffpatch-master/jsondiffpatch-formatters.min-9f798d40f91c6211cce03ed889b305bf.js: 14.15 KB (4.22 KB gzipped)
 - dist/legacy-app/vendors/jsondiffpatch-master/jsondiffpatch.min-aabe77f81a3f5661e2941fed093f0f3a.js: 20.75 KB (5.64 KB gzipped)
 - dist/legacy-app/vendors/marked/lib/marked-46fab518da76a0692a5e37f7ac9625b1.js: 27.55 KB (6.91 KB gzipped)
 - dist/legacy-app/vendors/toastr/toastr-102e236cca470fc1a211d29acd8e9ed4.css: 6.82 KB (2.89 KB gzipped)
 - dist/legacy-app/vendors/toastr/toastr-e4018d6f3414664a50b9b860e7ee9c4c.js: 15.98 KB (3.14 KB gzipped)
 - dist/legacy-app/vendors/toastr/toastr.min-c4d50504a82305d607ae5ff7b33e0c39.css: 5.85 KB (2.68 KB gzipped)
 - dist/legacy-app/vendors/toastr/toastr.min-d59436971aa13b0e0c24d4332543fbef.js: 4.87 KB (1.91 KB gzipped)
 - dist/moment/fastboot-moment-62eb34042848ca105b39d48fa2474ea3.js: 95 B (97 B gzipped)
 - dist/moment/fastboot-moment-timezone-abadb8be73831ba0ff2208c313da0af0.js: 104 B (107 B gzipped)

--- (Running the application, auto-reloading is enabled) ---

[info] p.c.s.NettyServer - Listening for HTTP on /0:0:0:0:0:0:0:0:9001
2017-09-04 19:09:49 INFO  p.a.Play:97 - Application started (Dev)
2017-09-04 19:09:51 INFO  application:81 - Creating DAO factory: wherehows.dao.DaoFactory
<============-> 94% EXECUTING [1h 0m 55s]
> :wherehows-frontend:runPlayBinary > Running at http://localhost:9001/

---- wherehows-backend logs:
Mon Sep 04 19:13:39 CST 2017 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
Mon Sep 04 19:13:39 CST 2017 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
Mon Sep 04 19:13:39 CST 2017 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
Mon Sep 04 19:13:39 CST 2017 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
Mon Sep 04 19:13:39 CST 2017 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
2017-09-04 19:13:39 INFO  application:65 - Enabled jobs: []
2017-09-04 19:13:39 INFO  application:68 - Scheduled jobs: {}
<============-> 96% EXECUTING [1h 2m 44s]
> :wherehows-backend:runPlayBinary > Running at http://localhost:19001/

**Comment by mars-lan** [comment]
This is an expected behavior from the gradle play plugin. Updated the Getting Started guide with more info on this: https://github.com/linkedin/WhereHows/blob/master/wherehows-docs/getting-started.md#development
