### ISSUE TITLE
how to load hive

### ISSUE THREAD

**Issue by diaowenyang** [linkedin/WhereHows#725]
I configured this file HIVE_METADATA_ETL.job，how to load hive metedata to Wherehows?
{
    "wh_etl_job_name": "HIVE_DATASET_METADATA_ETL",
    "ref_id": 10001,
    "cron_expr": "* * * * * ?",
    "properties": {
        "hive.metastore.jdbc.url": "jdbc:mysql://localhost/hive",
        "hive.metastore.jdbc.driver": "com.mysql.jdbc.Driver",
        "hive.metastore.username": "wherehows",
        "hive.metastore.password": "wherehows",
        "hive.schema_json_file": "/home/schema.json",
        "hive.schema_csv_file": "/home/schema.csv",
        "hive.field_metadata": "/home/field.csv",
        "hive.hdfs_map_csv_file": "/home/hdfs.csv",
        "hdfs.namenode.ipc.uri": "hdfs://localhost:8020",
        "kerberos.auth": "false"
    },
    "timeout": null,
    "next_run": null,
    "comments": "hive vm metadata etl"
}

**Comment by rilma** [comment]
I would like to do exactly like this, for example.

**Comment by rahultw** [comment]
facing the same issue. How to load hive metadata?

**Comment by mars-lan** [comment]
@yinsong this was an issue opened for WhereHows, which we no longer support. Please refer to https://github.com/linkedin/datahub/tree/master/metadata-ingestion/sql-etl for how this is done for DataHub.
