### ISSUE TITLE
Compilation failed when run "build.sh 1" command

### ISSUE THREAD

**Issue by lufeng1102** [linkedin/WhereHows#775]
Hi All, I want to deploy wherehows v1.0.0 using docker. But it throw complication failed when run the "build.sh 1" command. Following is part of the error result. How can I solve this issue?

`  符号:   类 TSelectSqlStatement
  位置: 类 InsertStmt
/home/work/lufeng/WhereHows/wherehows-etl/src/main/java/metadata/etl/sqlParser/InsertStmt.java:51: 错误: 找不到符号
            case TBaseType.vt_query:
                 ^
  符号:   变量 TBaseType
  位置: 类 InsertStmt
/home/work/lufeng/WhereHows/wherehows-etl/src/main/java/metadata/etl/sqlParser/InsertStmt.java:52: 错误: 找不到符号
                TSelectSqlStatement subQuery = stmt.getSubQuery();
                ^
  符号:   类 TSelectSqlStatement
  位置: 类 InsertStmt
97 个错误
12 个警告
:wherehows-etl:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':wherehows-etl:compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 8.993 secs`

**Comment by lufeng1102** [comment]
fixed this issue by download the extra libraries for etl module.

**Comment by cpalomaressbd** [comment]
How did you do it?
