### ISSUE TITLE
Some questions about integrating kafka. Please~ 

### ISSUE THREAD

**Issue by Seandity** [linkedin/WhereHows#792]
There have consumer and processor  but no producer, I am confused where is origin topic messages that is received by  the topic-specific work-processor. (work on v0.2.1)

**Comment by ericsun2** [comment]
Right now, consumer + processor is used to ingest audit topics, such as Hive Metadata Change, Gobblin Tracking, ...
Are you looking for a code module which generates/produces Kafka events, such as WH Metadata Change, WH ETL State, ...?
AFAIK, the producer and corresponding topic schema is coming into the oss codebase.

**Comment by Seandity** [comment]
emm，now,Iam understand ,no matter how Gobblin Tracking or other produces, they all provide production data outside the entire cluster。So there have many forms of producer, not only kafka Pro. 
This part of the function for wherehows maybe just is a consumer  : )

**Comment by keremsahin1** [comment]
Dear issue owner,

Thanks for your interest in WhereHows. We have recently announced DataHub which is the rebranding of WhereHows. LinkedIn improved the architecture of WhereHows and rebranded WhereHows into DataHub and replaced its metadata infrastructure in this direction. DataHub is a more advanced and improved metadata management product compared to WhereHows. 

Unfortunately, we have to stop supporting WhereHows to better focus on DataHub and offer more help to DataHub users. Therefore, we will drop all issues related to WhereHows and will not accept any contribution for it. Active development for DataHub has already started on `datahub` branch and will continue to live in there until it's finally merged to master and project is renamed to DataHub. 

Please check the `datahub` branch to get familar with DataHub.

Best,
DataHub team
