### ISSUE TITLE
OozieExtract querys run too slow

### ISSUE THREAD

**Issue by lfyzjck** [linkedin/WhereHows#832]
When i configure oozie etl job, it execute a query like this:

```
 SELECT a.*, b.created_time FROM
              (SELECT w.app_name, w.app_path, max(w.id) as source_version, max(unix_timestamp(w.last_modified_time)) as last_modified_time
              from WF_JOBS w LEFT JOIN WF_JOBS s
              ON w.app_path = s.app_path AND w.created_time < s.created_time
              WHERE s.created_time IS NULL GROUP BY w.app_name, w.app_path) a
              JOIN
              (SELECT app_path, min(unix_timestamp(created_time)) as created_time FROM WF_JOBS GROUP BY app_path) b
              ON a.app_path = b.app_path;
```

The query use too many `JOIN` and has token hours to run : 
```
mysql> show processlist;
+-----+------+-----------------+-----------+---------+------+--------------+------------------------------------------------------------------------------------------------------+
| Id  | User | Host            | db        | Command | Time | State        | Info                                                                                                 |
+-----+------+-----------------+-----------+---------+------+--------------+------------------------------------------------------------------------------------------------------+
| 106 | root | localhost:55327 | oozie     | Query   | 2370 | Sending data | SELECT a.*, b.created_time FROM
              (SELECT w.app_name, w.app_path, max(w.id) as source_ve |
```

While i had 50w records in table `WF_JOBS`:
```
mysql> select count(*) from WF_JOBS;
+----------+
| count(*) |
+----------+
|   499979 |
+----------+
1 row in set (0.22 sec)
```

**Comment by keremsahin1** [comment]
Dear issue owner,

Thanks for your interest in WhereHows. We have recently announced DataHub which is the rebranding of WhereHows. LinkedIn improved the architecture of WhereHows and rebranded WhereHows into DataHub and replaced its metadata infrastructure in this direction. DataHub is a more advanced and improved metadata management product compared to WhereHows. 

Unfortunately, we have to stop supporting WhereHows to better focus on DataHub and offer more help to DataHub users. Therefore, we will drop all issues related to WhereHows and will not accept any contribution for it. Active development for DataHub has already started on `datahub` branch and will continue to live in there until it's finally merged to master and project is renamed to DataHub. 

Please check the `datahub` branch to get familar with DataHub.

Best,
DataHub team
