### ISSUE TITLE
Kerberos Support

### ISSUE THREAD

**Issue by carnalim** [linkedin/WhereHows#84]
Do you guys support Kerberos? I can't seem to find any documentation on using something like a keytab to allow the HDFS crawler the ability to maybe run as a super user that can look into any file or something of that nature.

**Comment by SunZhaonan** [comment]
We use private key to login into remote machine, then run the job as that remote user.
The HDFS dataset configuration is here : https://github.com/linkedin/WhereHows/wiki/Hdfs-Dataset#configuration
Set the `hdfs.remote.user` and `hdfs.private_key_location` then it should be good.

We are working on a way to dynamically proxy to the folder owner (this user need to have permission to proxy to any user). Will create the pull request soon.

**Comment by carnalim** [comment]
Just would like to know more around the thought process of, if we were to use this Tool, we would want to capture everything in the cluster as a holistic meta data catalog. In order to do that we would need to run as a super user or a user in HDFS's supergroup correct? Because we can't use Kerberos to essentially impersonate HDFS user when we run jobs. 

Your proposed solution seems like you have every user or system ID logging in an keeping track of their own things rather a mandatory user doing all the work? Is that correct in my thinking?

**Comment by SunZhaonan** [comment]
* Right now the code in HDFS metadata ETL does not have Kerberos login part, as in VM there is no security restriction. But inside Linkedin we did use Kerberos to manage the security issue, I'll push this part as an optional way later. 

* Right now it can only read the files that is 'readable to all'. What we plan to do is login as a 'super user' and use this 'super user' to proxy to each folder's owner to fetch the metadata.  The 'super user' I refer to here is a proxy user : https://hadoop.apache.org/docs/current/hadoop-project-dist/hadoop-common/Superusers.html . All schedulers such as Azkaban, Oozie have this kind of proxy user so they can execute jobs as others. It need extra configuration on hdfs site xml, but not too complex, I'll update the docs after this is done.

* For your question about ` why would I want a user to proxy into a bunch of other users vs just one user to do everything for me.` . I guess the 'super user' your refer to is admin users such as 'hdfs' . It's too risky to use that account in an application, and grid ops guys won't let this happened :( .

**Comment by SunZhaonan** [comment]
Solved in #88
