### ISSUE TITLE
Demo data for Docker

### ISSUE THREAD

**Issue by tomsej** [linkedin/WhereHows#854]
Do you think it would be possible to share some demo data for current Docker container. It is really hard to test new version of WhereHows without any data, documentation and with a lot of schema changes between versions.

**Comment by rilma** [comment]
Hello @tomsej , I have satisfactorily installed the WhereHows project using the Docker Compose script available at "WhereHows/wherehows-docker". When I open "http://localhost:9001" in my browser, the interface is requesting my credentials (e.g. Login/User and Password). Any idea how I can set them up before installing the WhereHows package?

**Comment by camelliazhang2018** [comment]
@tomsej Yes, we do have plan to add demo data into docker. We will get you updated once it is available.

**Comment by keremsahin1** [comment]
Dear issue owner,

Thanks for your interest in WhereHows. We have recently announced DataHub which is the rebranding of WhereHows. LinkedIn improved the architecture of WhereHows and rebranded WhereHows into DataHub and replaced its metadata infrastructure in this direction. DataHub is a more advanced and improved metadata management product compared to WhereHows. 

Unfortunately, we have to stop supporting WhereHows to better focus on DataHub and offer more help to DataHub users. Therefore, we will drop all issues related to WhereHows and will not accept any contribution for it. Active development for DataHub has already started on `datahub` branch and will continue to live in there until it's finally merged to master and project is renamed to DataHub. 

Please check the `datahub` branch to get familar with DataHub.

Best,
DataHub team
