### ISSUE TITLE
wherehows docker error

### ISSUE THREAD

**Issue by diaowenyang** [linkedin/WhereHows#866]
HI:
  I use v1.1.0.
  and in WhereHows/wherehows-docker run " sudo sh build.sh 1 --stacktrace"

  Error fellows:
:wherehows-backend:createPlayBinaryAssetsJar UP-TO-DATE
:wherehows-backend:compilePlayBinaryPlayRoutes UP-TO-DATE
:wherehows-backend:compilePlayBinaryPlayTwirlTemplates UP-TO-DATE
:wherehows-common:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':wherehows-common:compileJava'.
> Could not find tools.jar. Please check that /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.144-0.b01.el7_4.x86_64/jre contains a valid JDK installation.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 5.487 secs

How to fix it ?

**Comment by rilma** [comment]
You have to make sure you have the correct configuration before building the Docker container. Here few steps to help you out (under Ubuntu):

1. Install the Java Development Kit (at least the Java Runtime Environment)
2. Define the JAVA_HOME environment variable
3. Install the latest Docker Compose (e.g. I have installed v1.17)
4. At the home directory (e.g. WhereHows/) run `$ ./gradlew clean build`, or simply `./gradlew build` is there is nothing to be cleaned.
5. If step 4 works fine, go to the Docker Compose folder (e.g WhereHows/wherehows-docker/) then run `./build.sh 1`. If everything goes fine, you should be able to start the services by running `docker-compose up`.

Hope it works for you!

**Comment by diaowenyang** [comment]
@rilma Thank you so much!
I use your ways to do,it's useful!
But I meet new question:


Additional error details:
Since bower is a user command, there is no need to execute it with superuser permissions.
If you're having permission errors when using bower without sudo, please spend a few minutes learning more about how your system should work and make any necessary repairs.

http://www.joyent.com/blog/installing-node-and-npm
https://gist.github.com/isaacs/579814

You can however run a command with sudo using --allow-root option
:wherehows-web:bowerInstall FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':wherehows-web:bowerInstall'.
> Process 'command '/home/wherehows/WhereHows-1.0/WhereHows/wherehows-web/build/nodejs/node-v7.8.0-linux-x64/bin/node'' finished with non-zero exit value 1

Do you konw how to fix it ?

**Comment by diaowenyang** [comment]
@rilma It works !  Thank you very much!

**Comment by diaowenyang** [comment]
@rilma 
HI  rilma:
   I meet new error:
   Everything goes fine,until I run "docker-compose up"
   
 ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a version of "2" (or "2.0") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.

How to fix it ?

**Comment by rilma** [comment]
It's because your system doesn't have the latest Docker Compose. It's stated in item #3 from my previous message. Please, go to the [official site](https://docs.docker.com/compose/install/) and get the correction installation instructions according to your system.

**Comment by diaowenyang** [comment]
HI @rilma ：
When I install docker-compose 1.15.0,then run docker-compose up,I meet new error:

wherehows-backend_1   | 2017-11-23 02:48:00 INFO  application:55 - Creating Pool for datasource 'wherehows'
wherehows-frontend_1  | NettyServer.main is deprecated. Please start your Play server with the ${ProdServerStart.getClass.getName}.main.
wherehows-backend_1   | 2017-11-23 02:48:00 INFO  p.a.d.DefaultDBApi:45 - Database [wherehows] connected at jdbc:mysql://wherehows-mysql:3306/wherehows
wherehows-frontend_1  | Some(ConfigOrigin(application.conf @ jar:file:/application/lib/wherehows-frontend.jar!/application.conf))
wherehows-frontend_1  | Oops, cannot start the server.
wherehows-frontend_1  | Configuration error: Configuration error[application.conf @ jar:file:/application/lib/wherehows-frontend.jar!/application.conf: 77: Could not resolve substitution to a value: ${WHZ_ES_METRIC_URL}]
wherehows-frontend_1  | 	at play.api.Configuration$.configError(Configuration.scala:180)
wherehows-frontend_1  | 	at play.api.Configuration$.load(Configuration.scala:103)
wherehows-frontend_1  | 	at play.core.server.ProdServerStart$.readServerConfigSettings(ProdServerStart.scala:81)
wherehows-frontend_1  | 	at play.core.server.ProdServerStart$.start(ProdServerStart.scala:42)
wherehows-frontend_1  | 	at play.core.server.ProdServerStart$.main(ProdServerStart.scala:27)
wherehows-frontend_1  | 	at play.core.server.NettyServer$.main(NettyServer.scala:232)
wherehows-frontend_1  | 	at play.core.server.NettyServer.main(NettyServer.scala)
wherehows-frontend_1  | Caused by: com.typesafe.config.ConfigException$UnresolvedSubstitution: application.conf @ jar:file:/application/lib/wherehows-frontend.jar!/application.conf: 77: Could not resolve substitution to a value: ${WHZ_ES_METRIC_URL}
wherehows-frontend_1  | 	at com.typesafe.config.impl.ConfigReference.resolveSubstitutions(ConfigReference.java:108)
wherehows-frontend_1  | 	at com.typesafe.config.impl.ResolveContext.realResolve(ResolveContext.java:179)
wherehows-frontend_1  | 	at com.typesafe.config.impl.ResolveContext.resolve(ResolveContext.java:142)
wherehows-frontend_1  | 	at com.typesafe.config.impl.SimpleConfigObject$ResolveModifier.modifyChildMayThrow(SimpleConfigObject.java:379)
wherehows-frontend_1  | 	at com.typesafe.config.impl.SimpleConfigObject.modifyMayThrow(SimpleConfigObject.java:312)
wherehows-frontend_1  | 	at com.typesafe.config.impl.SimpleConfigObject.resolveSubstitutions(SimpleConfigObject.java:398)
wherehows-frontend_1  | 	at com.typesafe.config.impl.ResolveContext.realResolve(ResolveContext.java:179)
wherehows-frontend_1  | 	at com.typesafe.config.impl.ResolveContext.resolve(ResolveContext.java:142)
wherehows-frontend_1  | 	at com.typesafe.config.impl.SimpleConfigObject$ResolveModifier.modifyChildMayThrow(SimpleConfigObject.java:379)
wherehows-frontend_1  | 	at com.typesafe.config.impl.SimpleConfigObject.modifyMayThrow(SimpleConfigObject.java:312)
wherehows-frontend_1  | 	at com.typesafe.config.impl.SimpleConfigObject.resolveSubstitutions(SimpleConfigObject.java:398)
wherehows-frontend_1  | 	at com.typesafe.config.impl.ResolveContext.realResolve(ResolveContext.java:179)
wherehows-frontend_1  | 	at com.typesafe.config.impl.ResolveContext.resolve(ResolveContext.java:142)
wherehows-frontend_1  | 	at com.typesafe.config.impl.SimpleConfigObject$ResolveModifier.modifyChildMayThrow(SimpleConfigObject.java:379)
wherehows-frontend_1  | 	at com.typesafe.config.impl.SimpleConfigObject.modifyMayThrow(SimpleConfigObject.java:312)
wherehows-frontend_1  | 	at com.typesafe.config.impl.SimpleConfigObject.resolveSubstitutions(SimpleConfigObject.java:398)
wherehows-frontend_1  | 	at com.typesafe.config.impl.ResolveContext.realResolve(ResolveContext.java:179)
wherehows-frontend_1  | 	at com.typesafe.config.impl.ResolveContext.resolve(ResolveContext.java:142)
wherehows-frontend_1  | 	at com.typesafe.config.impl.ResolveContext.resolve(ResolveContext.java:231)
wherehows-frontend_1  | 	at com.typesafe.config.impl.SimpleConfig.resolveWith(SimpleConfig.java:74)
wherehows-frontend_1  | 	at com.typesafe.config.impl.SimpleConfig.resolve(SimpleConfig.java:64)
wherehows-frontend_1  | 	at com.typesafe.config.impl.SimpleConfig.resolve(SimpleConfig.java:59)
wherehows-frontend_1  | 	at com.typesafe.config.impl.SimpleConfig.resolve(SimpleConfig.java:37)
wherehows-frontend_1  | 	at play.api.Configuration$.load(Configuration.scala:99)
wherehows-frontend_1  | 	... 5 more
wherehows-frontend_1  | 2017/11/23 02:48:00 Command exited with error: exit status 255
wherehows-backend_1   | 2017-11-23 02:48:01 INFO  application:34 - on start---===
wherehowsdocker_wherehows-frontend_1 exited with code 255


How to fix it?
