### ISSUE TITLE
Build Failed!

### ISSUE THREAD

**Issue by rilma** [linkedin/WhereHows#867]
I have cloned the master repository and make sure to have the JAVA_HOME environment variable correct in my system (Ubuntu 16.04). When I run "./gradlew build" in the WhereHows directory, I get the following output at prompt, indicated that 3 test has failed (see below). I would love to hear what I am missing in the installation process.. Thanks!

##################################################################
> Task :wherehows-common:compileJava
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :wherehows-data-model:generateAvroJava
[WARNING] Avro: Invalid default for field state: null not a ["string"]
[WARNING] Avro: Invalid default for field state: null not a [{"type":"string","avro.java.string":"String"}]

> Task :wherehows-data-model:compileJava
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :wherehows-dao:compileJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :wherehows-hadoop:compileJava
Note: /home/rilma/Documents/Python/DataCatalog/WhereHows/wherehows-hadoop/src/main/java/wherehows/ParquetFileAnalyzer.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :wherehows-etl:compileJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :wherehows-backend:compilePlayBinaryScala
Pruning sources from previous analysis, due to incompatible CompileSetup.
Note: /home/rilma/Documents/Python/DataCatalog/WhereHows/wherehows-backend/app/models/daos/DatasetDao.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /home/rilma/Documents/Python/DataCatalog/WhereHows/wherehows-backend/app/controllers/Application.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :wherehows-backend:compilePlayBinaryTests
Pruning sources from previous analysis, due to incompatible CompileSetup.

> Task :wherehows-common:test

Gradle suite > Gradle test > wherehows.common.utils.JobsUtilTest.testGetEnabledJobs FAILED
    java.lang.AssertionError at JobsUtilTest.java:88

Gradle suite > Gradle test > wherehows.common.utils.JobsUtilTest.testGetEnabledJobsByType FAILED
    java.lang.AssertionError at JobsUtilTest.java:111

Gradle suite > Gradle test > wherehows.common.utils.JobsUtilTest.testGetScheduledJobs FAILED
    java.lang.AssertionError at JobsUtilTest.java:64

13 tests completed, 3 failed

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':wherehows-common:test'.
> There were failing tests. See the report at: file:///home/rilma/Documents/Python/DataCatalog/WhereHows/wherehows-common/build/reports/tests/test/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED in 23s
36 actionable tasks: 30 executed, 6 up-to-date
##################################################################

**Comment by rilma** [comment]
I have made a new try today and it worked well. I have made sure the extra library files are available the "wherehows-etl/extralibs" folder. In summary, I run the following commands to install the package.

```
$ git clone https://github.com/linkedin/WhereHows.git
$ cd WhereHows
$ export JAVA_HOME=/usr/lib/jvm/default-java
$ ./gradlew clean build
```

Where can I get the package documentation?

**Comment by joaolcorreia** [comment]
@rilma which packages did you add to fix it? I dont need Oracle do I still need to add them?
