### ISSUE TITLE
wh_etl_job_property confusion

### ISSUE THREAD

**Issue by carnalim** [linkedin/WhereHows#87]
I have a few questions about the hdfs.remote.* properties. In the documentation it is a bit unclear. 

- If I choose my remote.machine as localhost, there should be no jython copying of the .jar correct? 

- hdfs.remote.sample In the VM you have it populated like: .wherehows/hdfs_sample.dat what does that mean? What is .wherehows? 

- For the JAR do I build it from the source like gradle dist in the hadoop-dataset-extractor-standalone and than put it somewhere on the local machine and populate the hdfs.remote.jar location for it? 

- Do you have any performance metrics around hdfs.num_of_threads and what is recommended?

**Comment by SunZhaonan** [comment]
* Whatever the remote.machine set,  it will use jsch copy the jar file to target location : https://github.com/linkedin/WhereHows/blob/master/metadata-etl/src/main/java/metadata/etl/dataset/hdfs/HdfsMetadataEtl.java#L78

* `.wherehows` is the target folder that we put the output data in, you can specify any folder as you like

* After you build, the `schemaFetch.jar` should be in the lib folder, and inside the job HdfsMetadataETl we will copy this jar file to `hdfs.remote.jar` location (code in first comment)

* Haven't done a complete performance test yet. In our case, we have about 25k readable datasets in the white list, we always use 3 thread and it could be done within 1 hour. (Currently the threads split the entry points in the white list, it is not an optimized distribute strategy yet. e.g. if your entry point is just a root folder '/', there will be only one thread running no matter how many thread you specify.) This performance part definately could be improved.
