### ISSUE TITLE
Missing or invalid [username]

### ISSUE THREAD

**Issue by rilma** [linkedin/WhereHows#874]
I have satisfactorily installed the WhereHows project using the Docker Compose script available at "WhereHows/wherehows-docker". When I open the link "http://localhost:9001" in my browser, the interface requests my credentials (e.g. Username and Password). Would please suggest an idea how I can set them up so I can login in? Thanks!

**Comment by sagartoms** [comment]
You can create a user manually in the sql table as shown in https://github.com/linkedin/WhereHows/issues/616

**Comment by rilma** [comment]
The following SQL command allowed me to add a user to the backend database:

`INSERT INTO wherehows.users (name, email, username, password_digest, password_digest_type, authentication_type)
VALUES ('Your Name', 'username@domain.com', 'YourUsername, SHA1('YourPassword'), 'SHA1', 'default');`

Thanks!

**Comment by swarupa3** [comment]
Thanks in advance 
could you please suggest me that where i need to give sql statement i mean i which file i need to update this statement

**Comment by yynelson** [comment]
@swarupa3 in your mysql shell
