### ISSUE TITLE
wherehows docker build.sh 1 errors

### ISSUE THREAD

**Issue by diaowenyang** [linkedin/WhereHows#880]
HI
I use v1.0.0,and when I run build.sh 1 ,error goes that:

Additional error details:
Since bower is a user command, there is no need to execute it with superuser permissions.
If you're having permission errors when using bower without sudo, please spend a few minutes learning more about how your system should work and make any necessary repairs.

http://www.joyent.com/blog/installing-node-and-npm
https://gist.github.com/isaacs/579814

You can however run a command with sudo using --allow-root option
:wherehows-web:bowerInstall FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':wherehows-web:bowerInstall'.
> Process 'command '/home/wherehows/WhereHows-1.0/WhereHows/wherehows-web/build/nodejs/node-v7.8.0-linux-x64/bin/node'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

Please help me to fix it.

**Comment by crazy2323** [comment]
I have the same error

**Comment by crazy2323** [comment]
vi ~/.bowerrc
and add content as below:
{"allow_root": true }

**Comment by lg985** [comment]
I have the same issue, how did you fix this issue?
