### ISSUE TITLE
wherehows-docker module , compile fail , because not found class

### ISSUE THREAD

**Issue by liyaqiu** [linkedin/WhereHows#893]
wherehows-docker module ,edition: latest

my operation 
   1. download resource code
   2. From the wherehows-docker, run build.sh 1    

 run build.sh 1     result:

/root/WhereHows/wherehows-etl/src/main/java/metadata/etl/sqlParser/SqlParser.java:75: 错误: 找不到符号
public static Stmt analyzeStmt(TCustomSqlStatement stmt) throws NoSqlTypeException {
^
符号: 类 TCustomSqlStatement
位置: 类 SqlParser
/root/WhereHows/wherehows-etl/src/main/java/metadata/etl/sqlParser/UpdateStmt.java:16: 错误: 程序包gudusoft.gsqlparser不存在
import gudusoft.gsqlparser.EExpressionType;

**Comment by liyaqiu** [comment]
help me,thanks

**Comment by mars-lan** [comment]
You'll find this helpful https://github.com/linkedin/WhereHows/blob/master/wherehows-docs/getting-started.md#download-third-party-jar-files

**Comment by keremsahin1** [comment]
Dear issue owner,

Thanks for your interest in WhereHows. We have recently announced DataHub which is the rebranding of WhereHows. LinkedIn improved the architecture of WhereHows and rebranded WhereHows into DataHub and replaced its metadata infrastructure in this direction. DataHub is a more advanced and improved metadata management product compared to WhereHows. 

Unfortunately, we have to stop supporting WhereHows to better focus on DataHub and offer more help to DataHub users. Therefore, we will drop all issues related to WhereHows and will not accept any contribution for it. Active development for DataHub has already started on `datahub` branch and will continue to live in there until it's finally merged to master and project is renamed to DataHub. 

Please check the `datahub` branch to get familar with DataHub.

Best,
DataHub team
