### ISSUE TITLE
I built the environment in docker mode, and the configuration file is not read。。。help me

### ISSUE THREAD

**Issue by liyaqiu** [linkedin/WhereHows#897]
I access Oracle, but when the mirror operation, found the configuration file is not read, I changed the application.env configuration file WHZ_ETL_JOBS_DIR= "under the wherehows-backend package /var/tmp/jobs, but when I started the docker mirror found no read to my Oracle job configuration

**Comment by keremsahin1** [comment]
Dear issue owner,

Thanks for your interest in WhereHows. We have recently announced DataHub which is the rebranding of WhereHows. LinkedIn improved the architecture of WhereHows and rebranded WhereHows into DataHub and replaced its metadata infrastructure in this direction. DataHub is a more advanced and improved metadata management product compared to WhereHows. 

Unfortunately, we have to stop supporting WhereHows to better focus on DataHub and offer more help to DataHub users. Therefore, we will drop all issues related to WhereHows and will not accept any contribution for it. Active development for DataHub has already started on `datahub` branch and will continue to live in there until it's finally merged to master and project is renamed to DataHub. 

Please check the `datahub` branch to get familar with DataHub.

Best,
DataHub team
