### ISSUE TITLE
Docker running wherehows configuration does not know how to read it

### ISSUE THREAD

**Issue by liyaqiu** [linkedin/WhereHows#898]
How can I read the Oracle job file I configure?

**Comment by xkcoding** [comment]
You can try `docker exec -it +` **your backend service container**`+ /bin/bash`

Then can configure the Oracle job.

This is the solution I can think of. 

Also you can configure the job before you build the images.

**Comment by keremsahin1** [comment]
Dear issue owner,

Thanks for your interest in WhereHows. We have recently announced DataHub which is the rebranding of WhereHows. LinkedIn improved the architecture of WhereHows and rebranded WhereHows into DataHub and replaced its metadata infrastructure in this direction. DataHub is a more advanced and improved metadata management product compared to WhereHows. 

Unfortunately, we have to stop supporting WhereHows to better focus on DataHub and offer more help to DataHub users. Therefore, we will drop all issues related to WhereHows and will not accept any contribution for it. Active development for DataHub has already started on `datahub` branch and will continue to live in there until it's finally merged to master and project is renamed to DataHub. 

Please check the `datahub` branch to get familar with DataHub.

Best,
DataHub team
