### ISSUE TITLE
dataset.json Not Found

### ISSUE THREAD

**Issue by rajivchodisetti** [linkedin/WhereHows#90]
Can we please have a sample "dataset.json" file shipped with the bundle for demo purpose .  And also can you please provide some CURL based examples for  "Dataset POST API" at the below wiki  https://github.com/linkedin/WhereHows/wiki/Backend-API#dataset-post

**Comment by rajivchodisetti** [comment]
Just to get a feel of how the tool works , am trying to insert a record by using the below API call , and is not working 

curl -H "Content-Type: application/json" -X POST -d '{"name" : "DUMMY4","urn" : "teradata:///DWH_TMP/DUMMY4","schema" : "{\"name\": \"DUMMY\", \"fields\": [{\"accessCount\": null, \"lastAccessTime\": null, \"nullable\": \"Y\", \"format\": null, \"type\": \"INT\", \"maxByteLength\": 4, \"name\": \"DUMMY\", \"doc\": \"\"}]}","properties" : "{\"storage_type\": \"View\", \"accessCount\": 2670, \"lastAccessTime\": null, \"sizeInMbytes\": null, \"referenceTables\": [\"DWH_DIM.DUMMY\"], \"viewSqlText\": \"REPLACE VIEW DWH_STG.DUMMY AS\nLOCKING ROW FOR ACCESS\n SELECT * \n FROM DWH_DIM.DUMMY;\", \"createTime\": \"2015-03-06 10:43:58\", \"lastAlterTime\": \"2015-03-10 20:57:16\"}","schema_type" : "JSON","fields" :"{\"DUMMY\": {\"type\": \"INT\", \"maxByteLength\": 4}}","source" : "Teradata","modified" : "2015/03/10 8:57:16","created" : null,"location_prefix" : "DWH_STG","ref_dataset_urn" : "teradata:///DWH_TMP/DUMMY2","is_partitioned" : "Y","sample_partition_full_path": "/daily/2015/10/10","parent_name" : null,"storage_type" : null,"dataset_type" : null,"hive_serdes_class" : null}' http://localhost:9000/dataset

**Comment by SunZhaonan** [comment]
As I mentioned before, even though we have those json file, if there is no content in the databases, it can't show anything on the web pages. For now the easiest way to try out the tools is to download the VM.

This API did have a bug, I'll update it soon.

**Comment by rajivchodisetti** [comment]
Once the API is fixed , can we not just convert our database metadata into the format which wherehowz understand and then insert that metadata using "POST dataset" API ... I can try VM but the VM is too big in size to download , anyhow will give a try

**Comment by ericsun2** [comment]
@rajivchodisetti 

You can surely ingest the metadata records into WhereHows backend table to test the feature.

**Comment by shweta-sah** [comment]
@ericsun2 Hi Eric, I would like to ingest some sample metadata records into the WhereHows backend tables to test some features in my local installation. Where should I get the metadata records from?
