### ISSUE TITLE
HIVE_METADATA_ETL.job

### ISSUE THREAD

**Issue by yuexiaojie1620** [linkedin/WhereHows#902]
set  dataset job Not active . 

edit HIVE_METADATA_ETL.job job.cron.expr=0 0/15 * * * ? *

I do not know where the problem is 。

help me。😢

![image](https://user-images.githubusercontent.com/9793747/33712946-3411b8e0-db84-11e7-853b-0a05d7c9b453.png)

![image](https://user-images.githubusercontent.com/9793747/33712883-f61aead4-db83-11e7-9563-e472a56b4392.png)

**Comment by visokoo** [comment]
After editing the file, you need to make sure it's present in the /applications/jobs/ directory on the backend node.

**Comment by yuexiaojie1620** [comment]
@visokoo 
hi !
     hello
Deployed on Docker with master tag version 1.0.0
I modified the file
![image](https://user-images.githubusercontent.com/9793747/33751342-3cc192ee-dc15-11e7-8279-da8bcc3e8055.png)

**Comment by yuexiaojie1620** [comment]
@visokoo
Check the log and found it did not perform, but also need to modify where?

**Comment by yuexiaojie1620** [comment]
@visokoo  

You are right. My directory is misplaced !!
thx

**Comment by yinsong** [comment]
@yuexiaojie1620 
hi,in tag 1.1.0 i configure HIVE_METADATA_ETL.job and start backend service 
but get error  [WhereHowsETLService-akka.actor.default-dispatcher-2] [akka://WhereHowsETLService/user/SchedulerActor] null
java.lang.NullPointerException,
how can i resolve it
