### ISSUE TITLE
MySQLSyntaxErrorException: Table 'wherehows.log_dataset_instance_load_status' doesn't exist

### ISSUE THREAD

**Issue by cvraghav** [linkedin/WhereHows#929]
frontend is throwing an error - table log_dataset_instance_load_status does not exist. I didn't find any references to that table in sql scripts. Anyone having similar issue?

https://github.com/linkedin/WhereHows/blob/0cd9d682580d8004ab6ed23d0c1db257043770b2/wherehows-frontend/app/dao/DatasetsDAO.java#L350

**Comment by alyiwang** [comment]
#1054 should fix this
