### ISSUE TITLE
what is wrong when i building the project ,give me help........

### ISSUE THREAD

**Issue by wuchenlv1988** [linkedin/WhereHows#952]
make: *** [Release/obj.target/libsass/src/libsass/src/ast.o] Error 1
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
make: Leaving directory `/software/git/WhereHows/wherehows-web/node_modules/node-sass/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/software/git/WhereHows/wherehows-web/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 2.6.32-573.8.1.el6.x86_64
gyp ERR! command "/software/git/WhereHows/wherehows-web/build/nodejs/node-v8.9.4-linux-x64/bin/node" "/software/git/WhereHows/wherehows-web/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /software/git/WhereHows/wherehows-web/node_modules/node-sass
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
Build failed with error code: 1

:wherehows-web:yarn (Thread[Task worker for ':',5,main]) completed. Took 1 mins 4.695 secs.

FAILURE: Build failed with an exception.

**Comment by camelliazhang2018** [comment]
@theseyi Hi Seyi, Can you please help with this issue? Thanks~

**Comment by xkcoding** [comment]
you can try another NPM Mirror like https://npm.taobao.org/  or others

**Comment by keremsahin1** [comment]
Dear issue owner,

Thanks for your interest in WhereHows. We have recently announced DataHub which is the rebranding of WhereHows. LinkedIn improved the architecture of WhereHows and rebranded WhereHows into DataHub and replaced its metadata infrastructure in this direction. DataHub is a more advanced and improved metadata management product compared to WhereHows. 

Unfortunately, we have to stop supporting WhereHows to better focus on DataHub and offer more help to DataHub users. Therefore, we will drop all issues related to WhereHows and will not accept any contribution for it. Active development for DataHub has already started on `datahub` branch and will continue to live in there until it's finally merged to master and project is renamed to DataHub. 

Please check the `datahub` branch to get familar with DataHub.

Best,
DataHub team
