### ISSUE TITLE
error when doing "docker-compose up"

### ISSUE THREAD

**Issue by richardxin** [linkedin/WhereHows#963]
I follwoed Docker Getting Start Guide, saw error when doing "docker-compose up"
ERROR: for wherehowsdocker_wherehows-mysql_1  Cannot start service wherehows-mysql: driver failed programming external connectivity on endpoint wherehowsdocker_wherehows-mysql_1 (33c6e19419e1edb7284cfeb2008ea43a7cf5ce5aa80c73b1d852952c24d61d83): Error starting userland proxy: Bind for 0.0.0.0:3306 failed: port is already allocated

ERROR: for wherehows-mysql  Cannot start service wherehows-mysql: driver failed programming external connectivity on endpoint wherehowsdocker_wherehows-mysql_1 (33c6e19419e1edb7284cfeb2008ea43a7cf5ce5aa80c73b1d852952c24d61d83): Error starting userland proxy: Bind for 0.0.0.0:3306 failed: port is already allocated
ERROR: Encountered errors while bringing up the project.

I have checked followings:
1) $ lsof|grep 3306 didn't return anything
2) tried to change 3306 in wherehows-mysql/Dockerfile AND docker-compose.yml to a random port #, I got mysql connection rejected error.

Please help, thanks

**Comment by richardxin** [comment]
can anyone help?

I tried the same on 2 macbook, same error.

**Comment by camelliazhang2018** [comment]
@richardxin Is there any existing mySQL installed on your local machine? You need to close it or disable 3306 port first before you start your docker
