### ISSUE TITLE
is Piwik a required component to run Wherehows?

### ISSUE THREAD

**Issue by richardxin** [linkedin/WhereHows#968]
I saw errors in the frontend service log:
2018-02-14 23:54:33 ERROR application:177 - Piwik site ID must be an integer

It seems the root cause was that I didn't set values for:
https://github.com/linkedin/WhereHows/blob/master/wherehows-frontend/conf/application.conf#L92-L93

is Piwik a required component to run Wherehows?

**Comment by alyiwang** [comment]
It's not required. The UI will function just fine without it.
