### ISSUE TITLE
ReadJsonQueryFile failed due to null jsonFile value

### ISSUE THREAD

**Issue by richardxin** [linkedin/WhereHows#969]
I'm having an issue that readJsonQueryFile(String jsonFile) in https://github.com/linkedin/WhereHows/blob/master/wherehows-frontend/app/utils/Search.java#L43
throws exception: "ReadJsonQueryFile failed. Error:" , after debugging I found that input "jsonFile" had value of null.

The error happened when I typed 3rd characters on the search bar, and auto-complete is initiated.

and null value came from System.getenv("WHZ_ELASTICSEARCH_AUTO_COMPLETION_QUERY_TEMPLATE");
at Search.java#L40

I searched repo, but not able to find WHZ_ELASTICSEARCH_AUTO_COMPLETION_QUERY_TEMPLATE is defined/set anywhere. Where should WHZ_ELASTICSEARCH_AUTO_COMPLETION_QUERY_TEMPLATE be defined/set and where can I find the example of the template file?

My suggestion: 
1) on application start, we need a process to check ALL required fields and other prerequisites -- fail fast if requirements not met
2) good documentation and examples

**Comment by richardxin** [comment]
And I'm seeing exact same exception with your docker demo running on my laptop.

**Comment by richardxin** [comment]
I checked out most recent tag 1.0.0 from git instead of from master, doesn't have that same error any more, the property was introduced after the tag. I'm using tag 1.0.0 for now...

**Comment by camelliazhang2018** [comment]
@richardxin 
We recently refactored our code. 
WHZ_ELASTICSEARCH_AUTO_COMPLETION_QUERY_TEMPLATE
And other query template can be found here:
https://github.com/linkedin/WhereHows/tree/master/wherehows-data-model/ELASTICSEARCH

They need to put into your application env.
I will update the related docs, sorry for the confusion. 
It will be similar like this: 
WHZ_ELASTICSEARCH_DATASET_QUERY_TEMPLATE = "${basedir}/conf/elasticsearch/dataset_query_template.json"

WHZ_ELASTICSEARCH_AUTO_COMPLETION_QUERY_TEMPLATE =
"${basedir}/conf/elasticsearch/auto_completion_query_template.json"

WHZ_ELASTICSEARCH_COMMENT_QUERY_TEMPLATE=
"${basedir}/conf/elasticsearch/comment_query_template.json"

WHZ_ELASTICSEARCH_FILTER_UNIT =
"${basedir}/conf/elasticsearch/filter_unit.json"

WHZ_ELASTICSEARCH_FLOW_QUERY_TEMPLATE=
"${basedir}/conf/elasticsearch/flow_query_template.json"

WHZ_ELASTICSEARCH_METRIC_QUERY_TEMPLATE=
"${basedir}/conf/elasticsearch/metric_query_template.json"

WHZ_ELASTICSEARCH_SUGGESTER_QUERY_TEMPLATE=
"${basedir}/conf/elasticsearch/suggester_query_template.json"

**Comment by richardxin** [comment]
not seeing this issue any more after following @camelliazhang2018's instruction above
