### ISSUE TITLE
etl job config's job.disabled=0 doesn't enable the job

### ISSUE THREAD

**Issue by richardxin** [linkedin/WhereHows#974]
I expect that setting job.disabled=0 will enable the job, but it seems that I have to comment out this line to enable the job
looking at the source code, the code only check for existence of the property, doesn't care about the value of the property, is that expected behavior?
for example: 
https://github.com/linkedin/WhereHows/blob/master/wherehows-common/src/main/java/wherehows/common/utils/JobsUtil.java#L108

if (!prop.containsKey(Constant.JOB_DISABLED_KEY))

**Comment by alyiwang** [comment]
Yes, that's expected. The documentation is a bit unclear about this.
